---
title: "NP CONAPESCA Data Exploration_Oct thru Nov 2025_EMF"
output: html_document
date: "2025-10-29"
---

# Natural Products Inquiry (dataMares data) (October 2025) ----------------
## Understanding OTRAS
```{r CONAPESCA OTRAS explore}
CONAPESCA_data_dataMares <- read_csv("/Users/ferrer/Desktop/OHI/FP/dataMares_CONAPESCA_Data_Oct6_2025.csv")
names(CONAPESCA_data_dataMares) <- c("Index", "Year", "State", "Office", "Taxa", "General_Sp_Name", "Sp_Scientific_Name", "Fishery_Type", "Landing_Site", "Fishing_Site", "Days_Spent", "Date", "Revenue_mxn", "Biomass_kg", "Price_mxn")

table(CONAPESCA_data_dataMares$General_Sp_Name)
table(CONAPESCA_data_dataMares$Sp_Scientific_Name[which(CONAPESCA_data_dataMares$General_Sp_Name=="CORVINA")])
# OTRAS = 616392 obs.

States_of_Interest<- c("BAJA CALIFORNIA", "BAJA CALIFORNIA SUR", "SONORA", "SINALOA", "NAYARIT", "JALISCO")

Landings_filtered<- CONAPESCA_data_dataMares %>% filter(State %in% States_of_Interest)
# n obs.= 4,755,692

OTRAS_dataMares<- Landings_filtered %>% filter(General_Sp_Name=="OTRAS")
# n obs.= 616,392

CORVINA_dataMares<- Landings_filtered %>% filter(General_Sp_Name=="CORVINA")
# n obs.= 178,051
```

```{r Understanding OTRAS}
table(OTRAS_dataMares$Sp_Scientific_Name)
table(OTRAS_dataMares$Year) # 24 years of coverage, 2000-2023
names(OTRAS_dataMares)

OTRAS_summary <- OTRAS_dataMares %>%
  select(Year, State, Sp_Scientific_Name, Biomass_kg, Revenue_mxn) %>%
  group_by(Year, State, Sp_Scientific_Name) %>%
  summarise(
    Total_Biomass = sum(Biomass_kg, na.rm = TRUE),
    Total_Revenue = sum(Revenue_mxn, na.rm = TRUE),
    n_Records = n(),
    .groups = "drop"  # optional: ungroup after summarising
  )

# Identify species with ≥10 records in MOST years
# Step 1: get the number of unique years in your dataset
n_years <- OTRAS_summary %>% pull(Year) %>% unique() %>% length()

# Step 2: filter and summarize
species_with_10plus_most_years <- OTRAS_summary %>%
  group_by(Year, Sp_Scientific_Name, State) %>%
  summarise(yearly_records = sum(n_Records), .groups = "drop") %>%
  filter(yearly_records >= 10) %>%
  distinct(Sp_Scientific_Name, Year) %>%
  count(Sp_Scientific_Name) %>%
  filter(n > n_years / 2) %>%
  pull(Sp_Scientific_Name)

OTRAS_filtered<- OTRAS_dataMares %>% filter(Sp_Scientific_Name %in% species_with_10plus_most_years)

OTRAS_filtered_summary <- OTRAS_filtered %>%
  select(Year, State, Sp_Scientific_Name, Biomass_kg, Revenue_mxn) %>%
  group_by(Year, State, Sp_Scientific_Name) %>%
  summarise(
    Total_Biomass = sum(Biomass_kg, na.rm = TRUE),
    Total_Revenue = sum(Revenue_mxn, na.rm = TRUE),
    n_Records = n(),
    .groups = "drop"  # optional: ungroup after summarising
  )
```

```{r Plot OTRAS}
OTRAS_plot<- OTRAS_filtered_summary %>%
  filter(!Sp_Scientific_Name== "ND") %>%
  ggplot(aes(x = Year, y = Total_Biomass, color = Sp_Scientific_Name)) +
  geom_line(size = 1) +
  facet_wrap(~State, scales = "free_y") +
  labs(
    title = "Biomass Landed Over Time by Fishery and State",
    x = "Year",
    y = "Total Biomass (kg)",
    color = "Species"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    strip.text = element_text(face = "bold")
  )

OTRAS_plot
```

```{Save plot}
ggplotly(OTRAS_plot)

ggsave(
  filename = "Desktop/OHI/FP/Otras_Biomass_Plot_Oct8_2025.png",  # file name
  plot = OTRAS_plot,            # the plot object
  width = 10,                        # width in inches
  height = 10,                        # height in inches
  dpi = 300                         # resolution (dots per inch)
)
```

## Understanding CORVINA:
```{r Understanding CORVINA}
CORVINA_summary <- CORVINA_dataMares %>%
  select(Year, State, Sp_Scientific_Name, Biomass_kg, Revenue_mxn) %>%
  group_by(Year, State, Sp_Scientific_Name) %>%
  summarise(
    Total_Biomass = sum(Biomass_kg, na.rm = TRUE),
    Total_Revenue = sum(Revenue_mxn, na.rm = TRUE),
    n_Records = n(),
    .groups = "drop"  # optional: ungroup after summarising
  )
```

```{r Plot CORVINA}
CORVINA_plot<- CORVINA_summary %>%
  ggplot(aes(x = Year, y = Total_Biomass, color = Sp_Scientific_Name)) +
  geom_line(size = 1) +
  facet_wrap(~State, scales = "free_y") +
  labs(
    title = "Corvina Sp. Biomass Landed Over Time by and State",
    subtitle = "Totoaba is Totoaba macdonaldi; technically illegal to fish since the 1970s",
    x = "Year",
    y = "Total Biomass (kg)",
    color = "Species"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    strip.text = element_text(face = "bold")
  )

CORVINA_plot
```

## Understanding SEASHELLS:
```{r Seashells}
Species_data <- read_csv("/home/ferrer/ohi_goc_prep/FP/FIS/v2025/CONAPESCA_Sp_MasterFile_EMF.csv")

Species_data <- Species_data %>%
  mutate(across(everything(), ~ if (is.character(.)) str_to_lower(.) else .))

CONAPESCA_data_naturalproducts0 <- CONAPESCA_data_filtered %>%
  mutate(across(everything(), ~ if (is.character(.)) str_to_lower(.) else .))

names(CONAPESCA_data_naturalproducts0) <- c("index", "consulta", "state", "office", "taxa", "general_sp_name", "sp_scientific_name", "fishery_type", "landing_site", "fishing_site", "days_spent", "fecha", "revenue_mxn", "biomass_kg", "price_mxn", "date", "year", "month", "day", "CPUE_est")

CONAPESCA_data_naturalproducts0 <- CONAPESCA_data_naturalproducts0 %>%
  left_join(Species_data, by = c("sp_scientific_name" = "ScientificName"))

table(CONAPESCA_data_naturalproducts0$NewClass)
```


# Natural Products Inquiry (J.C. CONAPESCA data) (November 2025) ----------------

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
# Visualization
library(ggplot2)
library(plotly)
library(htmlwidgets)


setwd("/home/ferrer/ohi_goc_prep/NP/")
```

```{r Natural Products Production Associated with Top Landings}
Landings_GoC_TopGroupings_wSp<- readRDS("/home/shares/ohi/OHI_GOC/goal_prep/fis/v2025/int/juan_carlos/TopGroupings_Landings_2000.present_wSp_Nov102025.rds")
LandingReceipts_Keywords<- read_csv("/home/ferrer/ohi_goc_prep/FP/EMF_CONAPESCA_Exploration/LandingReceipts_KeywordsKey_Nov102025.csv")

NP_Keywords <- LandingReceipts_Keywords %>%
  filter(NP_flag %in% c("yes", "maybe")) %>%
  pull(Keyword)

NP_Landings <- Landings_GoC_TopGroupings_wSp %>%
  filter(keyword_1 %in% NP_Keywords |
           keyword_2 %in% NP_Keywords |
           keyword_3 %in% NP_Keywords |
           keyword_4 %in% NP_Keywords |
           keyword_5 %in% NP_Keywords)

unique(NP_Landings$common_name_english_estimated)
# Previous: 3031 obs. over 17 taxa (common names)
# WITH SHARK FIN: 18495 obs. over 26 taxa (common names)
# NOTE: adding additional key word "BUCHE", "CARNADA", AND "S.C." did not change total NP observations.

unique(NP_Landings$species_name)
# Previous: And 21 styles of preparation
# And 65 styles of preparation
```

```{r NP Summary Table}
# How many species (log-book entries) are there per grouping?
NP_summary_table <- NP_Landings %>%
  select(common_name_english_estimated, species_name) %>%
  group_by(common_name_english_estimated) %>%
  summarize(species_list = paste(unique(species_name), collapse = ", "))
```

```{r Let's look in the CONAPESCA database for very specific types of shellfish}
# Pinctada mazatlanica (Mother of pearl)
# Pteria sterna (nacre) 
# Pinctada imbricata (Atlantic mother of pearl)
# Pteria colymbus (Atlantic winged pearl oyster)

AllLandings_GoC<- readRDS("/home/shares/ohi/OHI_GOC/goal_prep/fis/v2025/int/juan_carlos/GoC_Landings_2000.present_EMF_created.rds")
# 3716415 obs.

AllLandings_GoC <- AllLandings_GoC %>%
  mutate(species_name = stri_trans_general(species_name, "latin-ascii"))
# 3716415 obs.

possible_shellfish <- AllLandings_GoC %>%
  filter(grepl("pter|pinc", species_name, ignore.case = TRUE)) %>%
  distinct(species_name)
# 0 obs.

AllLandings_GoC <- AllLandings_GoC %>%
  mutate(species_clean = gsub("[^A-Za-z]", "", species_name))
# 3716415 obs.

AllLandings_GoC %>%
  filter(grepl("Pteria|Pinctada", species_clean, ignore.case = TRUE)) %>%
  distinct(species_name)
```
Can't find any landings with Pinctada or Pteria in the name...

```{r Let's look into just the ALMEJA and CARACOL}
##### ALMEJA and CARACOL
Seashell_Landings<- AllLandings_GoC %>% filter(main_species_group==c("ALMEJA", "CARACOL"))
# 50336 obs.

unique(Seashell_Landings$species_name)
```
```{r Filter out keywords from recorded_species_name}
# List of all key terms:
keyword_list <- c(
  "DESC", "IND", "ENT", "FCO", "DESV", "S", "FCA", "DES", "DSC", 
  "ECO", "CONG", "CONGELADO", "DE CULTIVO", "DE CULTIVO VIVO", 
  "FILETE", "FILETE DE", "ECA", "CABEZA DE", "FILETE DE ECO", 
  "PIEL DE ECA", "PIEL DE SECA", "ALETA ECA DE", "DESCABEZADO", "FRESCO", "SECO DE", "ALETA", "SECA", "SECA DE", "SECO", "SECO DE", "DE ALTA MAR", "ENTERO",
  "POLVO DE", "CONCHA DE", "COCINERO",
  "CARNADA", "BUCHE", "S.C."
)

# NOTE TO SELF: THIS LIST IS UNDER CONSTRUCTION (as of Nov 10 2025)

# Sort by descending length to match multi-word keywords first
keyword_list <- keyword_list[order(nchar(keyword_list), decreasing = TRUE)]

Seashell_Sp_List <- Seashell_Landings %>%
  select(main_species_group, recorded_species_name = species_name) %>%
  distinct() %>%
  
  # Extract keywords
  mutate(
    keywords = str_extract_all(
      recorded_species_name,
      paste0("\\b(", paste(keyword_list, collapse="|"), ")\\b[.,]?")
    )
  ) %>%
  
  # Pad for unnesting
  mutate(keywords = lapply(keywords, function(x) { length(x) <- 5; x })) %>%
  unnest_wider(keywords, names_sep = "_") %>%
  rename(
    keyword_1 = keywords_1,
    keyword_2 = keywords_2,
    keyword_3 = keywords_3,
    keyword_4 = keywords_4,
    keyword_5 = keywords_5
  ) %>%
  
  # Clean species names (remove keywords and extra spaces)
  mutate(
    recorded_species_name_clean = str_remove_all(
      recorded_species_name,
      paste0("\\b(", paste(keyword_list, collapse="|"), ")\\b[.,]?")
    ),
    recorded_species_name_clean = str_remove_all(recorded_species_name_clean, "\\bY\\b"),
    recorded_species_name_clean = str_squish(recorded_species_name_clean)
  )

Seashell_Sp_List <- Seashell_Sp_List %>%
  arrange(main_species_group, recorded_species_name_clean)

unique(Seashell_Sp_List$keyword_1)
unique(Seashell_Sp_List$recorded_species_name_clean)

# Only 83 names to sort through here!!
```

```{r save this as a CSV}
write.csv(Seashell_Sp_List, "/home/ferrer/ohi_goc_prep/NP/v2025/Seashell_Sp_Nov102025.csv", row.names = FALSE)
```

