---
title: 'OHI GoC 2025: Clean waters pesticides'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# CW: Pesticides

## Current status

```{r setup}
library(sf)
library(utils)
library(tidyverse)
library(here)
library(raster)
library(mapview)
library(purrr)
library(stringr) # fuzzy string matching
library(stringi)
library(janitor)
library(tibble)
```

### Read in agriculture estimates


```{r}
total_ag_pesticides_kg <- st_read(here::here("/home/shares/ohi/OHI_GOC/goal_prep/cw/v2025/pesticides/int", "total_agriculture_pesticides_kg_pourpoints_rgnid_allyears.gpkg")) %>% 
  rename(ag_pesticide_kg = total_pesticide_kg)
```


### Read in shrimp farming estimates

```{r}
total_aq_lime_kg <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/cw/v2025/pesticides/int/shrimp_lime_kg_by_rgnid_lyle_fritch.csv")) %>% 
  select(rgn_id, year, aqua_lime_kg = lime_kg)
```

^ estimate as a risk factor (score each source first)


### Agriculture + aquaculture estimates per region and year

```{r}
total_pesticide_and_chem_kg <- full_join(total_ag_pesticides_kg, total_aq_lime_kg) %>% 
  mutate(aqua_lime_kg = ifelse(is.na(aqua_lime_kg), 0, aqua_lime_kg),
         ag_pesticide_kg = ifelse(is.na(ag_pesticide_kg), 0, ag_pesticide_kg)) %>% 
  mutate(total_chem_kg = ag_pesticide_kg + aqua_lime_kg)
```


## Current status

$$current\ status\ _{pesticides} = 1 - \frac{pesticides\ _{current} - pesticides\ _{ideal}}{pesticides\ _{maximum} - pesticides\ _{ideal}}$$

Where the ideal is zero, and the maximum is the global maximum of kg estimated across all years and regions.

```{r}
current_status_pesticides <- total_pesticide_and_chem_kg %>% 
  mutate(
    ideal = 0,
    maximum = max(total_chem_kg),
    current_status = 1 - ((total_chem_kg - ideal)/(maximum - ideal)),
    current_status_final = current_status * 100
  )

current_status_pesticides_ag <- total_ag_pesticides_kg %>% 
  mutate(
    ideal = 0,
    maximum = max(ag_pesticide_kg),
    current_status = 1 - ((ag_pesticide_kg - ideal)/(maximum - ideal)),
    current_status_final = current_status * 100
  )
```


### plotly

```{r}
library(plotly)

rgn_colors <- c(
  Region_1 = "#C03729",
  Region_2 = "#E68C7C",
  Region_3 = "#FC8F24",
  Region_4 = "#dcaa38",
  Region_5 = "#cbd2a0",
  Region_6 = "#98a25a",
  Region_7 = "#747428",
  Region_8 = "#627391",
  Region_9 = "#8d61a9"
)

## plot the pesticide cs over time
pesticide_plotly <- plotly::plot_ly(
  current_status_pesticides, 
  x = ~year, 
  y = ~current_status_final, 
  color = ~rgn_id, 
  colors = rgn_colors,
  type = "scatter", 
  mode = "lines+markers"
) %>% 
  layout(
    title = "Clean Waters: Pesticide Current Status",
    xaxis = list(title = "ano // Year"),
    yaxis = list(title = "Puntaje // Percent (out of 100)")
  ) %>%
  add_lines( 
    x = range(current_status_pesticides$year), 
    y = c(100, 100),
    line = list(color = "black", width = 2, dash = "dash"),
    name = "Meta // Goal (100/100)",
    inherit = FALSE
  )
pesticide_plotly

## plot the pesticide cs over time
ag_pesticide_plotly <- plotly::plot_ly(
  current_status_pesticides_ag, 
  x = ~year, 
  y = ~current_status_final, 
  color = ~rgn_id, 
  colors = rgn_colors,
  type = "scatter", 
  mode = "lines+markers"
) %>% 
  layout(
    title = "Clean Waters: AG Pesticide Current Status",
    xaxis = list(title = "ano // Year"),
    yaxis = list(title = "Puntaje // Percent (out of 100)")
  ) %>%
  add_lines( 
    x = range(current_status_pesticides_ag$year), 
    y = c(100, 100),
    line = list(color = "black", width = 2, dash = "dash"),
    name = "Meta // Goal (100/100)",
    inherit = FALSE
  )
ag_pesticide_plotly
```

