---
title: 'OHI GoC 2024: Catch Per Unit Effort GoC'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: inline
editor_options: 
  chunk_output_type: inline
---

# Summary

## Global Datasets of AIS-based Fishing Effort and Vessel Presence

This dataset contains the Global Fishing Watch AIS-based fishing effort and vessel presence datasets.
Data is based on fishing detections of \>114,000 unique AIS devices on fishing vessels, of which \~70,000 are active each year.
Fishing vessels are identified via a neural network classifier, vessel registry databases, and manual review by GFW and regional experts.
Data are binned into grid cells 0.01 (or 0.1) degrees on a side and measured in units of hours.
The time is calculated by assigning an amount of time to each AIS detection (which is the time to the previous position), and then summing all positions in each grid cell.

**Current version**

2.0: Fishing effort data for 2012-2020 using our latest AIS algorithms, neural network models, and vessel registry database.

**File structure**

Fishing effort and vessel presence data are available as .csv files in daily formats.
Files for each year are stored in separate .zip files.
A README.txt file is provided for each dataset version and contains the table schema and additional information.
There is also a README-known-issues-v2.txt file outlining some of the known issues with the version 2 release.

Files are names according to the following convention:

Daily file format: \[fleet/mmsi\]-daily-csvs-\[100/10\]-\[version\]-\[year\].zip

Fishing vessel format: fishing-vessels-\[version\].csv

README file format: README-\[fleet/mmsi/fishing-vessels\]-\[version\].txt File identifiers:

-   \[fleet/mmsi\]: Data by fleet (flag and geartype) or by MMSI \[100/10\]: 100th or 10th degree resolution

-   \[version\]: Fishing effort version (v2, v1-5,v1)

-   \[year\]: Year of data included in .zip or .csv file

Examples: fleet-daily-csvs-100-v2-2020.zip; mmsi-daily-csvs-10-v2-2020.csv; fishing-vessels-v2.csv; README-fleet-v2.txt

**Reference & Code**

For additional information about these results, see the associated journal article: D.A.
Kroodsma, J. Mayorga, T. Hochberg, N.A. Miller, K. Boerder, F. Ferretti, A. Wilson, B. Bergman, T.D. White, B.A. Block, P. Woods, B. Sullivan, C. Costello, and B.
Worm.
"Tracking the global footprint of fisheries." Science 361.6378 (2018).

GitHub repository for Tracking the global footprint of fisheries: https://github.com/GlobalFishingWatch/paper-global-footprint-of-fisheries License: Unless otherwise stated, Global Fishing Watch data is licensed under a Creative Commons Attribution-ShareAlike 4.0 International license and code under an Apache 2.0 license.

-----------------------------------------------------------

# Setup 

```{r}
library(tidyverse)
library(magrittr)
library(here)
library(tictoc)
library(kableExtra)
library(plotly)
library(viridis)
library(readr)
library(purrr)

# for Global Fishing Watch API (using package gfwr)
# install.packages("gfwr", repos = c("https://globalfishingwatch.r-universe.dev", "https://cran.r-project.org"))
library(gfwr)

# obtaining API key -- follow the instructions using .Renviron here <https://github.com/GlobalFishingWatch/gfwr>
# usethis::edit_r_environ()
key <- gfw_auth()

# ---- sources! ----
# source(here("workflow", "R", "common.R")) # file creates objects to process data
## set the mazu and neptune data_edit share based on operating system
dir_M             <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
                       'Darwin'  = '/Volumes/ohi',    ### connect (cmd-K) to smb://mazu/ohi
                       'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

# ---- set year and file path info ----
current_year <- 2025 # Update this in the future!!
version_year <- paste0("v",current_year)
data_dir_version_year <- paste0("d", current_year)

# ---- data directories ----

# raw data directory (on Mazu)
raw_data_dir <- here::here(dir_M, "OHI_GOC", "_raw_data")

# final output dir
output_dir <- here("FIS", version_year, "output")
```






