---
title: "Untitled"
output: html_document
date: "2025-09-29"
---
Exploring Juan Carlos fishing data

https://github.com/mex-Fisheries

office Names?
https://github.com/mex-fisheries/mex_ports/blob/main/data/clean/mex_ports.csv
also: mex_vessel_registry

```{r setup, include=FALSE}
library(tidyverse)
jc_data <- "/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean"

list.files(jc_data)
```


```{r}

## year, eu_rnpa, species group, weight/value 
tmp <- readRDS(file.path(jc_data, "mex_annual_landings_by_eu.rds"))

## year, landing_site_key, species group, weight/value 
tmp <- readRDS(file.path(jc_data, "mex_annual_landings_by_landing_site.rds"))
unique(tmp$landing_site_key)
tmp2 <- filter(tmp, landing_site_key == "25E") # sinaloa

## year, eu_rnpa, vessel__rnpa, species group, weight/value
tmp <- readRDS(file.path(jc_data, "mex_annual_landings_by_vessel.rds"))
head(tmp)

## this is very complete
tmp <- readRDS(file.path(jc_data, "mex_conapesca_apertura_2018_present.rds")) %>%
  filter(state %in% c("BAJA CALIFORNIA", "BAJA CALIFORNIA SUR", " NAYARIT", "JALISCO", "SINALOA", "SONORA")) %>%
  filter(fishing_zone_type != "AGUAS CONTINENTALES")

baja <- tmp <- readRDS(file.path(jc_data, "mex_conapesca_apertura_2018_present.rds")) %>%
  filter(state %in% c("BAJA CALIFORNIA")) %>%
  filter(fishing_zone_type != "AGUAS CONTINENTALES")


head(tmp)
table(tmp$office_name, tmp$landing_site)
table(tmp$fleet)
sort(unique(tmp$office_name))
sort(unique(tmp$landing_site))
sort(unique(tmp$fishing_site_name))
unique(tmp$economic_unit)
unique(tmp$fishing_site_name)
unique(tmp$acuaculture_production)
unique(tmp$fishing_zone_type). # filter: "AGUAS CONTINENTALES"
ensenada <- filter(tmp, office_name == "ENSENADA")
length(table(ensenada$landing_site))

no_baja <- readRDS(file.path(jc_data, "mex_conapesca_apertura_2018_present.rds")) %>%
  filter(state %in% c( "BAJA CALIFORNIA SUR", " NAYARIT", "JALISCO", "SINALOA", "SONORA")) %>%
  filter(fishing_zone_type != "AGUAS CONTINENTALES")
intersect(ensenada$landing_site, no_baja$landing_site)


## state, office, eu_rnpa, vessel_rnpa, species group, livewieght, value
tmp <- readRDS(file.path(jc_data, "mex_landings_2000_2022.rds")) 
head(tmp)
length(table(tmp$office_name))


## state, office, landing_site, month, permit (eu), eu_rnpa, vessel_rnpa, species group, livewieght, value
tmp <- readRDS(file.path(jc_data, "mex_landings_2000_present.rds")) 
head(tmp)
length(table(tmp$office_name))

## year, month, eu, speicesgroup, weight/value
tmp <- readRDS(file.path(jc_data, "mex_monthly_landings_by_eu.rds")) 
head(tmp)

## year, month, landing_site_key, species_group, weight/value
tmp <- readRDS(file.path(jc_data, "mex_monthly_landings_by_landing_site.rds")) 
head(tmp)

## year, month, eu, vellse, speciesgroup, weight/value
tmp <- readRDS(file.path(jc_data, "mex_monthly_landings_by_vessel.rds")) 
head(tmp)


```