---
title: "OHI GOC final scores first draft (Sep 2026)"
author: "Erica Ferrer"
date: "`r Sys.Date()`"
output: html_document
---

# PRE-WORK ------------------------------

```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load libraries & set working directories}
library(tidyverse)
library(here)
library(plotly)
library(zoo)

# No scientific notation:
options(scipen = 999)

final_output_dir <- "/home/ferrer/ohi_goc_prep/_index_scores_1.0/_goal_scores_1.0/"
```

```{r Load clean_names_lowercase function}
clean_names_lowercase <- function(x) {

  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")

  x %>%
    tolower() %>%
    trimws()
}
```


# LOAD AND PREP INDIVIDUAL GOAL SCORES ------------------------------

# AO (access_opportunities)

```{r access_opportunities AKA artisanal_fishing_opporunities}
# Load original:
AFO_Scores0 <- read_csv(here::here("/home/ferrer/ohi_goc_prep/AO/v2026/AO_Scores/AFO_Scores/AFO_Scores_1.0_df_Jun152026.csv"))
# 70 obs., 3 vars.

colnames(AFO_Scores0)

# Clean:
AO_Scores<- AFO_Scores0 %>%
  select(year, OHI_region_no = OHI_region_est, AO_score= AFO_Score) %>% 
  mutate(goal = "access_opporunities")
# 70 obs., 4 vars.


# Save:
write_csv(AO_Scores, here::here(final_output_dir, "_goal_scores_1.0/AO_Scores_1.0_df_Sep112026.csv"))
```


# BD (biodiversity)

```{r biodiversity}
# Load original:
BD_Scores0 <- read_csv(here::here("/home/ferrer/ohi_goc_prep/BD/v2026/BD_Scores_1.0/BD_Scores_1.0_df_Sep082026.csv"))
# 63 obs., 4 vars.

colnames(BD_Scores0)

# Clean:
BD_Scores<- BD_Scores0 %>%
  select(year, OHI_region_no = OHI_region, BD_score) %>% 
  mutate(goal = "biodiversity")
# 63 obs., 4 vars.


# Save:
write_csv(BD_Scores, here::here(final_output_dir, "_goal_scores_1.0/BD_Scores_1.0_df_Sep112026.csv"))
```


# CW (clean_waters)

```{r clean_waters}
# Load original:
CW_Scores0 <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/cw/v2025/cw_current_status_arithmetic.csv"))
# 81 obs., 7 vars.

colnames(CW_Scores0)

# Clean:
CW_Scores<- CW_Scores0 %>%
  select(year, OHI_region_no= rgn_id, CW_score = CW) %>% 
  mutate(goal = "clean_waters",
         OHI_region_no = clean_names_lowercase(OHI_region_no))
# 81 obs., 4 vars.


# Save:
write_csv(CW_Scores, here::here(final_output_dir, "_goal_scores_1.0/CW_Scores_1.0_df_Sep112026.csv"))
```


# FP (food_provisioning)

```{r food_provisioning}
# Load original:
FP_Scores0 <- read_csv(here::here("/home/ferrer/ohi_goc_prep/FP/v2026/FP_Scores_1.1/FP_Scores_1.1_df_Jul282026.csv"))
# NOTE TO SELF: Including 1.1 score since these do not include CPUE.
# 63 obs., 10 vars.

colnames(FP_Scores0)

# Clean:
FP_Scores<- FP_Scores0 %>%
  select(year, OHI_region_no = OHI_region_est, FP_score) %>% 
  mutate(goal = "food_provisioning")
# 63 obs., 4 vars.


# Save:
write_csv(FP_Scores, here::here(final_output_dir, "_goal_scores_1.0/FP_Scores_1.0_df_Sep112026.csv"))
```


# HS (habitat_services)

```{r habitat_services}
# Load original:
HS_Scores0 <- read_csv(here::here("/home/ferrer/ohi_goc_prep/HS/v2026/HS_Scores_1.1/HS_current_status_Sep112026.csv"))
# 54 obs., 6 vars.

colnames(HS_Scores0)

# Clean:
HS_Scores<- HS_Scores0 %>%
  select(year, OHI_region_no = rgn_id, HS_score) %>% 
  mutate(goal = "habitat_services",
         OHI_region_no= clean_names_lowercase(OHI_region_no))
# 54 obs., 4 vars.


# Save:
write_csv(HS_Scores, here::here(final_output_dir, "_goal_scores_1.0/HS_Scores_1.0_df_Sep112026.csv"))
```


# LE (livelihoods_economies)

```{r livelihoods_economies}
LE_Scores0 <- read_csv(here::here(
    "/home/shares/ohi/OHI_GOC/goal_prep/le",
    "final_le_current_status_2019ref_informality.csv"
  ))
# 41 obs., 4 vars.

colnames(LE_Scores0)

# Clean:
LE_Scores<- LE_Scores0 %>%
  select(year = ano_censal, OHI_region_no= rgn_id, LE_score = final_le_current_status_rgn) %>% 
  mutate(goal = "livelihoods_economies",
         OHI_region_no = clean_names_lowercase(OHI_region_no))
# 41 obs., 4 vars.

# Gapfill missing years (NOTE TO SELF: this will be updated)
LE_Scores_gf <- LE_Scores %>% 
  complete(year = full_seq(2003:2025, 1), OHI_region_no) %>%  # expand to every year 2003-2025
  arrange(year, OHI_region_no) %>% 
  group_by(OHI_region_no) %>% 
  mutate(LE_score = na.approx(LE_score, x = year, na.rm = FALSE, rule = 2)) %>% 
  ungroup() %>% 
  mutate(goal = "livelihoods_economies")
# 207 obs., 4 vars.


# Save:
write_csv(LE_Scores_gf, here::here(final_output_dir, "_goal_scores_1.0/LE_Scores_1.0_df_Sep112026.csv"))
```

# NP (natural_products)

```{r natural_products}
# Load original:
NP_Scores0 <- read_csv(here::here("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores_1.0/NP_Scores_1.0_df_Sep082026.csv"))
# NOTE TO SELF: Including 1.1 score since these do not include CPUE.
# 63 obs., 10 vars.

colnames(NP_Scores0)

# Clean:
NP_Scores<- NP_Scores0 %>%
  select(year, OHI_region_no = OHI_region, NP_Score) %>% 
  mutate(goal = "natural_products")
# 63 obs., 4 vars.


# Save:
write_csv(NP_Scores, here::here(final_output_dir, "_goal_scores_1.0/NP_Scores_1.0_df_Sep112026.csv"))
```


# SP (sense_of_place)

```{r sense_of_place}
# Load original:
SP_Scores0 <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/sp_current_status_noCCE.csv"))
# 63 obs., 3 vars.

colnames(SP_Scores0)

# Clean:
SP_Scores<- SP_Scores0 %>%
  select(year, OHI_region_no= rgn_id, SP_score= current_status) %>%
  mutate(goal = "sense_of_place",
         OHI_region_no = clean_names_lowercase(OHI_region_no))
# 63 obs., 4 vars.


# Save:
write_csv(SP_Scores, here::here(final_output_dir, "_goal_scores_1.0/SP_Scores_1.0_df_Sep112026.csv"))
```


# TR (tourism_recreation) 

```{r tourism_recreation}
# Load original:
TR_Scores0 <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/tr/v2025/output/tr_current_status_final_083126.csv"))
# 63 obs., 3 vars.

colnames(TR_Scores0)

# Clean:
TR_Scores<- TR_Scores0 %>%
  rename(TR_score = tr_current_status, OHI_region_no= rgn_id) %>% 
  mutate(goal = "tourism_recreation",
         OHI_region_no = clean_names_lowercase(OHI_region_no))
# 63 obs., 4 vars.
  

# Save:
write_csv(TR_Scores, here::here(final_output_dir, "_goal_scores_1.0/TR_Scores_1.0_df_Sep112026.csv"))
```


# Join all goal dataframes:

## Long:
```{r}

Index_Scores_long0 <- bind_rows(
  AO_Scores,
  BD_Scores,
  CW_Scores,
  HS_Scores,
  FP_Scores,
  LE_Scores,
  NP_Scores,
  SP_Scores,
  TR_Scores
) %>%
  arrange(year, OHI_region_no, goal)

# Coalesce score values:
Index_Scores_long <- Index_Scores_long0 %>%
  mutate(
    goal_score = coalesce(
      AO_score,
      BD_score,
      CW_score,
      HS_score,
      FP_score,
      LE_score,
      NP_Score,
      SP_score,
      TR_score
    )
  ) %>%
  select(
    year,
    OHI_region_no,
    goal,
    goal_score
  ) %>%
  arrange(year, OHI_region_no, goal)

```

## Wide

```{r Index_Scores_wide0}
Index_Scores_wide0 <- Index_Scores_long %>%
  pivot_wider(
    id_cols = c(year, OHI_region_no),
    names_from = goal,
    values_from = goal_score
  ) %>%
  rename(
    AO_score= access_opporunities,   
    BD_score=biodiversity,
    CW_score= clean_waters,
    FP_score= food_provisioning,
    HS_score= habitat_services,
    LE_score= livelihoods_economies,
    NP_score=natural_products,
    SP_score=sense_of_place,
    TR_score=tourism_recreation
  )


Index_Scores_wide <- Index_Scores_wide0 %>%
  mutate(
    Index_score = rowMeans(
      select(., 
             AO_score,  
             BD_score,
             CW_score,
             FP_score,
             HS_score,
             LE_score,
             NP_score,
             SP_score,
             TR_score
      ),
      na.rm = TRUE
    )
  )

Index_Scores_wide_2023<- Index_Scores_wide %>%
  filter(year == 2023,
         !is.na(OHI_region_no))
```


# SAVE:

```{r Save Index_Scores_wide}
write.csv(Index_Scores_wide,
          file= "/home/ferrer/ohi_goc_prep/_index_scores_1.0/Index_Scores_1.0_df_Sep112026.csv",
          row.names = FALSE)
```


# MAP

```{r Read in OHI region boundaries}
# Read in OHI region boundaries
ohi_regions <- st_read(here("spatial", "ohi_regions", "goc_ohi_rgns.shp")) |> st_make_valid()

colnames(ohi_regions)

ohi_regions<- ohi_regions %>%
  rename(OHI_region_no= rgn_id) %>%
  mutate(
    OHI_region_no= clean_names_lowercase(OHI_region_no)
  )
```

```{r Map Index_Scores_wide_2023}

# 2. Join onto OHI polygons
Index_Scores_wide_2023 <- ohi_regions |>
  left_join(Index_Scores_wide_2023, by = "OHI_region_no")

# 3. Split marine vs land
ohi_marine <- Index_Scores_wide_2023 %>% filter(location == "marine")
ohi_land   <- Index_Scores_wide_2023 %>% filter(location == "land")

# 4. Map
tmap_mode("plot")

Index_Scores_2023_map<- tm_shape(ohi_land) +
  tm_polygons(
    col = "#f5e6c8",
    border.col = "gray40",
    lwd = 1,
    alpha = 0.5,
    legend.show = FALSE
  ) +

tm_shape(ohi_marine) +
  tm_polygons(
    col = "Index_score",
    palette = "RdYlGn",
    alpha = 0.8,
    title = "Index Scores (version 1.0)",
    border.col = "black",
    lwd = 1.2
  ) +

tm_layout(
  title = "Final Index Scores per Region (2023)",
  frame = FALSE,
  legend.outside = TRUE
)

Index_Scores_2023_map
```


# RADIAL PLOT
