---
title: "Saltmarsh Habitat data exploration"
author: "Austin Martinez"
date: 08/014/2026
format: 
  html:
    code-fold: show
execute:
  echo: true
  message: false
  warning: false
---

```{r}
# Load in Libraries
library(sf)
library(dplyr)
library(here)
library(terra)
library(tidyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tmap)
library(stringr)
```

```{r}
# Read in OHI region boundaries
ohi_regions <- st_read(here("spatial", "ohi_regions", "goc_ohi_rgns.shp")) |> st_make_valid()
```

# CANABIO Land Use and Vegitation all years

```{r}
saltmarsh_canabio_landuse_2021 <- st_read("/home/shares/ohi/OHI_GOC/_raw_data/CONABIO_Saltmarsh_landuse_veg/usv250s7gw/usv250s7gw.shp") |> st_make_valid()
```

# Hem's data
```{r}
hem_saltmarsh <- st_read("/home/shares/ohi/OHI_GOC/_raw_data/Hem_data/goc_habitat_data/wetlands/wetlands_merge.shp") |> st_make_valid()
hem_saltmarsh <- st_transform(hem_saltmarsh, st_crs(ohi_regions))
```
```{r}
tmap_mode("plot")

tm_shape(hem_saltmarsh) +
  tm_polygons(
    col = "darkgreen",
    border.col = "darkgreen",
    lwd = 0.01,
    alpha = 1
  ) +
tm_shape(ohi_regions |> filter(location == "marine")) +
  tm_borders(col = "gray", lwd = 0.2)

```

# Other wetland Hem data
```{r}

```

