################################################################################

Erica Ferrer
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
library(sf) # for work on shape fines
# Visualization
library(ggplot2)
library(colorspace)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/BD/")
```

```{r Load clean_names_lowercase function}
clean_names_lowercase <- function(x) {

  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")

  x %>%
    tolower() %>%
    trimws()
}
```


# STEP 0: Load in Region_Key
```{r Region key}
Region_Key0<- read.csv("/home/ferrer/ohi_goc_prep/FP/CONAPESCA_Keys/Spatial_Keys/RegionKey_FINAL_May262026.csv")

colnames(Region_Key0)

Region_Key<- Region_Key0 %>%
  select(OHI_region= OHI_region_est, OHI_region_name) %>%
  distinct()
```

# STEP 1: Load in NRSI_data0

```{r Load in NRSI_data0}
NRSI_data0<- read.csv("/home/shares/ohi/OHI_GOC/_raw_data/dataMares/nrsi_per_reef_year_ALL_not_filtered.csv")

NRSI_data<- NRSI_data0
```

```{r Looking for sites in Nayarit}
unique(NRSI_data$reef)
table(NRSI_data$reef)

Fully_Protected_Reefs<- NRSI_data %>%
  filter(protection== "Fully Protected")

Not_Protected_Reefs<- NRSI_data %>%
  filter(protection== "Not Protected")

# Can't seem to find the sites near Nayarit... - Aug 5 2026
# Reached out to Eduardo, now I found it - Aug 10 2026
```

# STEP 2: Add lat-long details to NRSI_data

```{r Loading in OHI regions and buffer shape files}
# OHI regions:
OHI_regions_metadata <- readLines("/home/shares/ohi/OHI_GOC/spatial/OHI_regions/marine/ohi_goc_final_071025.prj")
# CRS: EPSG:4326 in practice, poorly labeled in meta-data.

OHI_regions_shape0 <- sf::st_read(
  "/home/shares/ohi/OHI_GOC/spatial/OHI_regions/marine/ohi_goc_final_071025.shp",
  options = "ENCODING=LATIN1"
)

st_crs(OHI_regions_shape0)

OHI_regions_shape0 <- st_make_valid(OHI_regions_shape0)

# Quick plot:
OHI_Region_plot<- ggplot(OHI_regions_shape0) +
  geom_sf(aes(fill = rgn_id)) +
  theme_bw()

OHI_Region_plot

# 50km buffer:
OHI_buffer_metadata <- readLines("/home/shares/ohi/OHI_GOC/spatial/inland_50km_buffer/inland_50km_goc.prj")
# Projected CRS name: Mexico_ITRF2008_LCC

OHI_buffer_shape0 <- sf::st_read(
  "/home/shares/ohi/OHI_GOC/spatial/inland_50km_buffer/inland_50km_goc.shp",
  options = "ENCODING=LATIN1"
)

st_crs(OHI_buffer_shape0)

OHI_buffer_shape0 <- st_make_valid(OHI_buffer_shape0)

# Quick plot:
OHI_Buffer_plot<- ggplot(OHI_buffer_shape0) +
  geom_sf(aes(fill = rgn_id)) +
  theme_bw()

OHI_Buffer_plot
```

```{r Some quick cleaning}
# Let's use CRS 4326 for all projections now.
crs_use = 4326

# Change CRS on OHI_buffer_shape to match CRS on OHI_regions_shape
OHI_regions_shape <- st_transform(OHI_regions_shape0, crs_use)

# Change CRS on OHI_buffer_shape to match CRS on OHI_regions_shape
OHI_buffer_shape <- st_transform(OHI_buffer_shape0, crs_use)

# Remove columns and extract useful info:
OHI_buffer_shape<- OHI_buffer_shape0 %>%
  select(-c(estado))

additional_info<- OHI_buffer_shape0 %>%
  select(rgn_id, ecorgn) %>%
  st_drop_geometry()

# Add new columns to OHI_regions_shape
OHI_regions_shape <- OHI_regions_shape %>%
  left_join(
    additional_info,
    by = "rgn_id"
  ) %>%
  mutate(
    location= c("sea")
  ) %>%
  relocate(location, .after= rgn_id)

rm(additional_info)
```

```{r Join OHI geometric key to NRSI_data}
# Step 0 — define a Coordinate Reference System (CRS) once and stick to it:
crs_use <- 4326

# Alternative could be: CRS 5070 is the USA Contiguous Albers Equal Area (good proxy for northern Mexico too). EPSG:5070 is centered on the U.S., so Baja / Sonora are near the edge of its optimal zone.

# Step 1 — Convert master table to spatial points
# Turn NRSI_data into an sf object
colnames(NRSI_data)

master_sf <- NRSI_data %>%
  filter(!is.na(longitude), !is.na(latitude)) %>%
  st_as_sf(coords = c("longitude", "latitude"), 
           crs = crs_use,
           remove = FALSE) %>%
  st_transform(crs_use)

# Step 2 — Transform polygons ONCE
buffer_sf <- OHI_buffer_shape %>%
  st_transform(crs_use)

sea_sf <- OHI_regions_shape %>%
  st_transform(crs_use)

# Step 3 — Spatial join to land buffer polygons
# Join points → OHI_buffer_shape
master_land <- st_join(
  master_sf,
  buffer_sf,
  join = st_within,
  left = TRUE
)

# Re-name columns to be safe:
master_land <- master_land %>%
  rename(
    rgn_id_land = rgn_id,
    ecorgn_land = ecorgn,
    location_land = location
  )

# Step 5 — Spatial join to sea regions
# Join same (or filtered) points → OHI_regions_shape
master_all <- st_join(
  master_land,
  sea_sf,
  join = st_within,
  left = TRUE
)

# Step 6 — Fix duplicate column names cleanly
master_all <- master_all %>%
  rename(
    rgn_id_sea = rgn_id,
    ecorgn_sea = ecorgn,
    location_sea = location
  )
```

# NOTE TO SELF: This ^ is a pretty sloppy join. Perfect this later. - Aug 5 2026


# STEP 3: Compute ROK scores per region ------------------------------
Scores = average NSRI score by OHI region

```{r Summarize NRSI and join Region_Key}
colnames(master_all)
table(master_all$rgn_id_sea)

# Region_2 Region_3 Region_4 Region_6 Region_7 Region_9 
#       95       76     1391       18        2       53 

ROK_Status_summarized<- master_all %>%
  group_by(year, rgn_id_sea) %>%
  summarize(
    mean_NRSI = mean(nrsi_01, na.rm = TRUE),
    n_reefs = n_distinct(reef, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    OHI_region = clean_names_lowercase(rgn_id_sea)
  )
# 55 obs., 6 vars.

# Generate ROK_Scores with region details merged in:
ROK_Scores<- ROK_Status_summarized %>%
  select(OHI_region, year, mean_NRSI, n_reefs) %>%
  left_join(
    Region_Key,
    by= c("OHI_region")
  )
# 55 obs., 6 vars.

ROK_Scores <- sf::st_drop_geometry(ROK_Scores)
# 55 obs., 5 vars.

ROK_Scores<- ROK_Scores %>%
  mutate(
    ROK_score= mean_NRSI * 100
  )
# 55 obs., 6 vars.
```

# SAVE ROK_Scores ------------------------------

```{r Save FP_Scores}
write.csv(ROK_Scores, 
          "/home/ferrer/ohi_goc_prep/BD/BD_Scores/ROK_Scores/ROK_Scores_1.0_df_Aug102026.csv", 
          row.names = FALSE)
# 55 obs., 6 vars.
```

# PLOT ROK_Scores  ------------------------------

```{r Plot ROK_Scores over time}
colnames(ROK_Scores)

# Plot 1, panel per region:

Region_colors<- c(
  "Western Upper Gulf" = "#C03729",
  "Western Midriff Islands" = "#E68C7C",
  "Western Central Gulf" = "#FC8F24",
  "Western Southern Gulf" = "#dcaa38",
  "Eastern Upper Gulf" = "#cbd2a0",
  "Eastern Midriff Islands" = "#98a25a",
  "Southern Sonora Coast" = "#747428",
  "Sinaloa Coast" = "#627391",
  "Southeastern Gulf" = "#8d61a9")

ROK_Scores_OverTime<- ROK_Scores %>%
  filter(!is.na(OHI_region)) %>%
  
  ggplot(
    aes(
      x = year,
      y = mean_NRSI,
      color = OHI_region_name
    )
  ) +
  geom_line() +
  
  facet_wrap(~ OHI_region) +

  labs(
    title = "Status of Rocky Reefs per Region",
    subtitle= "updated: Aug 5 2026",
    y = "Normalized Reef Status Inidicator (0 to 1)",
    x = "Year"
  ) +
  
  scale_color_manual(values = Region_colors) +
  
  theme_bw(base_size = 14) +
  theme(
    strip.text = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

ROK_Scores_OverTime
```

```{r Save plot as PNGs}
ggsave(
  plot = ROK_Scores_OverTime,
  filename = sprintf("/home/ferrer/ohi_goc_prep/BD/BD_Scores/ROK_Scores/ROK_Scores_1.0_plot_Aug052026.png"),
  width = 12,
  height = 12,
  dpi = 300
)
```