```{r Libraries}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(plotly)
library(htmlwidgets)
```

```{r Mexico FAO Data}
## FAO data, some of the zeros were originally reported as NA (so exercise caution there)
harvest <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2025/refs/heads/main/globalprep/mar/v2025/output/mar_harvest_tonnes.csv")
mex_harvest <- filter(harvest, rgn_id == 135)
mex_harvest <- filter(mex_harvest, year == 2017) %>% data.frame()

# data from Seafood Watch (Monterey Bay)
sustainability <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2025/refs/heads/main/globalprep/mar/v2025/output/mar_sustainability.csv")
mex_sust <- filter(sustainability, taxa_code %in% mex_harvest$taxa_code) %>%
 filter(year==2025) %>% data.frame()

# determine whether sustainability was gapfilled (if so, fairly low confidence, depending on method used and taxa)
gf <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2025/refs/heads/main/globalprep/mar/v2025/output/mar_sustainability_gf.csv")
mex_gf <- filter(gf, taxa_code %in% mex_harvest$taxa_code) %>% data.frame()
```

```{r CONAPESCA data 2001 thru 2019}
CONAPESCA_data<- read_csv(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByDataMares/", "CONAPESCA Data_NW.Mexico_20012019.csv"))
# 537385 obs.

# Make new date columns
CONAPESCA_data$Date_parsed <- parse_date_time(CONAPESCA_data$Date, 
                                  orders = c("dmy", "dmY", "d/m/y", "d/m/Y"))

CONAPESCA_data$Day <- day(CONAPESCA_data$Date_parsed)
CONAPESCA_data$Month <- month(CONAPESCA_data$Date_parsed)
CONAPESCA_data$Year <- year(CONAPESCA_data$Date_parsed)
```

```{r Preliminary exploration}
table(CONAPESCA_data$State)
# BAJA CALIFORNIA BAJA CALIFORNIA SUR              SONORA 
#           112183              286198              139004 
# Notably, does not include data from Sinaloa.

table(CONAPESCA_data$Tipo.de.pesca)
# ARTESANAL INDUSTRIAL 
# 496959     39716 
# Mostly artisanal entries...

CONAPESCA_data_reshape <- CONAPESCA_data %>%
  group_by(Year, Tipo.de.pesca, General.Name) %>%
  summarise(Mass_Kg = sum(Mass_Kg))

CONAPESCA_plot1 <- CONAPESCA_data_reshape %>%
  filter(Year == 2019, Tipo.de.pesca != "NA") %>%
  mutate(General.Name = reorder_within(General.Name, log10(Mass_Kg), Tipo.de.pesca)) %>%
  ggplot(aes(x = General.Name, y = log10(Mass_Kg), fill = Tipo.de.pesca)) +
  geom_bar(stat = "identity") +
  scale_x_reordered() +
  labs(
    title = "Catch by Fishery Type and Species (2019)",
    x = "Taxa",
    y = "Catch (kg) log10-scale",
    fill = "Fishery Type"  # rename the legend
  ) +
  coord_flip() +
  theme_bw(base_family = "Helvetica") +  # change base font
  theme(
    plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),  # center + bold + larger
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 13),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  ) +
  geom_hline(yintercept = log10(1e6), color = "tomato", linetype = "dashed") + #a line at the 1000 metric tonne mark (10e5 kg)
  scale_fill_manual(values = c("lightblue1", "navy")) # supply a vector of colors matching your fishery types

  # # Draw a transparent rectangle box around top 10 bars
  # annotate("rect",
  #          xmin = 37, xmax = 53,  # careful: x and y are flipped, so switch axes here
  #          ymin = log10(1), ymax = log10(1e9),
  #          fill = NA,
  #          color = "darkgrey",
  #          size = 1)

CONAPESCA_plot1

CONAPESCA_interactive_plot1 <- ggplotly(CONAPESCA_plot1)
CONAPESCA_interactive_plot1
```

```{r Save plot}
ggsave(
  filename = "CONAPESCA_plot1_Sep 15 2025.png",  # file name
  plot = CONAPESCA_plot1,            # the plot object
  width = 10,                        # width in inches
  height = 10,                        # height in inches
  dpi = 300                         # resolution (dots per inch)
)

# Save your plotly object as HTML
htmlwidgets::saveWidget(CONAPESCA_interactive_plot1, "CONAPESCA_plot1.html")
```


