---
title: "Look into GoC Mariculture"
output: html_notebook
---

# Load MAR dataframe (data as of Dec 09 2025)
```{r Load MAR dataframe}
# Load file, only if needed:
GoC_Landings_for_CMSY<- readRDS(here("/home/shares/ohi/OHI_GOC/goal_prep/fp/mar/v2025/int/GOC_MAR.landings_CLEAN_as.of.Dec092025.rds"))
```

```{r Top Mariculture Sp.}
table(Landings_GoC_Mariculture$common_name_clean)

Landings_GoC_Mariculture_Summary<- Landings_GoC_Mariculture %>% 
  filter(year >= 2014, year <= 2024) %>%
  select(state, recorded_taxa_group, recorded_taxa_name_clean, weight_kg_corrected, value) %>%
  group_by(state, recorded_taxa_group, recorded_taxa_name_clean) %>%
  summarize(total_catch_2014.2024= sum(weight_kg_corrected, na.rm = TRUE),
            total_value_2014.2024= sum(value, na.rm = TRUE))

unique(Landings_GoC_Mariculture_Summary$recorded_taxa_name_clean)

GoC_Top_MaricultureSp <- Landings_GoC_Mariculture_Summary %>%
  filter(total_catch_2014.2024 >= 10000) %>%
  pull(recorded_taxa_name_clean) %>%
  unique()

GoC_Top_MaricultureSp # NOTE TO SELF: 29 top species and some of them are fairly general or could be freshwater...

Landings_GoC_TopMariculture_Summary<- Landings_GoC_Mariculture %>% 
  filter(year >= 2014, year <= 2024) %>%
  filter(recorded_taxa_name_clean %in% GoC_Top_MaricultureSp) %>%
  select(recorded_taxa_group, recorded_taxa_name_clean, weight_kg_corrected, value) %>%
  group_by(recorded_taxa_group, recorded_taxa_name_clean) %>%
  summarize(total_catch_2014.2024= sum(weight_kg_corrected, na.rm = TRUE),
            total_value_2014.2024= sum(value, na.rm = TRUE))
```

```{r Save Landings_GoC_TopMariculture_Summary to find MAR sustainability scores}
# write.csv(Landings_GoC_TopMariculture_Summary, "/home/ferrer/ohi_goc_prep/FP/MAR/v2025/GOC_Mariculture_TopCatches_2014.2024_Dec082025.csv", row.names = FALSE)
```

# SUMMARY STATS ABOUT OUR DATA: return to this later.
```{r How much of biomass includes information about species, genus, family?}
Landings_GoC %>%
  pull(estimated_species_name) %>%
  {c(n_na = sum(is.na(.)),
      n_unknown = sum(. == "unknown", na.rm = TRUE),
      n_NEI = sum(. == "NEI", na.rm = TRUE)
    ) }
# 1008085 (1839 + 205110 + 765582) out of 3559463 records (27%) for species are NA, "unknown", or "NEI"
# Meaning we have species info for 73% of records.

Landings_GoC %>%
  pull(estimated_genus_name) %>%
  {c(n_na = sum(is.na(.)),
     n_unknown = sum(. == "unknown", na.rm = TRUE),
     n_NEI = sum(. == "NEI", na.rm = TRUE)
    ) }
# 1008085 (206949 + 0 + 765582) out of 3559463 records (27%) for genus are NA, "unknown", or "NEI"
# Meaning we have genus info for 73% of records.

Landings_GoC %>%
  pull(estimated_family_name) %>%
  {c(n_na = sum(is.na(.)),
     n_unknown = sum(. == "unknown", na.rm = TRUE),
     n_NEI = sum(. == "NEI", na.rm = TRUE),
     n_family_info_pending = sum(. == "family missing but genus available", na.rm = TRUE)
    ) }
# 336348 (185825 + 0 + 150523) out of 3559463 records (9%) for family are NA, "unknown", or "NEI". 29438 (~1%) records have information about genus but family info pending.
# Meaning we already have or can get family info for 91% of records.
```