---
title: 'OHI GoC 2025: Species Present in the Gulf of California'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: inline
editor_options: 
  chunk_output_type: console
---

# Summary

The species that inhabit the ocean have a vital role in shaping the existing marine environment. They are valued for their beauty and inherent right to exist, as well as their role in supporting productive habitats that provide many benefits for people.

From the largest predators to microscopic plankton, these species depend upon each other for survival. The interaction of species that have naturally evolved in a given location is essential for ecosystem structure and stability. In addition, the maintenance of large numbers of species provides diverse genetic resource that makes it possible to avoid functional collapse, should conditions change in the future.

This sub-goal assesses the health of all marine species present in the Gulf of California, including endangered species and species in relatively good conditions. The presence of species that are not at risk leads to a higher score.

## Exploring data sources

### The Gulf of California Invertebrate Database:The Invertebrate Portion of the Macrofauna Golfo Database

Link to downloard: <https://www.desertmuseum.org/center/seaofcortez/database.php>

Downloaded: April 29, 2025

Directions to download: Select Shallowest depth *equals 0 meters*; Greatest depth *is less than or equal to 15,000 meters* [artifical and arbitrary max, knowing that the deepest parts of the GoC are 10,000 meters]. Then download CSV file.  For v2025, there were 2340 results found.

Acronyms used in the database: <https://www.desertmuseum.org/center/seaofcortez/acronyms.php>

Data stored: home/shares/ohi/OHI_GOC/_raw_data/GoC_invert_database_desertmuseum/d2025/seaofcortez_export_0_15000meters.csv

# Setup


