---
title: "OHI Scores Habitat Services - Gulf of California OHI"
author: "Austin Martinez"
date: 6/30/2026
format: 
  html:
    code-fold: show
execute:
  echo: true
  message: false
  warning: false
---

```{r}
# Load in Libraries
library(sf)
library(dplyr)
library(here)
library(terra)
library(tidyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tmap)
library(stringr)
library(readr)
```

## Read in all habitat data
```{r}
# Read in habitat services data
habitat_services <- read_csv(here::here("BD", "HAB", "hab_OHI_scores", "habitat_services_output_pushed", "habitat_services_full.csv"))
```

```{r}
habitat_scores <- habitat_services |>
  group_by(rgn_id) |>
  summarise(
    carbon_score = sum(extent * `carbon_sequestration_(g C m⁻² yr⁻¹)` * condition, na.rm = TRUE) /
                    sum(extent * `carbon_sequestration_(g C m⁻² yr⁻¹)`, na.rm = TRUE) * 100,

    filtration_score = sum(extent * filtration * condition, na.rm = TRUE) /
                       sum(extent * filtration, na.rm = TRUE) * 100,

    coastal_score = sum(extent * coastal_protection * condition, na.rm = TRUE) /
                    sum(extent * coastal_protection, na.rm = TRUE) * 100
  )
habitat_scores
```

```{r}
habitat_scores |>
  mutate(
    rgn_id = gsub("Region_", "Region ", rgn_id),        # remove "Region_" prefix
    carbon_score = round(carbon_score, 0),
    filtration_score = round(filtration_score, 0),
    coastal_score = round(coastal_score, 0),
    habitat_services_score = round(habitat_services_score, 0)
  ) |>
  kable(
    col.names = c(
      "Region",
      "Carbon Score",
      "Filtration Score",
      "Coastal Score",
      "Habitat Services Score"
    )
  ) |>
  kable_styling(
    bootstrap_options = c("striped", "bordered"),
    full_width = FALSE
  ) |>
  add_header_above(c("OHI Scores – Condition" = 5))

```


### Calculating the final habitat services scores for each service
```{r}
library(dplyr)

habitat_scores_trend <- habitat_services |>
  group_by(rgn_id) |>
  summarise(
    carbon_score = sum(extent * `carbon_sequestration_(g C m⁻² yr⁻¹)` * trend, na.rm = TRUE) /
                    sum(extent * `carbon_sequestration_(g C m⁻² yr⁻¹)`, na.rm = TRUE),

    filtration_score = sum(extent * filtration * trend, na.rm = TRUE) /
                       sum(extent * filtration, na.rm = TRUE),

    coastal_score = sum(extent * coastal_protection * trend, na.rm = TRUE) /
                    sum(extent * coastal_protection, na.rm = TRUE)
  )
habitat_scores_trend
```

```{r}
habitat_scores_final_trend <- habitat_scores_trend |>
  mutate(habitat_services_score = (carbon_score + filtration_score + coastal_score) / 3)
habitat_scores_final_trend
```
```{r}
habitat_scores_trend <- habitat_scores_trend |>
  mutate(habitat_services_score = rowMeans(
    cbind(carbon_score, filtration_score, coastal_score),
    na.rm = TRUE
  ))

habitat_scores_trend |>
  kable(
    col.names = c(
      "Region",
      "Carbon Trend",
      "Filtration Trend",
      "Coastal Trend",
      "Habitat Services Trend"
    )
  ) |>
  kable_styling(
    bootstrap_options = c("striped", "bordered"),
    full_width = FALSE
  ) |>
  add_header_above(c("OHI Scores – Trend" = 5))

```

We are missing scores for regions 1 and 3 because we have no 
```{r}
habitat_services |>
  filter(rgn_id %in% c("Region_3", "Region_1"))
```

```{r}
habitat_services |> filter(rgn_id == "Region_1")
```
