---
title: "OHI Habitat servics data prep - Gulf of California OHI"
author: "Austin Martinez"
date: 6/30/2026
format: 
  html:
    code-fold: show
execute:
  echo: true
  message: false
  warning: false
---

```{r}
# Load in Libraries
library(sf)
library(readr)
library(dplyr)
library(here)
library(terra)
library(tidyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tmap)
library(stringr)
```

## Read in trend, condition, and extent output files
```{r}
# Mangroves
mangrove_condition <- read_csv(here::here("BD", "HAB", "hab_mangroves", "v2025", "austin_mangroves", "habitat_services_output", "mangrove_condition.csv"))
mangrove_extent <- read_csv(here::here("BD", "HAB", "hab_mangroves", "v2025", "austin_mangroves", "habitat_services_output", "mangrove_extent.csv"))
mangrove_trend <- read_csv(here::here("BD", "HAB", "hab_mangroves", "v2025", "austin_mangroves", "habitat_services_output", "mangrove_trend.csv"))

# Saltmarsh
saltmarsh_condition <- read_csv(here::here("BD", "HAB", "hab_wetlands", "v2025", "habitat_services_output", "saltmarsh_condition.csv"))
saltmarsh_extent <- read_csv(here::here("BD", "HAB", "hab_wetlands", "v2025", "habitat_services_output", "saltmarsh_extent.csv"))
saltmarsh_trend <- read_csv(here::here("BD", "HAB", "hab_wetlands", "v2025", "habitat_services_output", "saltmarsh_trend.csv"))

# Coastal Dunes
coastal_dune_condition <- read_csv(here::here("BD", "HAB", "hab_coastal_dunes", "habitat_services_output", "coastal_dune_condition.csv"))
coastal_dune_extent <- read_csv(here::here("BD", "HAB", "hab_coastal_dunes", "habitat_services_output", "coastal_dune_extent.csv"))
coastal_dune_trend <- read_csv(here::here("BD", "HAB", "hab_coastal_dunes", "habitat_services_output", "coastal_dune_trend.csv"))

# Seagrass
seagrass_habitat_scores <- read_csv(here::here("BD", "HAB", "hab_seagrass", "v2025", "habitat_services_output", "seagrass_habitat_scores.csv"))
```

```{r}
# Join mangrove trend, condition, and extent CSVs
mangrove <- mangrove_condition |>
  left_join(mangrove_extent, by = c("rgn_id")) |>
  left_join(mangrove_trend,  by = c("rgn_id")) |>
  mutate(habitat = "mangrove") |>
  rename(extent = area_km2) |>
  select(-year.x, -year.y) |>
  select(rgn_id, year, condition, extent, trend, habitat)
```

We have a NA for rgn 7 because we only got data for years 2016 and 2021
```{r}
# Join saltmarsh trend, condition, and extent CSVs
saltmarsh <- saltmarsh_condition |>
  left_join(saltmarsh_extent, by = c("rgn_id", "year")) |>
  left_join(saltmarsh_trend,  by = c("rgn_id", "year")) |>
  mutate(habitat = "saltmarsh") |>
  rename(extent = area_km2)
```


```{r}
# Join coastal_dune trend, condition, and extent CSVs
coastal_dune <- coastal_dune_condition |>
  left_join(coastal_dune_extent, by = c("rgn_id", "year")) |>
  left_join(coastal_dune_trend,  by = c("rgn_id", "year")) |>
  mutate(habitat = "coastal_dune") |>
  rename(extent = area_km2)
```

```{r}
# Concatinate dataframes
habitat_full <- bind_rows(mangrove, saltmarsh, coastal_dune, seagrass_habitat_scores)
```


## Read in habitat service lit review scores for filtration, carbon sequestoration, and coastal protection
```{r}
service_weights <- read_csv("/home/shares/ohi/OHI_GOC/_raw_data/habitat_services.csv")
```

```{r}
service_weights <- service_weights |>
  rename(habitat = habitat_type) |>
  mutate(habitat = ifelse(habitat == "mangroves", "mangrove", habitat))

service_weights_sub <- service_weights |>
  select(habitat, coastal_protection, `carbon_sequestration_(g C m⁻² yr⁻¹)`, filtration)
```

```{r}
habitat_services_full <- habitat_full |>
  left_join(service_weights_sub,
            by = c("habitat" = "habitat"))
```


```{r}
# Write CSVs to output_data directory
write.csv(habitat_services_full,
          "habitat_services_output/habitat_services_full.csv",
          row.names = FALSE)
```
