---
title: 'OHI GoC 2025: Livelihoods & Economies'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# Merge LE: LIV + ECO

For number of jobs, quality of jobs, and revenue of certain sectors.  

## Read in all current status of components

### LIV: number of jobs

```{r}
ce_jobs_current_status <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/liv","ce_jobs_current_status.csv")) %>% 
  dplyr::select(-c(marine_jobs_per_local_pop, avg_value_2004_2014)) %>% 
  rename(job_current_status_raw = current_status_raw, 
         job_current_status = current_status,
         ano_censal = ce_ano_censal)
```

### LIV: quality of jobs

```{r}
ce_qual_current_status <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/liv","ce_qual_current_status.csv")) %>% 
  dplyr::select(rgn_id, ano_censal, qual_current_status_raw = current_status_raw, qual_current_status = current_status) 
```


### ECO

```{r}
ce_rev_current_status <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco","ce_rev_current_status.csv")) %>% 
  dplyr::select(rgn_id, ano_censal, rev_current_status_raw = current_status_raw, rev_current_status = current_status) 
```



## Merge LIV

Note: should we use the capped or un-capped current status to average LIV?

```{r}
liv_merge <- full_join(ce_jobs_current_status, ce_qual_current_status) %>% 
  mutate(liv_current_status_raw = ((job_current_status_raw + qual_current_status_raw) / 2),
         liv_current_status = ((job_current_status + qual_current_status) / 2)) %>% 
  mutate(liv_current_status_raw = ifelse(rgn_id == "Region_2", qual_current_status_raw, liv_current_status_raw), # for region_2 only use job quality becasue the reference point is not strictly temporal within region
         liv_current_status = ifelse(rgn_id == "Region_2", qual_current_status, liv_current_status)) %>% 
  dplyr::select(rgn_id, ano_censal, liv_current_status_raw, liv_current_status)
```


## Merge LIV and ECO

```{r}
le_current_status <- full_join(ce_rev_current_status, liv_merge) %>% 
  mutate(le_current_status_raw = ((liv_current_status_raw + rev_current_status_raw) / 2),
         le_current_status = ((liv_current_status + rev_current_status) / 2)) %>% 
  mutate(le_current_status_raw = ifelse(rgn_id == "Region_2", liv_current_status_raw, le_current_status_raw), # for region_2 only use job quality becasue the reference point is not strictly temporal within region
         le_current_status = ifelse(rgn_id == "Region_2", liv_current_status, le_current_status)) %>% 
  mutate(le_current_status_raw_recapped = ifelse(le_current_status_raw >= 100, 100, le_current_status_raw)) %>% 
  dplyr::select(rgn_id, ano_censal, le_current_status_raw, le_current_status_raw_recapped, le_current_status)
```

# Plot

## le_current_status_raw

```{r}
library(plotly)
library(dplyr)

le_current_status <- le_current_status %>%
  mutate(ano_censal = as.numeric(ano_censal))

le_raw_plotly <- plot_ly(
  le_current_status,
  x = ~ano_censal,
  y = ~le_current_status_raw,
  color = ~factor(rgn_id),
  colors = rgn_colors,
  type = "scatter",
  mode = "lines+markers"
) %>%
  layout(
    title = "RAW CURRENT STATUS of LE (LIV & ECO merged) per region",
    xaxis = list(title = "Census Year"),
    yaxis = list(
      title = "LE raw score (0 - 100 scale)"
    ),
    legend = list(title = list(text = "GoC Region"))
  ) %>%
  add_lines(
    x = range(le_current_status$ano_censal), 
    y = c(100, 100),
    line = list(color = "black", width = 2, dash = "dash"),
    name = "Meta // Goal (100/100)",
    inherit = FALSE
  )

le_raw_plotly



```

## le_current_status_raw_recapped

```{r}
library(plotly)
library(dplyr)

ce_qual_current_status <- ce_qual_current_status %>%
  mutate(ano_censal = as.numeric(ano_censal))

le_raw_recapped_plotly <- plot_ly(
  le_current_status,
  x = ~ano_censal,
  y = ~le_current_status_raw_recapped,
  color = ~factor(rgn_id),
  colors = rgn_colors,
  type = "scatter",
  mode = "lines+markers"
) %>%
  layout(
    title = "RAW CURRENT STATUS of LE (LIV & ECO merged), recapped at 100",
    xaxis = list(title = "Census Year"),
    yaxis = list(
      title = "LE raw score (0–100, capped at 100)",
      range = c(0, 110)
    ),
    legend = list(title = list(text = "Region"))
  ) %>%
  add_lines(
    x = range(le_current_status$ano_censal),
    y = c(100, 100),
    line = list(color = "black", width = 2, dash = "dash"),
    name = "Meta // Goal (100/100)",
    inherit = FALSE
  )

le_raw_recapped_plotly



```

## le_current_status

```{r}
library(plotly)
library(dplyr)

ce_qual_current_status <- ce_qual_current_status %>%
  mutate(ano_censal = as.numeric(ano_censal))

le_cs_plotly <- plot_ly(
  le_current_status,
  x = ~ano_censal,
  y = ~le_current_status,
  color = ~factor(rgn_id),
  colors = rgn_colors,
  type = "scatter",
  mode = "lines+markers"
) %>%
  layout(
    title = "CURRENT STATUS of LE (LIV & ECO merged) per region",
    xaxis = list(title = "Census Year"),
    yaxis = list(
      title = "LE current status (0–100)",
      range = c(0, 110)
    ),
    legend = list(title = list(text = "Region"))
  ) %>%
  add_lines(
    x = range(le_current_status$ano_censal),
    y = c(100, 100),
    line = list(color = "black", width = 2, dash = "dash"),
    name = "Meta // Goal (100/100)",
    inherit = FALSE
  )

le_cs_plotly



```
