Miscellaneous Statistics for FP Report

################################################################################ 

For questions contact: Erica Ferrer, Ph.D. at emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################ 

# PRE-WORK ------------------------------

```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
library(sf) # shape files
# Visualization
library(ggplot2)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/FP/")
```

## clean_names_lowercase function
```{r Load clean_names_lowercase function}
# Takes text and standardizes it, which we will need for merging later on:

clean_names_lowercase <- function(x) {

  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")

  x %>%
    tolower() %>%
    trimws()
}
```

```{r Load in GOC_Landings}
GOC_Landings<- readRDS("/home/shares/ohi/OHI_GOC/goal_prep/fp/cleaned_CONAPESCA/GOC_Landings_SectorSorted.Georef_PATCHED_Jun032026.rds")
# 3490044 obs.
```

```{r How many genera accounted for?}
colnames(GOC_Landings)
table(GOC_Landings$GOC_Include_Exclude)
# 3490044 obs.

# How many genera in the database?
MarineFishery_Sectors<- c("marine: fishery sector yet to be classified",
                          "marine: small-scale capture",
                          "marine: large-scale capture")
  
PossibleMarineFishery_Sectors<- c("freshwater or marine: large-scale capture",
                          "freshwater or marine: small-scale capture",
                          "freshwater or marine: fishery sector yet to be classified")

GOC_MarineFisheryLandings0<- GOC_Landings %>%
  filter(sector_estimate_draft %in% c(MarineFishery_Sectors, PossibleMarineFishery_Sectors)) %>%
  mutate(
    estimated_genus_name= clean_names_lowercase(estimated_genus_name)
  )

unique(GOC_MarineFisheryLandings0$estimated_genus_name)

# Compared to:
Stock_Statuses0<- read.csv("/home/ferrer/ohi_goc_prep/FP/FP_Scores/FIS_Scores/FIS_Stock_Status_SubScores/Stock_Statuses_Compiled_df_Jun072026.csv")

colnames(Stock_Statuses0)

Stock_Statuses<- Stock_Statuses0 %>%
  filter(!is.na(StockStatus_final))

Stocks_Accounted_For<- unique(Stock_Statuses$estimated_genus_name)
# 85 genera
```

```{r}
# I want to calculate Marine Catch in 2024 overall versus for the Stocks_Accounted_For

MarineCatch_2024 <- GOC_MarineFisheryLandings0 %>%
  filter(year == 2024) %>%
  summarize(
    total_mass_mt = sum(weight_kg_corrected, na.rm = TRUE) / 1000,
    accounted_mass_mt = sum(
      weight_kg_corrected[estimated_genus_name %in% Stocks_Accounted_For],
      na.rm = TRUE
    ) / 1000,
    pct_accounted = 100 * accounted_mass_mt / total_mass_mt
  )
```

