---
title: "Coral Reef Habitat Condition and Trend - Gulf of California OHI"
author: "Austin Martinez"
date: 5/7/2026
format: 
  html:
    code-fold: show
execute:
  echo: true
  message: false
  warning: false
---

```{r}
# Load in Libraries
library(sf)
library(dplyr)
library(here)
library(terra)
library(tidyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tmap)
library(stringr)
```

```{r}
# Read in OHI region boundaries
ohi_regions <- st_read(here("spatial", "ohi_regions", "goc_ohi_rgns.shp")) |> st_make_valid()

# Read in Allen polygon data
atlas_coral <- st_read("/home/shares/ohi/OHI_GOC/_raw_data/ALLEN_coral_Atlas/Mexican-Exclusive-Economic-Zone-20230309211010/Reef-Extent/reefextent.gpkg") |> st_make_valid()

# Read in Hem point data
hem_coral <- st_read("/home/shares/ohi/OHI_GOC/_raw_data/Hem_data/goc_habitat_data/coral/Arrecifes_de_coral_(Golfo_de_California).shp") |> st_make_valid()
```

```{r}
# Make all 3 data sets the same CRS
ohi_regions <- st_transform(ohi_regions, st_crs(atlas_coral))
hem_coral <- st_transform(hem_coral, st_crs(atlas_coral))

```

```{r}
atlas_coral <- st_intersection(atlas_coral, ohi_regions)
hem_coral   <- st_intersection(hem_coral, ohi_regions)
```

```{r}
library(tmap)

tmap_mode("view")

tm_shape(ohi_regions) +
  tm_polygons(col = "gray70", alpha = 0.1, border.col = NA) +

tm_shape(atlas_coral) +
  tm_polygons(col = "red", alpha = 1, border.col = "red") +

tm_shape(hem_coral) +
  tm_dots(col = "blue", size = 0.03) +
  
tm_layout(title = "OHI Regions with Allen Coral Polygons and Hem Coral Points")


```


```{r}
# Identify Hem points that intersect Atlas polygons
corals_that_intersect <- st_intersects(hem_coral, atlas_coral)

# Keep only Hem points that do NOT intersect Atlas polygons
hem_coral_int <- hem_coral[lengths(corals_that_intersect) == 0,]
```

```{r}
# Convert from m^2 to hectares
altas_coral_area_m2 <- sum(st_area(atlas_coral))
altas_coral_area_ha <- as.numeric(altas_coral_area_m2) / 10000
altas_coral_area_ha
```

```{r}
# Total area of corals in GOC according to Datamares: https://datamares.org/stories/marine-habitat-distributions-in-the-gulf-of-california-2/
Total_coral_area_ha <- 657

# Subtract total coral area by altas_coral_area_ha to 
remaining_coral_area_ha <- Total_coral_area_ha - altas_coral_area_ha
remaining_coral_area_ha
```

```{r}
non_int_coral_points <- as.numeric(nrow(hem_coral_int))
non_int_coral_points
```


```{r}
area_per_point_ha = remaining_coral_area_ha / non_int_coral_points
area_per_point_ha
```

```{r}
# Rename atlas_coral$geom → geometry
atlas_coral <- atlas_coral |>
  rename(geometry = geom)

# Drop the unwanted columns to concat hem_coral_int and atlas_coral
atlas_coral <- atlas_coral |>
  select(-class)

hem_coral_int <- hem_coral_int |>
  select(-Habitat)

# Add an area_ha column For polygons (atlas_coral) and For points (hem_coral_int)
atlas_coral <- atlas_coral |>
  mutate(area_ha = as.numeric(st_area(geometry)) / 10000)

hem_coral_int <- hem_coral_int |>
  mutate(area_ha = area_per_point_ha)

# Bind the two datasets together
coral_combined <- bind_rows(atlas_coral, hem_coral_int)
```

```{r}
# Check if it worked by suming all areas to see if we get 657 ha
sum(coral_combined$area_ha)
```

## Find the coral area in each region

```{r}
coral_by_region <- st_intersection(coral_combined, ohi_regions)

coral_region_area <- coral_combined |>
  st_drop_geometry() |>
  dplyr::group_by(rgn_id) |>
  dplyr::summarise(
    area_ha = sum(area_ha, na.rm = TRUE),
    year = 2025
  )

```

```{r}
coral_region_area |>
  arrange(rgn_id) |>
  kable(
    digits = 4,
    col.names = c("Region ID", "Area (ha)", "Year"),
    align = c("c", "r", "c")
  ) |>
  kable_styling(
    bootstrap_options = c("striped", "bordered", "hover"),
    full_width = FALSE
  ) |>
  add_header_above(
    c("Coral Habitat Area by OHI Region (2020)" = 3)
  )

```

