---
title: 'OHI GoC 2025: SP ICO Gulf of California'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# Summary

The Iconic Species (ICO) subgoal of Sense of Place captures the condition of iconic species that are relevant to local cultural identity.  We must (1) create a list of iconic species and which OHI regions they belong to, (2) determine their condition by their risk status, such as from NOM-059-SEMARNAT-2010, or IUCN, and (3) then, for each region, the average of the status for all iconic species can be calculated.

(1) = script1_iconic_species_list.qmd
(2) = script2_norma059.qmd, script3_cites_prep.qmd, script4_iucn_prep.qmd
(3) = script5_ico_current_status.qmd

In this third script, we will be cleaning up CITES information and assessing iconic species condition based on the Appendix the species is listed under.

Note that if none of the iconic species are listed on NOM-059-SEMARNAT-2010, we will check to see if they are listed as *at risk* by CITES/IUCN.  If not, the subgoal would have a current status of 100 for that region and year.

