
# PENDING STEP 17: Generate ARTISNAL List  ------------------------------
```{r Load GOC_Landings_marine if needed}
GOC_Landings_marine<- readRDS(here("/home/shares/ohi/OHI_GOC/goal_prep/fp/cleaned_CONAPESCA/GOC_Landings_MARINE_2000.present_EMF.Apr032026.rds"))
# 3312602 obs., 62 vars.
```

```{r FILTER OUT SSF SECTORS OF INTEREST:}
table(GOC_Landings_marine$sector_estimate_draft)

# FILTER OUT SSF SECTORS OF INTEREST: ----
# Let's assume that the records are most accurate since 2018.

SSF_Sectors<- c("marine: small-scale capture")

GOC_Landings_SSF<- GOC_Landings_marine %>% 
  filter(year>2017) %>%
  filter(sector_estimate_draft %in% SSF_Sectors)
# 950167 obs., 62 vars.

range(GOC_Landings_SSF$year)
```

```{r Generate a table / list of common n > 10 records SSF since 2018}
SSFGenera_summary <- GOC_Landings_SSF %>%
  filter(year > 2017) %>%
  filter(!is.na(estimated_genus_name) & estimated_genus_name != "NEI" & estimated_genus_name != "unknown") %>%
  select(estimated_genus_name, Major_Functional_Group) %>%
  group_by(Major_Functional_Group, estimated_genus_name) %>%
  summarise(
    n_records_since2018 = n(),
    .groups = "drop"
  )

SSFGenera_summary<- SSFGenera_summary %>%
  filter(n_records_since2018 > 10)
```