################################################################################

Erica Ferrer
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
# Visualization
library(ggplot2)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/FP/")
```

# Load in MAR dataframe (data as of Dec 09 2025)
```{r Load MAR dataframe}
# Load file, only if needed:
Mariculture_Landings<- readRDS(here("/home/shares/ohi/OHI_GOC/goal_prep/fp/mar/v2025/int/GOC_MAR.landings_CLEAN_as.of.Feb242026.rds"))
# 130432 obs., 50 vars.
```

```{r Investigate the mariculture flags}
table(Mariculture_Landings$common_name_clean)
table(Mariculture_Landings$aquaculture_flag)
table(Mariculture_Landings$acuaculture_production)
table(Mariculture_Landings$fleet) # lots of NAs

subset<- Mariculture_Landings %>% filter(acuaculture_production== c("NO", "no"))
# 7822 obs.

unique(subset$common_name_clean)
# NOTE TO SELF: Many types of ostion flagged in this subset as "NOT" aquaculture production, which is at odds with what we've been told...

subset<- Mariculture_Landings %>% filter(common_name_clean== c("tiburon", "tiburon azul", "tiburon tunero", "tiburon sedoso")) 
# NOTE TO SELF: Also weird, several shark entries flagged as aquaculture, even though we know this all but impossible.
```

```{r Top Mariculture Sp.}
table(Mariculture_Landings$common_name_clean)
table(Mariculture_Landings$aquaculture_flag)

Mariculture_Landings_Summary<- Mariculture_Landings %>% 
  filter(year >= 2014, year <= 2024) %>%
  select(state, recorded_taxa_group, recorded_taxa_name_clean, weight_kg_corrected, value) %>%
  group_by(state, recorded_taxa_group, recorded_taxa_name_clean) %>%
  summarize(total_catch_2014.2024= sum(weight_kg_corrected, na.rm = TRUE),
            total_value_2014.2024= sum(value, na.rm = TRUE))

unique(Mariculture_Landings_Summary$recorded_taxa_name_clean)

Top_MaricultureSp <- Mariculture_Landings_Summary %>%
  filter(total_catch_2014.2024 >= 10000) %>%
  pull(recorded_taxa_name_clean) %>%
  unique()

Top_MaricultureSp # NOTE TO SELF: 33 top species. Some of them are fairly general or could be freshwater.

Top_MaricultureSp_Summary<- Mariculture_Landings %>% 
  filter(year >= 2014, year <= 2024) %>%
  filter(recorded_taxa_name_clean %in% Top_MaricultureSp) %>%
  select(recorded_taxa_group, recorded_taxa_name_clean, weight_kg_corrected, value) %>%
  group_by(recorded_taxa_group, recorded_taxa_name_clean) %>%
  summarize(total_catch_2014.2024= sum(weight_kg_corrected, na.rm = TRUE),
            total_value_2014.2024= sum(value, na.rm = TRUE))
```

```{r Save Landings_GoC_TopMariculture_Summary to find MAR sustainability scores}
write.csv(Top_MaricultureSp_Summary, "/home/ferrer/ohi_goc_prep/FP/MAR_research/Mariculture_TopCatches_2014.2024_Feb242026.csv", row.names = FALSE)
```

```{r Mariculture Key}
# UNDER CONSTRUCTION (I did this manually, Feb 24 2026)
Mariculture_GroupKey<- read.csv("~/ohi_goc_prep/FP/MAR_research/Mariculture_GroupKey_UNDERCONSTRUCTION_Feb242026.csv")
```

```{r Merge and exclude}
Mariculture_Landings <- Mariculture_Landings %>%
  left_join(Mariculture_GroupKey,
            by = c("recorded_taxa_group", "recorded_taxa_name_clean"))

Mariculture_Landings<- Mariculture_Landings %>% filter(!MAR_Key_Manual=="Exclude")

Mariculture_Landings_Summary<- Mariculture_Landings %>% 
  filter(year >= 2014, year <= 2024) %>%
  select(year, MAR_Key_Manual, weight_kg_corrected, value) %>%
  group_by(MAR_Key_Manual, year) %>%
  summarize(annual_catch= sum(weight_kg_corrected, na.rm = TRUE),
            annual_value= sum(value, na.rm = TRUE))
```

```{r PLOT}
# Plot annual catch over time
ggplot(Mariculture_Landings_Summary, 
       aes(x = year, y = log10(annual_catch), color = MAR_Key_Manual, group = MAR_Key_Manual)) +
  geom_line(size = 1.2) +
  geom_point(size = 2) +
  scale_y_continuous(labels = scales::comma) +  # Adds commas to y-axis
  labs(
    title = "Annual Catch Over Time by MAR_Key_Manual",
    x = "Year",
    y = "Annual Catch (tons)",
    color = "Marine Category"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    text = element_text(size = 12)
  )
```





# SUMMARY STATS ABOUT OUR DATA: return to this later.
```{r How much of biomass includes information about species, genus, family?}
Landings_GoC %>%
  pull(estimated_species_name) %>%
  {c(n_na = sum(is.na(.)),
      n_unknown = sum(. == "unknown", na.rm = TRUE),
      n_NEI = sum(. == "NEI", na.rm = TRUE)
    ) }
# 1008085 (1839 + 205110 + 765582) out of 3559463 records (27%) for species are NA, "unknown", or "NEI"
# Meaning we have species info for 73% of records.

Landings_GoC %>%
  pull(estimated_genus_name) %>%
  {c(n_na = sum(is.na(.)),
     n_unknown = sum(. == "unknown", na.rm = TRUE),
     n_NEI = sum(. == "NEI", na.rm = TRUE)
    ) }
# 1008085 (206949 + 0 + 765582) out of 3559463 records (27%) for genus are NA, "unknown", or "NEI"
# Meaning we have genus info for 73% of records.

Landings_GoC %>%
  pull(estimated_family_name) %>%
  {c(n_na = sum(is.na(.)),
     n_unknown = sum(. == "unknown", na.rm = TRUE),
     n_NEI = sum(. == "NEI", na.rm = TRUE),
     n_family_info_pending = sum(. == "family missing but genus available", na.rm = TRUE)
    ) }
# 336348 (185825 + 0 + 150523) out of 3559463 records (9%) for family are NA, "unknown", or "NEI". 29438 (~1%) records have information about genus but family info pending.
# Meaning we already have or can get family info for 91% of records.
```