---
title: 'OHI GoC 2025: Population'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# Total population per municipality

To download, go to <https://www.inegi.org.mx/app/descarga/?t=123>, click Temas --> Demografía y Sociedad --> Población --> Población --> Indicadores (Inglés) 1910 - 2050.

Saved at `~/home/shares/ohi/OHI_GOC/_raw_data/census_inegi/estructura_english_00.xlsx`.  

```{r}
library(tidyverse)
library(here)
library(janitor)
library(mapview)
library(sf)
```

## Read in data

```{r}
population_raw <- readxl::read_xlsx(here::here("/home/shares/ohi/OHI_GOC/_raw_data/census_inegi/estructura_english_00.xlsx"), skip = 4) %>% 
  janitor::clean_names()

colnames(population_raw)
```

```{r}
## bring in the municipality to rgn_id code CSV I made...
municipality_to_rgnid <- read_csv(here::here("/home/shares/ohi/OHI_GOC/spatial/municipality_to_rgnid","municipality_to_rgnid.csv")) %>% 
  dplyr::select(-c("notes","municipio_raw")) %>% 
  janitor::clean_names() %>% 
  mutate(municipio = str_trim(municipio, side = "both"))
```

## Filter to GoC municipalities

```{r}
## filter to only GoC
population_goc <- population_raw %>% 
  mutate(cve_entidad = as.numeric(cve_entidad),
         cve_municipio = as.numeric(cve_municipio)) %>% 
  inner_join(municipality_to_rgnid, by = c("cve_entidad" = "e03","cve_municipio" = "e04")) %>% 
  ## also, filter to municipal total...it does not look like there is as complete of data for the other variables.
  filter(indicador %in% "Total population") %>% 
  # filter(!desc_municipio %in% c("Santa María del Oro", "Jala","Choix"))
  dplyr::select(cve_entidad, desc_entidad, cve_municipio, desc_municipio, indicador, unidad_medida, x2000, x2005, x2010, x2020, rgn_id, directly_coastal) %>% 
  pivot_longer(cols = x2000:x2020,
               names_to = c("year"),
               values_to = "pop_count"
  ) %>% 
  separate_wider_delim(year, delim = "x", names = c("delete","ano_censal")) %>% # clean up year
  dplyr::select(-delete)
```

## Save to mazu

```{r}
write_csv(population_goc, here::here("/home/shares/ohi/OHI_GOC/spatial/population_municipal","population_goc_municipality_inegi_2000_2020.csv"))
```



## 50km inland coastal population

```{r}
# load packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  here,
  CopernicusMarine,
  janitor,
  raster,
  terra,
  maps,
  httr,
  jsonlite,
  purrr,
  tictoc,
  sf, 
  googleVis,
  RColorBrewer,
  foreach,
  doParallel, # for using multiple cores, if needed
  tidyverse, 
  ohicore,
  ggplot2,
  reticulate, # for python coding
  ncmeta,
  ncdf4,
  plotly
)
```

```{r}
pop_2020_rast <- rast(here::here("/home/shares/ohi/OHI_GOC/goal_prep/pressures/population_rasters/pop_2020.tif"))

mapview(pop_2020_rast)

st_bbox(pop_2020_rast)
```

```{r}
inland_50 <- st_read(here::here("/home/shares/ohi/OHI_GOC/spatial/inland_50km_buffer","inland_50km_goc.shp"))

st_crs(inland_50) == st_crs(pop_2020_rast) # TRUE

res(inland_50) # polygon sf
raster::res(pop_2020_rast) # [1] 1000 1000

ext(inland_50) == ext(pop_2020_rast) #[1] FALSE

st_bbox(inland_50) == st_bbox(inland_50) 
# xmin ymin xmax ymax 
# TRUE TRUE TRUE TRUE 

```

```{r}
crop_pop_rast_2020 <- crop(pop_2020_rast, inland_50) # crop rast to 50km inland

mapview(crop_pop_rast_2020)
st_bbox(crop_pop_rast_2020)
```

```{r}
library(exactextractr)

zonal_stats_pop_inland_50 <- exact_extract(crop_pop_rast_2020, inland_50, 'sum')
inland_50$pop_sum_2020_inland_50 <- zonal_stats_pop_inland_50

inland_50_population_2020 <- inland_50 %>% 
  dplyr::select(rgn_id, pop_sum_2020_inland_50) %>% 
  st_drop_geometry()

# write_csv(inland_50_population_2020, here::here("/home/shares/ohi/OHI_GOC/spatial/population_inland_50km","extracted_pop2020_sum_by_rgn_inland_50.csv"))
```


```{r}
# municipio_codigo_sf <- st_read(here::here("/home/shares/ohi/OHI_GOC/spatial/land_admin_boundaries", "mex_admin2_joined_w_municipio_codigos.shp")) %>% 
#   mutate(e03 = as.numeric(clv_std),
#          e04 = as.numeric(clv_mnc))
#   
# 
# municipality_to_rgnid <- read_csv(here::here("/home/shares/ohi/OHI_GOC/spatial/municipality_to_rgnid","municipality_to_rgnid.csv")) %>% 
#   select(-c("notes","municipio_raw")) %>% 
#   janitor::clean_names() %>% 
#   mutate(municipio = str_trim(municipio, side = "both"))
# 
# only_goc_municipios <- inner_join(municipality_to_rgnid, municipio_codigo_sf, by = c("e03","e04")) %>% 
#   st_as_sf()
# 
# zonal_stats_total_possible_pop <- exact_extract(pop_2020_rast, only_goc_municipios, 'sum')
# inland_50$pop_sum_2020_inland_50 <- zonal_stats_pop_inland_50


```




```{r}
# exact_extract(crop_pop_rast_2020, inland_50[1, ], 'sum', progress = FALSE)
# exact_extract(crop_pop_rast_2020, inland_50[1, ], 'mean', progress = FALSE)
# 
# 
# r1 <- inland_50 %>% filter(rgn_id == 1)
# r1_area_km2 <- st_area(r1) / 1e6
# r1_pop <- exact_extract(crop_pop_rast_2020, r1, 'sum')[[1]]
# r1_density <- r1_pop / r1_area_km2
# r1_area_km2
# r1_pop
# r1_density

```




```{r}
# pop_rast_2 <- rasterize(
#   x = pop_loc_vect,
#   y = r_template,
#   field = "POBTOT",
#   fun = "sum",
#   background = 0
# )
# 
# # same field for point data, still POBTOT
# pop_pts_rast_2 <- rasterize(
#   x = pop_pts_vect,
#   y = r_template,
#   field = "POBTOT",
#   fun = "sum",
#   background = 0
# )
# 
# final_raster_2 <- pop_pts_rast_2 + pop_rast_2
# 
# crop_pop_rast_2020_2 <- crop(final_raster_2, inland_50)
# zonal_stats_pop_inland_50_2 <- exact_extract(crop_pop_rast_2020, inland_50, 'sum')
# 
# sum(inland_50$zonal_stats_pop_inland_50_2, na.rm = TRUE)

```


### Use polygons of localities instead of extracting from raster

```{r}
library(sf)
library(dplyr)

# find which localities intersect each inland_50 region

pop_loc <- st_read(here::here("/home/shares/ohi/OHI_GOC/goal_prep/pressures/population_localities/inegi_boundaries_pop.shp"))

# checkCRS
st_crs(inland_50)
st_crs(pop_loc)

# transform pop_loc to match inland_50 (EPSG:6372)
pop_loc_transformed <- st_transform(pop_loc, st_crs(inland_50))
st_crs(inland_50) == st_crs(pop_loc_transformed)  # TRUE

intersections <- st_intersects(inland_50, pop_loc_transformed, sparse = FALSE)

# sum from intersections matrix
intersecting_rows_list <- apply(intersections, 1, which)  # list of row indices per region

pop_by_region_vector <- tibble(
  rgn_id = inland_50$rgn_id,
  pop_sum_2020_inland_50 = sapply(intersecting_rows_list, function(rows) {
    if(length(rows) == 0) 0 else sum(pop_loc_transformed$POBTOT[rows], na.rm = TRUE)
  }),
  n_localities = sapply(intersecting_rows_list, length)
)
print(pop_by_region_vector)

# write_csv(pop_by_region_vector, here::here("/home/shares/ohi/OHI_GOC/spatial/population_inland_50km","pop2020_by_region_vector_inland_50.csv"))

```

```{r}
inegimuni <- st_read(here::here("/home/shares/ohi/OHI_GOC/spatial/delimitaciones_frontera_municipales_inegi","INEGI_Municipal_.shp")) %>% 
  distinct() %>% 
  st_as_sf()

m1 <- mapview(inegimuni)
m2 <- mapview(pop_loc, zcol = "POBTOT")
m1 + m2

municipality_to_rgnid_codigo <- municipality_to_rgnid %>% 
  mutate(e03 = as.character(e03),
         e04 = as.character(e04)) %>% 
  unite("ID", e03, e04, sep = " ")
```

