################################################################################

Erica Ferrer
ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
# Visualization
library(ggplot2)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/FP/")
```

# CPUE Estimates per Major_Functional_Group ------------------------------

# STEP 1: Interrogate the economic unit (eu_rnpa) and vessel (vessel_name) columns. ------------------------------

```{r Load in dataframe as needed}
GOC_MarineLandings0<- readRDS(here("/home/shares/ohi/OHI_GOC/goal_prep/fp/cleaned_CONAPESCA/GOC_Marine.Landings_Sector.Sorted.Georef_PATCHED_Jun032026.rds"))
# 3246583 obs., 58 vars.

dim(GOC_MarineLandings0)
# 3246583 obs., 58 vars.

# NOTE TO SELF: This file path will change when I create the "fisheries only" dataframe. - June 1 2026
# And when I patch any remaining species, genus, family, or sector adjustments - June 3 2026

table(GOC_MarineLandings0$GOC_Include_Exclude)
```

# **DECISION POINT: Selecting which sectors to include**
```{r Select Sectors_of_Interest}
table(GOC_MarineLandings0$sector_estimate_draft)

# SANITY CHECK: Which species are included in the freshwater or marine sector?
TEST<- GOC_MarineLandings0 %>%
  filter(sector_estimate_draft== "freshwater or marine: fishery sector yet to be classified")

table(TEST$recorded_taxa_group)
# Species like Mojarra (the overwhelming majority of catch), trout, and catfish, which can move from freshwater to marine systems and are a bit ambiguous in terms of where they can be caught.


MarineFishery_Sectors<- c("marine: fishery sector yet to be classified",
                          "marine: small-scale capture",
                          "marine: large-scale capture")
  
PossibleMarineFishery_Sectors<- c("freshwater or marine: large-scale capture",
                          "freshwater or marine: small-scale capture",
                          "freshwater or marine: fishery sector yet to be classified")

GOC_MarineFisheryLandings0<- GOC_MarineLandings0 %>%
  filter(sector_estimate_draft %in% c(MarineFishery_Sectors, PossibleMarineFishery_Sectors))

# 3137044 obs., 58 var.
```

# STEP 2: Esitmate CPUE per economic unit 2018-2024 

# ** MEL! This is the chunk of code I used to make the CatchPerEconomicUnit_summary!!! **
```{r Estimate CPUE per economic unit 2018-2024}
# Let's look through unit Economic Units. All records have a non-NA economic unit (at least since 2018)
EconomicUnits <- GOC_MarineFisheryLandings0 %>%
  distinct(eu_rnpa)
# 4525 obs.

# Estimate Catch per economic unit 2018-2024: summarize weight_kg_corrected by eu_rnpa per year
CatchPerEconomicUnit_summary <- GOC_MarineFisheryLandings0 %>%
  filter(year >= 2018 & year <= 2024) %>%   # filter the years
  group_by(year, eu_rnpa) %>%              # group by year and economic unit
  summarize(
    total_catch_kg = sum(weight_kg_corrected, na.rm = TRUE)  # sum catch, ignore NAs
  ) %>%
  ungroup()  # remove grouping after summarizing
# 13438 obs., 3 vars.
```

```{r Save dataframe as needed}
# Save the plot as a high-resolution PNG
write.csv(CatchPerEconomicUnit_summary,
          "/home/ferrer/ohi_goc_prep/FP/FP_Scores/FIS_Scores/FIS_CPUE_Scores/CatchPerEconomicUnit_summary_Jun082026.csv",
          row.names= FALSE)
```


```{r Estimate CPUE per economic unit 2018-2024}
# Mel adding Major Functional Group as well

# Estimate Catch per economic unit 2018-2024: summarize weight_kg_corrected by eu_rnpa per year
CatchPerEconomicUnit_group_summary <- GOC_MarineFisheryLandings0 %>%
  filter(year >= 2018 & year <= 2024) %>%   # filter the years
  group_by(year, eu_rnpa, Major_Functional_Group) %>%              # group by year and economic unit
  summarize(
    total_catch_kg = sum(weight_kg_corrected, na.rm = TRUE)  # sum catch, ignore NAs
  ) %>%
  ungroup()  # remove grouping after summarizing
```

```{r Save dataframe as needed}
# Save the plot as a high-resolution PNG
write_csv(CatchPerEconomicUnit_group_summary,
          here("FP/FP_Scores/FIS_Scores/FIS_CPUE_SubScores/CPUE_In_Progress/CatchPerEconomicUnit_group_summary_Jun102026.csv"))
```



# Other...

```{r Pull out the eu_rnpas that are consistently present in all years 2018-2025}
# Using these eu_rnpas only, estimate the total catch of Major_Taxa_Group divided by the total eu_rnpa per year

# Step 1: Identify eu_rnpa present in all years
ConsistentEconomicUnits <- GOC_MarineFisheryLandings0 %>%
  filter(year >= 2018 & year <= 2025) %>%
  group_by(eu_rnpa) %>%
  summarize(years_present = n_distinct(year), .groups = "drop") %>%
  filter(years_present == 8) %>%    # 2018–2025 = 8 years
  pull(eu_rnpa)                     # get vector of eu_rnpa
# 1024 eu.rnpas are consistently present in all years 2018-2025

# Step 2: Filter data to only include these eu_rnpa
GOC_CPUE_Landings <- GOC_MarineFisheryLandings0 %>%
  filter(year >= 2018 & year <= 2025) %>%
  filter(eu_rnpa %in% ConsistentEconomicUnits)
# 882461 obs., 58 vars.

# SANITY CHECK: Do all landings have a Major_Functional_Group assigned? All but 10 observations.
sum(is.na(GOC_CPUE_Landings$Major_Functional_Group))
```

```{r Summarize catch per EU by Major_Functional_Group per year}
colnames(GOC_CPUE_Landings)

CPUE_summary <- GOC_CPUE_Landings %>%
  group_by(year, Major_Functional_Group) %>%
  summarize(
    total_catch_mt = sum(weight_kg_corrected, na.rm = TRUE)/1000,
    n_eu = n_distinct(eu_rnpa),                    # number of economic units that year
    catch.mt_per_eu = total_catch_mt / n_eu          # divide total catch by number of units
  ) %>%
  ungroup()

# Looking promising! Let's plot it...
```

```{r Plot CPUE for each Major_Functional_Group}
# PLOT FOR ALL GROUPS, excluding Small Pelagics:
# Remove NAs or 'unknown' if you don’t want them cluttering the plot
# First compute overall yearly mean (across all groups)

# First we need mean CPUE over years per group (2018-2024)
CPUE_mean_df <- CPUE_summary %>%
  filter(year > 2017 & year < 2025) %>%
  group_by(Major_Functional_Group) %>%
  summarise(mean_cpue = mean(catch.mt_per_eu), 
            .groups = "drop")

CPUE_perEU_plot <- 
  
  CPUE_summary %>%
  filter(year < 2025) %>%
  
  ggplot(aes(x = year, y = catch.mt_per_eu)) +
  
  # Group-specific lines
  geom_line(aes(color = Major_Functional_Group), size = 1.1) +
  geom_point(aes(color = Major_Functional_Group), size = 2) +
  
  facet_wrap(~ Major_Functional_Group, scales = "free_y") +
  
  geom_hline(
  data = CPUE_mean_df,
  aes(yintercept = mean_cpue, group = Major_Functional_Group),
  color = "grey40",
  linetype = "dashed",
  linewidth = 0.8) +
  
  labs(
    title = "CPUE per Economic Unit by Functional Group (2018-2024)",
    x = "Year",
    y = "Catch per Economic Unit (mt)"
  ) +
  
  theme_bw() +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

CPUE_perEU_plot
```