---
title: "Soft bottom - Gulf of California OHI"
author: "Austin Martinez"
date: 07/10/2026
format: 
  html:
    code-fold: show
execute:
  echo: true
  message: false
  warning: false
---


```{r}
# Load in Libraries
library(sf)
library(dplyr)
library(here)
library(terra)
library(tidyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tmap)
```

# what depth does destructive fishing practicies occur in general what the min depth
```{r}
#ohi_regions <- rast(here("spatial", "ohi_regions", "marine_raster_prop_1km.tif"))

ohi_regions <- st_read(here("spatial", "ohi_regions", "goc_ohi_rgns.shp")) |> st_make_valid()

ohi_regions_marine <- ohi_regions |>
  filter(location == "marine")

#ohi_regions_inner <- st_buffer(ohi_regions_marine, dist = -1600)

gmrt_depth <- rast("/home/shares/ohi/OHI_GOC/_raw_data/GMRT_bathymetry_data/GMRTv4_5_0_20260709topo.tif")
```


```{r}
gmrt_depth <- project(gmrt_depth, crs(ohi_regions_marine))

ohi_mask <- rasterize(
  vect(ohi_regions_marine),
  gmrt_depth,
  field = 1,
  background = 0
)

ohi_mask <- resample(ohi_mask, gmrt_depth)

```

```{r}
ohi_mask_na <- classify(ohi_mask, rbind(c(0, NA)))

tmap_mode("view")

tm_shape(ohi_mask_na) +
  tm_raster(
    title = "OHI Marine Mask",
    palette = "blue",
    alpha = 0.5
  )

```

```{r}
gmrt_crop <- crop(gmrt_depth, ohi_mask)

gmrt_mask <- mask(gmrt_crop, ohi_mask, maskvalues = 0)

```

```{r}
plot(gmrt_mask)
```

```{r}
tmap_mode("view")

tm_shape(gmrt_mask) +
  tm_raster(
    title = "GMRT Bathymetry (m)",
    breaks = c(
  -4500,
  -4000,
  -3500,
  -2500,
  -2000,
  -1500,
  -1000,
  -500,
  -200,
  -50,
  0,
  500,
  1500,
  3000,
  4500
),
    alpha = 0.9,
    style = "cont"
  )  +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)

```
## Destructive fishing data

At what depths do bottom‑destructive fishing practices occur, and what is the minimum depth?

```{r}
# Years of destructive fishing data available
years <- 2007:2025

# Build full file paths for each year's raster and load them into a multi-layer SpatRaster
fishing_rasters <- rast(
  paste0(
    "/home/shares/ohi/OHI_GOC/goal_prep/pressures/vessels/benthic_destructive_fishing/destructive_fishing_hours_",
    years,
    "_1km.tif"
  )
)

# Print the total rasters in the stack
nlyr(fishing_rasters)
```

```{r}
# Mask bathymetry to only places with fishing effort
gmrt_resampled <- resample(gmrt_mask, fishing_rasters[[1]])

depth_where_fished <- mask(gmrt_resampled, fishing_rasters[[1]] > 0)
```


```{r}
depth_where_fished <- mask(
  gmrt_resampled,
  fishing_rasters[[1]],
  maskvalues = 0
)

```

```{r}
# Extract depth values
depth_vals <- values(depth_where_fished, na.rm = TRUE)

summary(depth_vals)
```



```{r}
breaks_ecological <- c(-4000, -1000, -200, -50, -20, 0, 50)

tmap_mode("view")

tm_shape(depth_where_fished) +
  tm_raster(
    title = "GMRT Bathymetry (m)",
    breaks = breaks_ecological,
    alpha = 0.9,
    style = "cont"
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(col = "black", lwd = .5) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)

```






# With vector data
```{r}
ohi_regions <- st_read(here("spatial", "ohi_regions", "goc_ohi_rgns.shp")) |> 
  st_make_valid()

ohi_regions_marine <- ohi_regions |> 
  filter(location == "marine")

gmrt_depth <- rast("/home/shares/ohi/OHI_GOC/_raw_data/GMRT_bathymetry_data/GMRTv4_5_0_20260709topo.tif")

```

```{r}
ohi_regions_marine <- st_transform(ohi_regions_marine, crs(gmrt_depth))

gmrt_mask <- mask(gmrt_depth, vect(ohi_regions_marine))

gmrt_crop <- crop(gmrt_mask, vect(ohi_regions_marine))

```

```{r}
tmap_mode("view")

tm_shape(gmrt_crop) +
  tm_raster(
    title = "GMRT Bathymetry (m)",
    breaks = c(
      -4500, -4000, -3500, -2500, -2000,
      -1500, -1000, -500, -200, -50,
      0, 500, 1500, 3000, 4500
    ),
    alpha = 0.9,
    style = "cont"
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(col = "black", lwd = 0.5) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)

```

```{r}
gmrt_resampled <- resample(gmrt_crop, fishing_rasters[[1]])

depth_where_fished <- mask(
  gmrt_resampled,
  fishing_rasters[[1]],
  maskvalues = 0
)
```

```{r}
depth_vals <- values(depth_where_fished, na.rm = TRUE)
summary(depth_vals)

```
# Raster:
GMRTv4_5_0_20260709topo
 Min.   :-3789.90       
 1st Qu.:  -56.29       
 Median :  -31.36       
 Mean   :  -42.70       
 3rd Qu.:  -15.24       
 Max.   :   43.69 
 
 
```{r}
breaks_ecological <- c(-4000, -1000, -200, -50, -20, 0, 50)

tmap_mode("view")

tm_shape(depth_where_fished) +
  tm_raster(
    title = "Depth Where Fishing Occurred (m)",
    breaks = breaks_ecological,
    alpha = 0.9,
    style = "cont"
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(col = "black", lwd = 0.5) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)

```

