---
title: 'OHI GoC 2025: Isolate GoC Municipios'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

## Isolate municipos

This script's exploration led to this manually made .CSV: `~/home/shares/ohi/OHI_GOC/spatial/municipality_to_rgnid/municipality_to_rgnid.csv`


```{r}
library(tidyverse)
library(mapview)
library(sf)
```


Using this pdf of the codes for each municipality: <https://www.gob.mx/cms/uploads/attachment/file/179869/Municipios_por_Regiones__atendidos_.pdf>

NOTE THAT SAN FELIPE was recently added in 2022 as a municipality.  Updated municipalities will need to be used. 

```{r}
library(DT)

raw_text <- paste(
  "02 BAJA_CALIFORNIA 001 ENSENADA 2 2.59",
  "02 BAJA_CALIFORNIA 002 MEXICALI 1 2.02",
  "02 BAJA_CALIFORNIA 003 TECATE 6 4.28",
  "02 BAJA_CALIFORNIA 004 TIJUANA 1 2.02",
  "02 BAJA_CALIFORNIA 005 PLAYAS_DE_ROSARITO 2 2.59",
  "02 BAJA_CALIFORNIA 006 SAN QUINTÍN 2 NA", ## added manually... because of 2022 changes: https://en.wikipedia.org/wiki/Municipalities_of_Baja_California
  "02 BAJA_CALIFORNIA 007 SAN FELIPE 2 NA", ## added manually... because of 2022 changes: https://en.wikipedia.org/wiki/Municipalities_of_Baja_California
  "03 BAJA_CALIFORNIA_SUR 001 COMONDU 3 3.03",
  "03 BAJA_CALIFORNIA_SUR 002 MULEGE 3 3.03",
  "03 BAJA_CALIFORNIA_SUR 003 LA_PAZ 3 3.03",
  "03 BAJA_CALIFORNIA_SUR 008 LOS_CABOS 3 3.03",
  "03 BAJA_CALIFORNIA_SUR 009 LORETO 4 3.53",
  "14 JALISCO 067 PUERTO_VALLARTA 6 4.28",
  "14 JALISCO 020 CABO_CORRIENTES 1 2.02",
  "18 NAYARIT 001 ACAPONETA 2 2.59",
  "18 NAYARIT 002 AHUACATLAN 1 2.02",
  "18 NAYARIT 003 AMATLAN_DE_CAÑAS 1 2.02",
  "18 NAYARIT 004 COMPOSTELA 2 2.59",
  "18 NAYARIT 006 IXTLAN_DEL_RIO 1 2.02",
  "18 NAYARIT 007 JALA 6 4.28",
  "18 NAYARIT 008 XALISCO 2 2.59",
  "18 NAYARIT 010 ROSAMORADA 2 2.59",
  "18 NAYARIT 011 RUIZ 2 2.59",
  "18 NAYARIT 012 SAN_BLAS 3 3.03",
  "18 NAYARIT 013 SAN_PEDRO_LAGUNILLAS 1 2.02",
  "18 NAYARIT 014 SANTA_MARIA_DEL_ORO 3 3.03",
  "18 NAYARIT 015 SANTIAGO_IXCUINTLA 2 2.59",
  "18 NAYARIT 016 TECUALA 1 2.02",
  "18 NAYARIT 017 TEPIC 6 4.28",
  "18 NAYARIT 018 TUXPAN 3 3.03",
  "18 NAYARIT 020 BAHIA_DE_BANDERAS 3 3.03",
  "25 SINALOA 001 AHOME 4 3.53",
  "25 SINALOA 002 ANGOSTURA 2 2.59",
  "25 SINALOA 003 BADIRAGUATO 6 4.28",
  "25 SINALOA 004 CONCORDIA 2 2.59",
  "25 SINALOA 005 COSALA 3 3.03",
  "25 SINALOA 006 CULIACAN 5 3.90",
  "25 SINALOA 007 CHOIX 5 3.90",
  "25 SINALOA 008 ELOTA 5 NA", # added in when found missing 
  "25 SINALOA 009 ESCUINAPA 2 2.59",
  "25 SINALOA 010 EL_FUERTE 3 3.03",
  "25 SINALOA 011 GUASAVE 6 4.28",
  "25 SINALOA 012 MAZATLAN 5 3.90",
  "25 SINALOA 013 MOCORITO 2 2.59",
  "25 SINALOA 014 ROSARIO 2 2.59",
  "25 SINALOA 015 SALVADOR_ALVARADO 2 2.59",
  "25 SINALOA 016 SAN_IGNACIO 2 NA", # added in when found missing 
  "25 SINALOA 017 SINALOA 3 3.03",
  "25 SINALOA 018 NAVOLATO 2 2.59",
  "26 SONORA 002 AGUA_PRIETA 6 4.28",
  "26 SONORA 003 ALAMOS 3 3.03",
  "26 SONORA 004 ALTAR 2 2.59",
  "26 SONORA 007 ATIL 6 4.28",
  "26 SONORA 012 BACUM 5 3.90",
  "26 SONORA 014 BAVIACORA 5 3.90",
  "26 SONORA 016 BENJAMIN_HILL 6 4.28",
  "26 SONORA 017 CABORCA 2 2.59",
  "26 SONORA 018 CAJEME 6 4.28",
  "26 SONORA 025 EMPALME 6 4.28",
  "26 SONORA 026 ETCHOJOA 6 4.28",
  "26 SONORA 029 GUAYMAS 5 3.90",
  "26 SONORA 030 HERMOSILLO 6 4.28",
  "26 SONORA 033 HUATABAMPO 3 3.03",
  "26 SONORA 035 IMURIS 6 4.28",
  "26 SONORA 036 MAGDALENA 5 3.90",
  "26 SONORA 037 MAZATAN 2 2.59",
  "26 SONORA 042 NAVOJOA 6 4.28",
  "26 SONORA 043 NOGALES 3 3.03",
  "26 SONORA 045 OPODEPE 4 3.53",
  "26 SONORA 047 PITIQUITO 3 3.03",
  "26 SONORA 048 PUERTO_PEÑASCO 3 3.03",
  "26 SONORA 054 SAN_JAVIER 3 3.03",
  "26 SONORA 055 SAN_LUIS_RIO_COLORADO 4 3.53",
  "26 SONORA 056 SAN_MIGUEL_DE_HORCASITAS 4 3.53",
  "26 SONORA 058 SANTA_ANA 5 3.90",
  "26 SONORA 065 TUBUTAMA 6 4.28",
  "26 SONORA 070 GENERAL_PLUTARCO_ELIAS_CALLES 1 2.02",
  "26 SONORA 071 BENITO_JUAREZ 3 3.03",
  "26 SONORA 072 SAN_IGNACIO_RIO_MUERTO 5 3.90",
  sep = "\n"
)

library(purrr)

lines <- str_split(raw_text, "\n")[[1]]

municipio_codigo_raw_df <- map_dfr(lines, function(x) {
  parts <- str_split(x, " +")[[1]]   # split on spaces
  tibble(
    clave_estado   = parts[1],
    estado         = parts[2] |> str_replace_all("_", " "),
    clave_municipio = parts[3],
    region         = as.integer(parts[length(parts) - 1]),
    tasa_regional  = as.numeric(parts[length(parts)]),
    municipio      = paste(parts[4:(length(parts) - 2)], collapse = " ") |> 
                      str_replace_all("_", " ")
  )
}) 

municipio_codigo_df <- municipio_codigo_raw_df %>% 
  dplyr::select(clave_estado, estado, clave_municipio, municipio, tasa_regional)

write_csv(municipio_codigo_df, here::here("/home/shares/ohi/OHI_GOC/spatial/land_admin_boundaries", "municipio_codigos_secreteria_de_economia.csv"))
```

Combine with shapefile for each municipality.

```{r}
municipios <- st_read(here::here("/home/shares/ohi/OHI_GOC/spatial/land_admin_boundaries/mex_admin_boundaries.shp","mex_admin2.shp")) %>% 
  mutate(nom_mun = str_to_upper(adm2_ref_n),
         nom_ent = str_to_upper(adm1_name)) %>% 
  select(nom_ent, nom_mun) %>% 
  filter(nom_ent %in% c("BAJA CALIFORNIA SUR", "BAJA CALIFORNIA", "SINALOA", "SONORA", "NAYARIT", "JALISCO")) %>% 
  mutate(
    nom_mun = str_replace(nom_mun, "PUERTO PENASCO", "PUERTO PEÑASCO"),
    nom_mun = str_replace(nom_mun, "AMATLAN DE CANAS", "AMATLAN DE CAÑAS")
  )

mapview(municipios)

# see if they match
setdiff(municipio_codigo_sf$municipio, municipios$nom_mun) # character(0)
# setdiff(municipios$nom_mun, municipio_codigo_sf$municipio)

municipio_codigo_sf <- inner_join(municipio_codigo_df, municipios, by = c("municipio" = "nom_mun", "estado" = "nom_ent")) %>% 
  st_as_sf()

mapview(municipio_codigo_sf)

# st_write(municipio_codigo_sf, here::here("/home/shares/ohi/OHI_GOC/spatial/land_admin_boundaries", "mex_admin2_joined_w_municipio_codigos.shp"), append = FALSE)
```
