---
title: 'OHI GoC 2025: Clean waters pharmaceuticals'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# CW: Pharmaceuticals - WWTP Effluent

## Estimated pharmaceutical discharge

```{r setup}
library(sf)
library(utils)
library(tidyverse)
library(here)
library(raster)
library(mapview)
library(purrr)
library(stringr) # fuzzy string matching
library(stringi)
library(janitor)
library(tibble)
```

### Watersheds and pour points

```{r}
## lets use the full state for now and then summarize by the full watersheds.
goc_ohi_rgns <- st_read(here::here("spatial/ohi_regions","goc_ohi_rgns.shp"))

union_rgns <- goc_ohi_rgns %>% 
  st_union() %>% 
  st_make_valid()

# plot(goc_ohi_rgns)
# plot(union_rgns)

watershed_all <- st_read(file.path("/home/shares/ohi/stressors_2021/_dataprep/nutrients/watersheds_pourpoints/watersheds_all_4326.shp"))
st_crs(watershed_all)
# mapview(watershed_all)

watershed_goc <- st_intersection(st_transform(watershed_all, st_crs(union_rgns)), union_rgns)
mapview(watershed_goc)

# --- if we plan to change the buffer for some reason ---
# inland_50 <- st_read(here::here("/home/shares/ohi/OHI_GOC/spatial/inland_50km_buffer","inland_50km_goc.shp"))
# watershed_goc_50km <- st_intersection(st_transform(watershed_all, st_crs(inland_50)), inland_50)
# mapview(watershed_goc_50km)
```


```{r}
# here's the associated pourpoints that should match with the watersheds:
pourpoints <- st_read("/home/shares/ohi/stressors_2021/_dataprep/nutrients/watersheds_pourpoints/pourpoints_mol.shp")

pourpoints_goc <- st_intersection(st_transform(pourpoints, st_crs(union_rgns)), union_rgns)
mapview(pourpoints_goc)

mapview(pourpoints_goc) + mapview(watershed_goc)
```


```{r}
sina <- st_read(here::here("/home/shares/ohi/OHI_GOC/_raw_data/SINA_3_CONAGUA/d2025/m02_costerosprom/m02_costerospromPoint.shp"))
colnames(sina)
```


## Water treatment plant exploration

```{r}
sina3.0_wtp <- st_read(here::here("/home/shares/ohi/OHI_GOC/_raw_data/SINA_3_CONAGUA/d2025/m30_vwplantaspotm/m30_vwplantaspotm.shp"))

colnames(sina3.0_wtp)
head(sina3.0_wtp)

unique(sina3.0_wtp$estado)
```

```{r}
# only in GoC states
sina3.0_wtp_goc <- sina3.0_wtp %>% 
  filter(estado %in% c("Baja California Sur","Baja California","Jalisco","Sinaloa","Sonora")) # no nayarit
```


## WASTEwater treatment plant exploration

```{r}
sina3.0_wwtp <- st_read(here::here("/home/shares/ohi/OHI_GOC/_raw_data/SINA_3_CONAGUA/d2025/m29_vwplantastarm/m29_vwplantastarmPoint.shp"))

colnames(sina3.0_wwtp)
head(sina3.0_wwtp)

unique(sina3.0_wwtp$estado)
```

```{r}
# only in GoC states
sina3.0_wwtp_goc <- sina3.0_wwtp %>% 
  filter(estado %in% c("Baja California Sur","Baja California","Jalisco","Sinaloa","Sonora","Nayarit")) 
```

```{r}
over_processing <- sina3.0_wwtp_goc %>% 
  mutate(over_proc = case_when(
    caudal > capacidad ~ TRUE,
    TRUE ~ FALSE
  ))
```





