---
title: "Soft bottom - Gulf of California OHI"
author: "Austin Martinez"
date: 07/10/2026
format: 
  html:
    code-fold: show
execute:
  echo: true
  message: false
  warning: false
---


```{r}
# Load in Libraries
library(sf)
library(dplyr)
library(here)
library(terra)
library(tidyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tmap)
```

```{r}
# Read in OHI region boundaries
ohi_regions <- st_read(here("spatial", "ohi_regions", "goc_ohi_rgns.shp")) |> st_make_valid()

ohi_regions_marine <- ohi_regions |>
  filter(location == "marine")
```

```{r}
# Arrecife rocoso (rocky reef)
rocky_reef <- st_read(here("/home/shares/ohi/OHI_GOC/_raw_data/Hem_data/goc_habitat_data/Arrecife rocoso/Arrecife rocoso.shp")) |> 
  st_make_valid() |> 
  st_transform(st_crs(ohi_regions))

# Read in Allen polygon data
atlas_coral <- st_read("/home/shares/ohi/OHI_GOC/_raw_data/ALLEN_coral_Atlas/Mexican-Exclusive-Economic-Zone-20230309211010/Reef-Extent/reefextent.gpkg") |> 
  st_make_valid()  |>
  st_transform(st_crs(ohi_regions))

# Rodoliths
rodoliths <- st_read(here("/home/shares/ohi/OHI_GOC/_raw_data/Hem_data/goc_habitat_data/rodoliths/rodolith_merge.shp")) |> 
  st_make_valid() |> 
  st_transform(st_crs(ohi_regions))

# Seamounts
seamounts <- st_read(here("/home/shares/ohi/OHI_GOC/_raw_data/Hem_data/goc_habitat_data/seamount/seamount_merge.shp")) |> 
  st_make_valid() |> 
  st_transform(st_crs(ohi_regions))

print(st_crs(seamounts) == st_crs(ohi_regions))
```
union all of vector together and just leave rocky reef and seamount
```{r}
# Make data match extent of the ohi_regions layer
#rocky_reef       <- st_intersection(rocky_reef, ohi_regions)
rodoliths        <- st_intersection(rodoliths, ohi_regions) # leave it out later
seamounts        <- st_intersection(seamounts, ohi_regions)
atlas_coral      <- st_intersection(atlas_coral, ohi_regions)

```

## rocky_reef work:
```{r}
# Find proportion of pixel that is rocky reef
rocky_reef <- rocky_reef |>
  mutate(
    rocky_km2 = rocky_ha / 100, # Convert rocky_ha from hectares to km2
    polygon_km2 = as.numeric(st_area(geometry)) / 1e6, # Find area of polygons
    prop_rocky_reef = rocky_km2 / polygon_km2 # Find proportion of polygon that is rocky reef
  )
```



```{r}
# Make a template raster to use in rasterization to make sure cell grids line up
template <- rast(here("spatial", "ohi_regions", "ohi_marine_raster_1km.tif "))

template_100m <- rast(
  ext(ohi_regions),
  resolution = 100,   # 100 m res
  crs = st_crs(ohi_regions)$wkt
)
```

# Rocky reef rasterization:
```{r}
# Rasterize rocky reef polygon proportions
rocky_reef_prop_r <- rasterize(vect(rocky_reef), template_100m, field = "prop_rocky_reef", background = 0)

# Crop raster to OHI regions
rocky_reef_prop_crop <- crop(rocky_reef_prop_r, ohi_regions)

# Mask raster to OHI regions
rocky_reef_prop_mask <- mask(rocky_reef_prop_crop, ohi_regions)
```

```{r}
tmap_mode("view")

tm_shape(rocky_reef_prop_mask) +
  tm_raster(
    palette = "-viridis",
    title = "Proportion Rocky Reef",
    alpha = 0.8,
    style = "fixed",
    breaks = c(0, 0.0092, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
    legend.format = list(digits = 4)
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(
    col = "white",
    lwd = 2,
    alpha = 0.9
  ) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)

```

```{r}
tmap_mode("view")

tm_shape(rocky_reef_prop_mask) +
  tm_raster(
    palette = "-viridis",
    title = "Proportion Rocky Reef",
    alpha = 0.8,
    breaks = seq(0, 1, by = 0.1),   # exact breakpoints
    style = "fixed",                # force exact bins
    legend.format = list(digits = 2)
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(
    col = "white",
    lwd = 2,
    alpha = 0.9
  ) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)


```




```{r}
# Rasterize the vector data
#rocky_reef_r <- rasterize(vect(rocky_reef), template_100m, field = 1, background = 0)
rodoliths_r  <- rasterize(vect(rodoliths),  template_100m, field = 1, background = 0)
seamounts_r  <- rasterize(vect(seamounts),  template_100m, field = 1, background = 0)
coral_r      <- rasterize(vect(atlas_coral), template_100m, field = 1, background = 0)

```

## Quick validation
```{r}
# Check alignment (resolution, origin, extent, CRS, rotation, cell alignment)
compareGeom(rocky_reef_prop_mask, template_100m)
compareGeom(coral_r, template_100m)
compareGeom(rodoliths_r, template_100m)
compareGeom(seamounts_r, template_100m)
```


```{r}
# Make raster where 0 = no hard‑bottom and 1+ = hard‑bottom present
hard_bottom_100m <- rocky_reef_prop_mask +
                    rodoliths_r +
                    seamounts_r +
                    coral_r

```


```{r}
# Groups every 10×10 block of 100‑m cells into one 1‑km cell, and computes the mean of values inside that block
hard_bottom_fraction <- aggregate(hard_bottom_100m, fact = 10, fun = "mean")

# flips the fraction so more soft bottom = 1
soft_bottom_fraction <- 1 - hard_bottom_fraction
```



```{r}
tmap_mode("view")

tm_shape(soft_bottom_fraction) +
  tm_raster(
    palette = "-viridis",
    title = "Proportion Rocky Reef",
    alpha = 0.8,
    breaks = seq(0, 1, by = 0.1),   # FORCE scale 0 → 1
    legend.format = list(digits = 2)
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(
    col = "gray",
    lwd = 2,
    alpha = 0.9
  ) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)

```

```{r}
marine_mask <- rasterize(
  vect(ohi_regions_marine),
  soft_bottom_fraction,
  field = 1,
  background = NA
)

soft_bottom_fraction_marine <- mask(soft_bottom_fraction, marine_mask)

```



```{r}
tmap_mode("view")

tm_shape(soft_bottom_fraction_marine) +
  tm_raster(
    palette = "-viridis",
    title = "Proportion Rocky Reef",
    alpha = 0.8,
    breaks = seq(0, 1, by = 0.1),   # FORCE scale 0 → 1
    legend.format = list(digits = 2)
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(
    col = "white",
    lwd = 2,
    alpha = 0.9
  ) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)
```



```{r}
tmap_mode("view")
tmap_options(check.and.fix = TRUE)

tm_shape(ohi_regions_marine) +
  tm_borders(col = "black", lwd = 1) +

#tm_shape(rocky_reef) +
#  tm_fill(col = "green", alpha = 0.5) +
#  tm_borders(col = "green") +

tm_shape(atlas_coral) +
  tm_fill(col = "blue", alpha = 0.5) +
  tm_borders(col = "blue") +
  
tm_shape(rodoliths) +
  tm_fill(col = "purple", alpha = 0.5) +
  tm_borders(col = "purple") +

tm_shape(seamounts) +
  tm_fill(col = "red", alpha = 0.5) +
  tm_borders(col = "red") +

tm_layout(
  frame = FALSE,
  legend.outside = TRUE,
  legend.outside.position = "right"
)

```



## Destructive fishing data

```{r}
# Years of destructive fishing data available
years <- 2007:2025

# Build full file paths for each year's raster and load them into a multi-layer SpatRaster
fishing_rasters <- rast(
  paste0(
    "/home/shares/ohi/OHI_GOC/goal_prep/pressures/vessels/benthic_destructive_fishing/destructive_fishing_hours_",
    years,
    "_1km.tif"
  )
)

# Print the total rasters in the stack
nlyr(fishing_rasters)
```

```{r}
soft_bottom_aligned <- project(soft_bottom_fraction_marine, fishing_rasters[[1]])

compareGeom(soft_bottom_aligned, fishing_rasters)

# Find how many hours of fishing per km of soft bottom sediment? 
hours_per_km_soft_bottom <- fishing_rasters / soft_bottom_aligned
```

```{r}
max(hours_per_km_soft_bottom[[7]])
```


```{r}
tmap_mode("view")

tm_shape(hours_per_km_soft_bottom[[7]]) +
  tm_raster(
    palette = "-viridis",
    title = "Destructive Fishing Hours (Year 7)",
    alpha = 0.9,
    style = "cont"
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(col = "white", lwd = 2) +
tm_layout(
    legend.outside = TRUE,
    frame = FALSE
)
```


# use quantile to 99% for plotting
```{r}
tmap_mode("view")

tm_shape(hours_per_km_soft_bottom[[7]]) +
  tm_raster(
    palette = "-viridis",
    style = "fixed",
    breaks = c(
                0,
                10,
                50,
                100,
                250,
                500,
                1000,
                2500,
                5000,
                10000,
                11000 ),
    title = "Hours per km Soft Bottom"
  ) +
tm_shape(ohi_regions_marine) +
  tm_borders(col = "white", lwd = 2) +
tm_layout(legend.outside = TRUE, frame = FALSE)

```

```{r}
histagram(hours_per_km_soft_bottom[[7]])
```


