---
title: 'OHI GoC 2024: Lasting Special Places (LSP)'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# Sentido de Pertenencia: Lasting Special Places

## List of coordinates from the Expert Working Group (EWG)

This subgoal's current status is based on whether there is a protection on the Lasting Special Place (LSP), and the condition is then determined by the effectiveness of that protection on the LSP.  For example, if the LSP is a specific island such as Isla Tiburón, so the island falls within a protected area, then its condition will be based on the management effectiveness determined by CONANP's SIMEC index of effectiveness (i-efectividad).

If they do not fall within a protected area, then the condition of protection will be determined accordingly.  Here is a table of the types of LSPs and their associated protections: <https://docs.google.com/spreadsheets/d/1RwNTzRZdBIDtzi7d1ceFxhNmVghN47NxTgrhZV8O2SM/edit?gid=1758421523#gid=1758421523>

So, first, we need to go through the list and separate into the type of LSP...