---
title: 'OHI GoC 2024: Lasting Special Places (LSP)'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# Sentido de Pertenencia: Lasting Special Places

## Merge all types of LSPs and determine a condition for each region

BUT maybe this should the be per-region values?

```{r}
# fishing sites
rgn_fishing_site_condition <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/lsp/v2025/output/rgn_fishing_sites_condition.csv")) %>% 
  mutate(rgn_id = str_replace_all(rgn_id, " ", "_"))

# archaeological sites
rgn_archaeological_site_condition <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/lsp/v2025/output/rgn_ewg_archaeological_sites_condition.csv")) %>% 
  mutate(rgn_id = str_replace_all(rgn_id, " ", "_"))

# protected area sites
rgn_protected_area_condition <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/lsp/v2025/output/rgn_protected_area_condition.csv")) %>%
  mutate(rgn_id = str_replace_all(rgn_id, " ", "_"))

# dive sites
rgn_dive_sites_condition <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/lsp/v2025/output/rgn_dive_sites_condition.csv"))%>% 
  mutate(rgn_id = str_replace_all(rgn_id, " ", "_"))

# special habitats (coral, coquina, seagrass, mangroves)
rgn_special_habitats_condition <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/lsp/v2025/output/rgn_special_habitats_condition.csv"))%>% 
  mutate(rgn_id = str_replace_all(rgn_id, " ", "_")) %>% 
  dplyr::select(-n_features)

# all other LSPs
other_sites_condition <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/lsp/v2025/output/rgn_final_other_protections_condition.csv"))%>% 
  mutate(rgn_id = str_replace_all(rgn_id, " ", "_"))

```


## Bind rows

```{r}
all_rgn_lsp_conditions <- bind_rows(rgn_fishing_site_condition, rgn_archaeological_site_condition, rgn_protected_area_condition, rgn_dive_sites_condition, rgn_special_habitats_condition, other_sites_condition)

lsp_current_status <- all_rgn_lsp_conditions %>% 
  group_by(rgn_id) %>% 
  summarize(
    current_status = mean(condition)
  ) %>% 
  ungroup()

```



