################################################################################

Erica Ferrer
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
# Visualization
library(ggplot2)
library(colorspace)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)
library(sf)


# No scientific notation:
options(scipen = 999)

# Set wd()
setwd("/home/ferrer/ohi_goc_prep/BD/")
```

```{r Load clean_names_lowercase function}
clean_names_lowercase <- function(x) {

  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")

  x %>%
    tolower() %>%
    trimws()
}
```

# STEP 1: Load input data ------------------------------

```{r Load HAB scores}
HAB_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/BD_Scores/BD_HAB_Scores/BD_HAB_Scores_df_Jul202026.csv")
# 405 obs., 11 vars.

# Clean HAB dataframe:
HAB_Scores<- HAB_Scores0 %>%
  rename(biome_score= HAB_score)
# 405 obs., 11 vars.
```

## Mangroves

```{r Load in MAN scores}
MAN_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_mangroves/MAN_outputs/mangrove_condition.csv")
# 9 obs., 3 vars.
# condition scores from 2020


# Clean MAN_Scores0:
MAN_Scores<- MAN_Scores0

colnames(MAN_Scores)

MAN_Scores<- MAN_Scores %>%
  rename(biome_score = condition,
         OHI_region = rgn_id) %>%
  mutate(
    OHI_region= clean_names_lowercase(OHI_region)
  )

MAN_Scores$biome_type<- c("mangrove_forest")
# 9 obs., 4 vars.

# Expand to all years and regions:
MAN_Scores_expanded <- expand_grid(
  OHI_region = paste0("region_", 1:9),
  year = 2019:2025
) %>%
  left_join(
    MAN_Scores %>%
      select(OHI_region, biome_score, biome_type),
    by = "OHI_region"
  )

MAN_Scores_expanded$biome_type<- c("mangrove_forest")
# 63 obs., 4 vars.
```

## Non-Mangrove Coastal Wetland

```{r Load in WET scores}
WET_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_wetlands/WET_outputs/wetland_condition.csv")
# 9 obs., 3 vars.
# condition scores from 2021


# Clean WET_Scores0:
WET_Scores<- WET_Scores0

colnames(WET_Scores)

WET_Scores<- WET_Scores %>%
  rename(biome_score = condition,
         OHI_region = rgn_id) %>%
  mutate(
    OHI_region= clean_names_lowercase(OHI_region),
    biome_score = biome_score * 100
  )

WET_Scores$biome_type<- c("coastal_wetland")
# 9 obs., 4 vars.

# Expand to all years and regions:
WET_Scores_expanded <- expand_grid(
  OHI_region = paste0("region_", 1:9),
  year = 2019:2025
) %>%
  left_join(
    WET_Scores %>%
      select(OHI_region, biome_score, biome_type),
    by = "OHI_region"
  )

WET_Scores_expanded$biome_type<- c("coastal_wetland")
# 63 obs., 4 vars.
```

## Seagrasses

```{r Load in SEA scores}
SEA_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_seagrass/SEA_outputs/seagrass_condition.csv")
# 9 obs., 3 vars.
# condition scores from 2025


# Clean SEA_Scores0:
SEA_Scores<- SEA_Scores0

colnames(SEA_Scores)

SEA_Scores<- SEA_Scores %>%
  rename(biome_score = condition,
         OHI_region = rgn_id) %>%
  mutate(
    OHI_region= clean_names_lowercase(OHI_region),
    biome_score = biome_score * 100
  )

SEA_Scores$biome_type<- c("seagrasses")
# 8 obs., 4 vars.

# Expand to all years and regions:
SEA_Scores_expanded <- expand_grid(
  OHI_region = paste0("region_", 1:9),
  year = 2019:2025
) %>%
  left_join(
    SEA_Scores %>%
      select(OHI_region, biome_score, biome_type),
    by = "OHI_region"
  )

SEA_Scores_expanded$biome_type<- c("seagrasses")
# 63 obs., 4 vars.
```


## Coral Reefs (CRL)

```{r Load in CRL scores}
CRL_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_corals/CRL_outputs/coral_current_status.csv")
# 2 obs., 3 vars.
# condition scores from 2023?


# Clean CRL_Scores0:
CRL_Scores<- CRL_Scores0

colnames(CRL_Scores)

CRL_Scores<- CRL_Scores %>%
  rename(biome_score = current_status,
         OHI_region = rgn_id) %>%
  mutate(
    OHI_region= clean_names_lowercase(OHI_region),
    biome_score = biome_score * 100
  )

CRL_Scores$biome_type<- c("coral_reefs")
# 2 obs., 4 vars.

# Expand to all years and regions:
CRL_Scores_expanded <- expand_grid(
  OHI_region = paste0("region_", 1:9),
  year = 2019:2025
) %>%
  left_join(
    CRL_Scores %>%
      select(OHI_region, biome_score, biome_type),
    by = "OHI_region"
  )

CRL_Scores_expanded$biome_type<- c("coral_reefs")
# 63 obs., 4 vars.
```


## Soft-Bottom Benthic Habitats (SOF)

```{r Load in SOF scores}
SOF_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_soft_bottom/SOF_outputs/sof_region_scores_per_year.csv")
# 171 obs., 7 vars.
# condition scores from 2007-2025


# Clean SOF_Scores0:
SOF_Scores<- SOF_Scores0

colnames(SOF_Scores)

SOF_Scores<- SOF_Scores %>%
  filter(year >= 2019, year <= 2025) %>%
  rename(biome_score = SOF_score) %>%
  mutate(
    OHI_region = paste0("region_", region_id),
  ) %>%
  select(year, OHI_region, biome_score)

SOF_Scores$biome_type<- c("soft_bottom_benthos")
# 63 obs., 8 vars.
```


## Rhodolith Beds (RHO)

```{r Load in RHO scores}
RHO_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_rhodolith_beds/RHO_outputs/rho_current_status.csv")
# 8 obs., 4 vars.
# NOTE TO SELF: RHO condition scores currently formatted incorrectly. I'll take scores from 2025.


# Clean RHO_Scores0:
RHO_Scores<- RHO_Scores0

colnames(RHO_Scores)

RHO_Scores<- RHO_Scores %>%
  rename(biome_score = X2025) %>%
  mutate(
    OHI_region = paste0("region_", region_id),
    biome_score = biome_score * 100
  ) %>%
  select(OHI_region, biome_score)

RHO_Scores$year<- c(2025)
RHO_Scores$biome_type<- c("rhodolith_beds")
# 8 obs., 4 vars.

# Expand to all years:
RHO_Scores_expanded <- expand_grid(
  OHI_region = paste0("region_", 1:9),
  year = 2019:2025
) %>%
  left_join(
    RHO_Scores %>%
      select(OHI_region, biome_score, biome_type),
    by = "OHI_region"
  )

RHO_Scores_expanded$biome_type<- c("rhodolith_beds")
# 63 obs., 4 vars.
```


## Rocky Reefs (ROK)

```{r Load in ROK scores}
ROK_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_rocky_reefs/ROK_outputs/ROK_Scores_1.0_df_Aug312026.csv")
# 280 obs., 10 vars.
# ROK condition scores from 1998-2025


# Clean ROK_Scores0:
ROK_Scores<- ROK_Scores0

colnames(ROK_Scores)

ROK_Scores<- ROK_Scores %>%
  filter(year >= 2019, year <= 2025) %>%
  rename(biome_score = ROK_score_final) %>%
  select(OHI_region, year, biome_score)

ROK_Scores$biome_type<- c("rocky_reefs")
# 70 obs., 4 vars.
```


## Open Ocean (OCE)

```{r Load in OCE scores}
OCE_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/_habitats/HAB_open_ocean/OCE_outputs/OCE_Scores_1.0_df_Sep082026.csv")
# 9 obs., 3 vars.
# OCE condition scores from ~2024


# Clean OCE_Scores0:
OCE_Scores<- OCE_Scores0

colnames(OCE_Scores)

OCE_Scores<- OCE_Scores %>%
  rename(biome_score = OCE_score)

OCE_Scores$biome_type<- c("open_ocean")
# 9 obs., 4 vars.

# Expand to all years:
OCE_Scores_expanded <- expand_grid(
  OHI_region = paste0("region_", 1:9),
  year = 2019:2025
) %>%
  left_join(
    OCE_Scores %>%
      select(OHI_region, biome_score, biome_type),
    by = "OHI_region"
  )

OCE_Scores_expanded$biome_type<- c("open_ocean")
# 63 obs., 4 vars.
```


# STEP 2: Compute regional BD scores ------------------------------

```{r Combine OCE_Scores0 scores}
Biomes_Combined0 <- bind_rows(MAN_Scores_expanded, WET_Scores_expanded, SEA_Scores_expanded, CRL_Scores_expanded, SOF_Scores, RHO_Scores_expanded, ROK_Scores, OCE_Scores_expanded)
# 511 obs., 4 vars.

table(Biomes_Combined0$biome_type)
    # coastal_wetland         coral_reefs     mangrove_forest          open_ocean      rhodolith_beds         rocky_reefs 
    #              63                  63                  63                  63                  63                  70 
    #      seagrasses soft_bottom_benthos 
    #              63                  63 
# Great!
```

```{r Compute BD_score}
colnames(Biomes_Combined0)

BD_Scores0 <- Biomes_Combined0 %>%
  select(year, OHI_region, biome_type, biome_score) %>%
  group_by(year, OHI_region) %>%
  summarize(
    BD_score = mean(biome_score, na.rm = TRUE),
    biome_types = paste(unique(biome_type), collapse = ", "),
    .groups = "drop"
  )

# 70 obs., 4 vars.

table(BD_Scores0$OHI_region)

BD_Scores<- BD_Scores0 %>%
  filter(!OHI_region== c("global average"))

# 63 obs., 4 vars.
```

# SAVE BD_Scores ------------------------------

```{r Save BD_Scores}
write.csv(BD_Scores, 
          "/home/ferrer/ohi_goc_prep/BD/v2026/BD_Scores_1.0/BD_Scores_1.0_df_Sep082026.csv", 
          row.names = FALSE)
# 63 obs., 4 vars.
```

```{r Sanity check final BD_Scores}
colnames(BD_Scores)

summary(BD_Scores$BD_score)

# FINAL BD Scores 1.0 (Sep 8 2026):
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 63.67   68.18   74.92   72.95   76.35   79.96 

# AFTER RHO and SOF (Aug 11):
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 64.80   73.44   77.20   77.12   82.29   87.63 

# AFTER rocky reefs (Aug 5):
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 61.37   65.30   70.18   72.00   78.31   86.50 

# BEFORE rocky reefs (Aug 5):
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 61.37   67.68   72.35   73.79   80.50   86.50 

# Year 2024 mean for BD scores:
mean(BD_Scores$BD_score[BD_Scores$year == 2024], na.rm = TRUE)
# 73
```

# PLOT BD_Scores  ------------------------------
```{r Load in BD_Scores as needed}
BD_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/v2026/BD_Scores_1.0/BD_Scores_1.0_df_Sep082026.csv")
# 63 obs., 4 vars.

BD_Scores<- BD_Scores0
```

```{r Region key}
Region_Key0<- read.csv("/home/ferrer/ohi_goc_prep/FP/v2026/CONAPESCA_Keys/Spatial_Keys/RegionKey_FINAL_May262026.csv")

colnames(Region_Key0)

Region_Key<- Region_Key0 %>%
  select(OHI_region= OHI_region_est, OHI_region_name) %>%
  distinct()
```

```{r Merge Region_Key to BD_Scores}
BD_Scores<- BD_Scores %>%
  left_join(Region_Key, 
            by = "OHI_region")

# Make sure to order the regions:
Region_order <- c(
  "Western Upper Gulf",
  "Western Midriff Islands",
  "Western Central Gulf",
  "Western Southern Gulf",
  "Eastern Upper Gulf",
  "Eastern Midriff Islands",
  "Southern Sonora Coast",
  "Sinaloa Coast",
  "Southeastern Gulf"
)

BD_Scores <- BD_Scores %>%
  mutate(
    OHI_region_name = factor(
      OHI_region_name,
      levels = Region_order
    )
  )
```

```{r Plot BD_Scores}
unique(BD_Scores$OHI_region_name)

Region_colors<- c(
  "Western Upper Gulf" = "#C03729",
  "Western Midriff Islands" = "#E68C7C",
  "Western Central Gulf" = "#FC8F24",
  "Western Southern Gulf" = "#dcaa38",
  "Eastern Upper Gulf" = "#cbd2a0",
  "Eastern Midriff Islands" = "#98a25a",
  "Southern Sonora Coast" = "#747428",
  "Sinaloa Coast" = "#627391",
  "Southeastern Gulf" = "#8d61a9")

BD_Scores_OverTime<- BD_Scores %>%
  filter(!is.na(OHI_region_name)) %>%
  
  ggplot(aes(
    x = year,
    y = BD_score,
    color = OHI_region_name
  )) +
  
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  
  facet_wrap(~ OHI_region_name, scales = "fixed") +
  
  labs(
    title = "BD Scores by Region",
    subtitle = "Includes MAN, WET, SEA, CRL, SOF, RHO, ROK, and OCE scores",
    caption = "updated: Sep 8 2026",
    y = "BD Score (from 0 to 100)",
    x = "Year"
  ) +
  
  geom_hline(yintercept = 100, linetype = "dashed", color = "grey50") +
  
  ylim(0, 101) +
  
  scale_color_manual(values = Region_colors) +
  
  theme_bw(base_size = 14) +
  theme(
    legend.position = "none",
    strip.text = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

BD_Scores_OverTime
```

```{r Save as PNG}
ggsave(
  filename = sprintf("/home/ferrer/ohi_goc_prep/BD/v2026/BD_Scores_1.0/BD_Scores_1.0_plot_Sep082026.png"),
  plot = BD_Scores_OverTime,
  width = 12,
  height = 12,
  dpi = 300
)
```


## PLOT as map:

```{r Load in OHI region map}
# Read in OHI region boundaries
ohi_regions <- st_read("/home/ferrer/ohi_goc_prep/spatial/ohi_regions/goc_ohi_rgns.shp") %>%
  st_make_valid()

colnames(ohi_regions)

# Separate land from marine regions:
ohi_regions_marine <- ohi_regions %>%
  filter(location == "marine") %>%
  mutate(
    OHI_region= clean_names_lowercase(rgn_id)
  ) %>%
  select(OHI_region, ecorgn, geometry)

ohi_regions_land <- ohi_regions %>%
  filter(location == "land") %>%
  mutate(
        OHI_region= clean_names_lowercase(rgn_id)
  )
```

```{r Plot scores per region in 2024}
# Filter BD_Scores to 2024:
BD_Scores_2024 <- BD_Scores %>%
  filter(year == 2024) %>%
  select(OHI_region, BD_score, OHI_region_name)

# Join BD_Scores_2024 to the marine spatial regions:
BD_map_2024 <- ohi_regions_marine %>%
  left_join(BD_Scores_2024, by = "OHI_region")

# Plot:

# Plot
BD_Scores_2024_map<- ggplot() +
  
  # Land background
  geom_sf(
    data = ohi_regions_land,
    fill = "grey75",
    color = "grey50",
    linewidth = 0.3
  ) +
  
  # Marine regions colored by BD score
  geom_sf(
    data = BD_map_2024,
    aes(fill = BD_score),
    color = "white",
    linewidth = 0.4
  ) +
  
  # Red → yellow → green scale
  scale_fill_gradientn(
    name = "BD Score",
    colours = c("#B2182B", "#FEE08B", "#1A9850"),
    values = c(0, 0.5, 1),
    limits = c(60, 85),
    breaks = seq(60, 85, 5)
  ) +
  
  
  labs(
    title = "Biodiversity Scores by Region, 2024"
  ) +
  
  labs(
    title = "BD Scores by Region, 2024-2025",
    subtitle= "regions are color-coded by score", 
    caption = "updated: Sep 9 2026"
  ) +
  
  theme_bw(base_size = 14) +
  theme(
    legend.position = "right",
    strip.text = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

BD_Scores_2024_map
```

```{r Save BD_Scores_2024_map}
ggsave(
  plot = BD_Scores_2024_map,
  filename = "/home/ferrer/ohi_goc_prep/BD/v2026/BD_Scores_1.0/BD_Scores_1.0_2024_map_Sep082026.png",
    width = 12,
    height = 12,
    dpi = 300
  )
```

