################################################################################

Erica Ferrer
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
# Visualization
library(ggplot2)
library(colorspace)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/FP/")
```

```{r Load clean_names_lowercase function}
clean_names_lowercase <- function(x) {

  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")

  x %>%
    tolower() %>%
    trimws()
}
```

# STEP 1: Load in AFO Scores

# STEP 2: Load in LCA Scores

# STEP 3: Calculate AO Scores as 50-50 weighted of AFO_Scores and LCA_Scores
```{r Merge AFO_Scores and LCA_Scores for AO_df}

```

```{r Calculate AO_Scores}

```

```{r Save AO_Scores}

```

# STEP 4: Plot AO_Scores
