---
title: "OHI GOC final scores first draft (Sep 2026)"
author: "Erica Ferrer"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(plotly)
library(zoo)

final_output_dir <- "/home/shares/ohi/OHI_GOC/goal_prep/final_cs_scores"
```


## clean_waters: AFO

```{r}
AO_Scores <- read_csv(here::here("/home/ferrer/ohi_goc_prep/AO/v2026/AO_Scores/AFO_Scores/AFO_Scores_1.0_df_Jun152026.csv"))

  select(rgn_id, year, current_status = AO) %>% 
  mutate(goal = "access_opporunities")

write_csv(CW_Scores, here::here(final_output_dir, "CW_Scores_1.0_df_Sep112026.csv"))
```


## clean_waters: CW

```{r}
CW_Scores <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/cw/v2025/cw_current_status_arithmetic.csv")) %>% 
  select(rgn_id, year, CW_score = CW) %>% 
  mutate(goal = "clean_waters")

write_csv(CW_Scores, here::here(final_output_dir, "CW_Scores_1.0_df_Sep112026.csv"))
```


## livelihoods_economies: LE

```{r}
LE_Scores <- read_csv(here::here(
    "/home/shares/ohi/OHI_GOC/goal_prep/le",
    "final_le_current_status_2019ref_informality.csv"
  )) %>% 
  select(rgn_id, year = ano_censal, LE_score = final_le_current_status_rgn) %>% 
  mutate(goal = "livelihoods_economies")


LE_Scores_gf <- LE_Scores %>% 
  complete(rgn_id, year = full_seq(2003:2025, 1)) %>%  # expand to every year 2003-2025
  arrange(rgn_id, year) %>% 
  group_by(rgn_id) %>% 
  mutate(current_status = na.approx(current_status, x = year, na.rm = FALSE, rule = 2)) %>% 
  ungroup() %>% 
  mutate(goal = "livelihoods_economies")

write_csv(LE_Scores_gf, here::here(final_output_dir, "LE_Scores_1.0_df_Sep112026.csv"))
```


## tourism_recreation: TR 

```{r}
TR_Scores <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/tr/v2025/output/tr_current_status_final_083126.csv")
) %>% 
  rename(TR_score = tr_current_status) %>% 
  mutate(goal = "tourism_recreation")

write_csv(TR_Scores, here::here(final_output_dir, "TR_Scores_1.0_df_Sep112026.csv"))
```


## sense_of_place: SP

```{r}
SP_Scores <- read_csv(here::here(
    "/home/shares/ohi/OHI_GOC/goal_prep/sp",
    "sp_current_status_noCCE.csv"
  )) %>% 
  mutate(goal = "sense_of_place")

write_csv(SP_Scores, here::here(final_output_dir, "SP_Scores_1.0_df_Sep112026.csv"))
```


# PLOT

```{r}
library(ggplot2)
library(dplyr)

library(ggplot2)

dat <- data.frame(
  indicator = c(
    "Natural Products",
    "Artisanal Fishing\nOpportunities",
    "Mariculture",
    "Fisheries",
    "Species",
    "Habitats",
    "Clean Waters",
    "Special Places",
    "Iconic Lasting\nSpecies",
    "Economies",
    "Livelihoods",
    "Tourism &\nRecreation",
    "Coastal\nProtection",
    "Carbon Storage"
  ),

  value = c(
    2.25, 2.30, 1.15, 1.75,
    1.85, 2.05, 2.00, 1.55,
    1.45, 1.95, 1.65, 1.35,
    2.10, 2.30
  ),

  group = c(
    "Food Provision",
    "Food Provision",
    "Food Provision",
    "Food Provision",
    "Biodiversity",
    "Biodiversity",
    "Biodiversity",
    "Sense of Place",
    "Sense of Place",
    "Livelihoods & Economies",
    "Livelihoods & Economies",
    "Livelihoods & Economies",
    "Coastal Benefits",
    "Coastal Benefits"
  )
)

# ---------------------------------------------------------
# 1. Geometry
# ---------------------------------------------------------

dat$x <- seq_len(nrow(dat))

inner <- 1
label_radius <- 2.75

# Calculate angle for each slice
n <- nrow(dat)

dat$angle <- 90 - 360 * (dat$x - 0.5) / n

# Flip labels on the left side so they remain readable
dat$label_angle <- ifelse(
  dat$angle < -90,
  dat$angle + 180,
  dat$angle
)

# Horizontal justification
dat$hjust <- ifelse(
  dat$angle < -90,
  1,
  0
)


# ---------------------------------------------------------
# 2. Plot
# ---------------------------------------------------------

p <- ggplot(dat) +

  # -------------------------------------------------------
  # Circular grid lines
  # -------------------------------------------------------

  geom_hline(
    yintercept = c(1, 1.5, 2, 2.5, 3),
    colour = "grey85",
    linewidth = 0.5
  ) +

  # -------------------------------------------------------
  # Bars
  # -------------------------------------------------------

  geom_rect(
    aes(
      xmin = x - 0.48,
      xmax = x + 0.48,
      ymin = inner,
      ymax = value,
      fill = indicator
    ),
    colour = "grey25",
    linewidth = 0.6
  ) +

  # -------------------------------------------------------
  # Indicator labels around the outside
  # -------------------------------------------------------

  geom_text(
    aes(
      x = x,
      y = label_radius,
      label = indicator,
      angle = label_angle,
      hjust = hjust
    ),
    size = 3.2,
    lineheight = 0.9
  ) +

  # -------------------------------------------------------
  # Number in the middle
  # -------------------------------------------------------

  annotate(
    "text",
    x = 1,
    y = 0,
    label = "72",
    size = 13,
    colour = "grey20"
  ) +

  # -------------------------------------------------------
  # Polar transformation
  # -------------------------------------------------------

  coord_polar(
    theta = "x",
    start = -pi / 2,
    clip = "off"
  ) +

  # -------------------------------------------------------
  # Colors
  # -------------------------------------------------------

  scale_fill_manual(
    values = c(
      "#C96FB2",
      "#C06BC3",
      "#D5C0D9",
      "#8C82C5",
      "#5DA4C5",
      "#48B2B5",
      "#5BB56B",
      "#8DC66A",
      "#B5C65B",
      "#E5CA69",
      "#F3B85D",
      "#F7A73F",
      "#F58A54",
      "#D9667E"
    )
  ) +

  # -------------------------------------------------------
  # Radius
  # -------------------------------------------------------

  scale_y_continuous(
    limits = c(0, 3.45),
    expand = c(0, 0)
  ) +

  # -------------------------------------------------------
  # Theme
  # -------------------------------------------------------

  theme_void() +

  theme(
    legend.position = "none",
    plot.margin = margin(40, 100, 60, 100)
  )

p


```