---
title: 'OHI GoC 2026: merge all goal scores'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor:
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options:
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(here)
library(plotly)
library(zoo)

final_output_dir <- "/home/shares/ohi/OHI_GOC/goal_prep/final_cs_scores"
```


## TR 

```{r}
tr_cs <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/tr/v2025/output/tr_current_status_final_083126.csv")
) %>% 
  rename(current_status = tr_current_status) %>% 
  mutate(goal = "tourism_recreation")

write_csv(tr_cs, here::here(final_output_dir, "TR_Scores_1.0_df_091126.csv"))
```


## SP

```{r}
sp_cs <- read_csv(here::here(
    "/home/shares/ohi/OHI_GOC/goal_prep/sp",
    "sp_current_status_noCCE.csv"
  )) %>% 
  mutate(goal = "sense_of_place")

write_csv(sp_cs, here::here(final_output_dir, "SP_Scores_1.0_df_091126.csv"))
```


## LE

```{r}
le_cs <- read_csv(here::here(
    "/home/shares/ohi/OHI_GOC/goal_prep/le",
    "final_le_current_status_2019ref_informality.csv"
  )) %>% 
  select(rgn_id, year = ano_censal, current_status = final_le_current_status_rgn) %>% 
  mutate(goal = "livelihoods_economies")


le_cs_gf <- le_cs %>% 
  complete(rgn_id, year = full_seq(2003:2025, 1)) %>%  # expand to every year 2003-2025
  arrange(rgn_id, year) %>% 
  group_by(rgn_id) %>% 
  mutate(current_status = na.approx(current_status, x = year, na.rm = FALSE, rule = 2)) %>% 
  ungroup() %>% 
  mutate(goal = "livelihoods_economies")

write_csv(le_cs_gf, here::here(final_output_dir, "LE_Scores_1.0_df_091126.csv"))
```

## CW

```{r}
cw_cs <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/cw/v2025/cw_current_status_arithmetic.csv")) %>% 
  select(rgn_id, year, current_status = CW) %>% 
  mutate(goal = "clean_waters")

write_csv(cw_cs, here::here(final_output_dir, "CW_Scores_1.0_df_091126.csv"))
```


