---
title: 'OHI GoC 2025: JC CONAPESCA cleaned data exploration'
output: html_document
date: "2025-3-6"
editor_options: 
  chunk_output_type: console
---

# Juan Carlos: clean CONAPESCA data

```{r}
library(tidyverse)
library(here)
library(janitor)
library(mapview)
library(sf)
```


```{r}
mex_monthly_landings_by_vessel <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_monthly_landings_by_vessel.rds")) # no landing site

mex_monthly_landings_by_landing_site <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_monthly_landings_by_landing_site.rds")) # no permit or vessel identifier, only landings/value, date, and landing site


mex_monthly_landings_by_eu <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_monthly_landings_by_eu.rds")) # only by eu_rnpa, not landing site or vessel ID

mex_monthly_landings_by_eu <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_monthly_landings_by_eu.rds")) # only by eu_rnpa, not landing site or vessel ID

mex_landings_2000_present <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_landings_2000_present.rds"))

length(unique(mex_landings_2000_present$landing_site_key))
unique(mex_landings_2000_present$landing_site_key)

mex_landings_2000_present_25E <-mex_landings_2000_present %>% 
  filter(landing_site_key %in% "25E") %>% 
  filter(year %in% "2000")


mex_conapesca_apertura_2018_present <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_conapesca_apertura_2018_present.rds")) 

unique(mex_conapesca_apertura_2018_present$fleet)
```


## ECO: Large scale

```{r}
mex_conapesca_apertura_2018_present <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_conapesca_apertura_2018_present.rds")) 

mex_conapesca_apertura_2018_present_largescale <-  mex_conapesca_apertura_2018_present %>% 
  filter(fleet %in% "large_scale")


unique(mex_conapesca_apertura_2018_present_largescale$state)

#  [1] "BAJA CALIFORNIA SUR" "CAMPECHE"           
#  [3] "YUCATAN"             "SONORA"             
#  [5] "SINALOA"             "BAJA CALIFORNIA"    
#  [7] "TABASCO"             "QUINTANA ROO"       
#  [9] "TAMAULIPAS"          "VERACRUZ"           
# [11] "COLIMA"              "OAXACA"             
# [13] "NAYARIT"             "CHIAPAS"

state_apertura_2018_present_largescale <- mex_conapesca_apertura_2018_present_largescale %>% 
  filter(state %in% c("BAJA CALIFORNIA SUR","SONORA","SINALOA","BAJA CALIFORNIA","NAYARIT","JALISCO"))


## LS = largescale: determining which of the office names in the GoC are Gulf-side
unique(state_apertura_2018_present_largescale$office_name)

#  [1] "ENSENADA"    N         "SAN FELIPE"         Y
#  [3] "LOS MOCHIS"   Y        "MAZATLAN"  Y
#  [5] "GUAYMAS"    Y          "PUERTO PEÑASCO" Y
#  [7] "TOPOLOBAMPO" Y         "HUATABAMPO"    Y
#  [9] "SAN CARLOS"  Y         "CRUZ DE HUANACAXTLE" # puerto vallarta
# [11] "CD. CONSTITUCION" # more pacific-side     "SAN BLAS"   Y Nayarit
# [13] "PUERTO LIBERTAD" Y sonora      "MEXICALI"  N
# [15] "LA PAZ"   Y            "VILLA DE JESUS MARIA" N pacific
# [17] "SANTA ROSALIA"    Y    "BAHIA ASUNCION"  N pacific
# [19] "CABO SAN LUCAS"       "SAN QUINTIN"  N pacific
# [21] "EL ROSARIO"    Y, sinaloa      "GUASAVE"   Y, sinaloa
# [23] "PUNTA ABREOJOS" N, pacific-side      "GUERRERO NEGRO"   N, pacific
# [25] "TIJUANA"    N          "BAHIA KINO"    Y
# [27] "NAVOLATO"    Y         "CULIACAN"    Y
# [29] "CD. OBREGON"  Y (maybe)        "LA REFORMA"  Y
# [31] "HERMOSILLO" Y           "BAHIA TORTUGAS"     N, pacific side
# [33] "TEPIC"   Y             "ISLA CEDROS" N, pacific-side
# [35] "GOLFO DE SANTA CLARA" Y  "PUERTO PE\xd1ASCO"  Y

goc_apertura_2018_present_largescale <- state_apertura_2018_present_largescale %>% 
  filter(!office_name %in% c("ENSENADA","CD. CONSTITUCION","MEXICALI","VILLA DE JESUS MARIA","BAHIA ASUNCION","SAN QUINTIN","GUERRERO NEGRO", "TIJUANA","BAHIA TORTUGAS","ISLA CEDROS")) 

unique(goc_apertura_2018_present_largescale$landing_site)

#  [1] "SAN FELIPE"   Y           "TOPOLOBAMPO"   Y,          
#  [3] "MAZATLAN"   Y             "PARAJE NUEVO"           
#  [5] "GUAYMAS"       Y          "PUERTO PEÑASCO"  Y       
#  [7] "YAVAROS"      Y, sonora           "SAN CARLOS"  Y           
#  [9] "CRUZ DE HUANACAXTLE"     "SAN BLAS"       Y        
# [11] "PUERTO VALLARTA"   Y      "ENSENADA"    N           
# [13] "LA PAZ"  Y                "PTO ADOLFO LOPEZ MATEOS" N
# [15] "PICHILINGUE"  Y, by la paz          "SANTA ROSALIA"  Y, by mulegé        
# [17] "BAHIA ASUNCION"   N, pacific-side       "SAN LUCAS"   Y           
# [19] "EL SAUZAL"  N, pacific-side             "MANZANILLO" N, in colima?            
# [21] "PUERTO ANGEL"    UNSURE: might be in Oaxaca         "PUNTA ABREOJOS"  N, pacific-side       
# [23] "GUERRERO NEGRO"   N, pacific side       "BAHIA DE KINO"    Y      
# [25] "LA CORTINA"   Unsure. N           "EL CASTILLO"    UNSURE        
# [27] "LA REFORMA"    Y          "BAHIA TORTUGAS"  N, pacific side      
# [29] "MATANCITAS" N, barely pacific side             "TEACAPAN, SIN." Y
# [31] "SANCHEZ MAGALLANES" N... Tabasco??     "PUERTO DE ABRIGO" N, Yucatan!      
# [33] "ISLA CEDROS" N, pacific side            "MOLINO VIEJO"   N, pacific-side        
# [35] "SALINA CRUZ"  N, coastal Oaxaca           "PUERTO MADERO"   N, near Tapachula.. very far       
# [37] "CHIAPAS"   N              "ROSALILLITA"   N, pacific side         
# [39] "PUERTO PE\xd1ASCO" Y      "GOLFO DE SANTA CLARA"   Y
# [41] "CHETUMAL" UNSURE: likely Quintana Roo, but could be in Bahia Kino Sonora...               "PUERTO ALCATRAZ" N, pacific side       
# [43] "PUERTO EXTRANJERO"  UNSURE     "PUERTO JUAREZ"  UNSURE, N 


# filter so that both the fishing offices and landing sites are in the GoC:
only_goc_apertura_2018_present_LS <- goc_apertura_2018_present_largescale %>% 
  filter(!landing_site %in% c(
  "ENSENADA",            # N
  "PTO ADOLFO LOPEZ MATEOS", # N
  "BAHIA ASUNCION",     # N, pacific-side 
  "EL SAUZAL",          # N, pacific-side 
  "MANZANILLO",         # N, in colima? 
  "PUERTO ANGEL",       # UNSURE: might be in Oaxaca
  "PUNTA ABREOJOS",     # N, pacific-side 
  "GUERRERO NEGRO",     # N, pacific side 
  "LA CORTINA",         # Unsure. N 
  "EL CASTILLO",        # UNSURE
  "MATANCITAS",         # N, barely pacific side
  "SANCHEZ MAGALLANES", # N... Tabasco??
  "PUERTO DE ABRIGO",   # N, Yucatan!
  "ISLA CEDROS",        # N, pacific side
  "MOLINO VIEJO",       # N, pacific-side
  "SALINA CRUZ",        # N, coastal Oaxaca
  "PUERTO MADERO",      # N, near Tapachula.. very far
  "CHIAPAS",            # N
  "ROSALILLITA",        # N, pacific side
  "CHETUMAL",           # UNSURE: likely Quintana Roo, but could be in Bahia Kino Sonora...
  "PUERTO ALCATRAZ",    # N, pacific side
  "PUERTO EXTRANJERO",  # UNSURE
  "PUERTO JUAREZ" ,      # UNSURE, N
  "BAHIA TORTUGAS"
))

unique(only_goc_apertura_2018_present_LS$fishing_site_name)
# [1] "ALTAMAR"                       
# [2] "PRESA PLUTARCO ELIAS CALLES"   
# [3] "PRESA SAN JERONIMO( LUMBRERAS)"
# [4] "PRESA ABELARDO L RODRIGUEZ" 

unique(only_goc_apertura_2018_present_LS$fishing_zone_type)
# [1] NA
```


```{r}
## join with OHI rgns
goc_poly <- st_read(here("spatial/ohi_regions","goc_ohi_rgns.shp"))
st_crs(goc_poly) # not WGS84: Mexico ITRF2008 / LCC
mapview(goc_poly)

only_goc_apertura_2018_present_LS_prepjoin <- only_goc_apertura_2018_present_LS %>% 
  mutate(estado = case_when(
    state %in% "BAJA CALIFORNIA SUR" ~ "Baja_California_Sur",
    state %in% "BAJA CALIFORNIA"~ "Baja_California",
    state %in% "SONORA" ~ "Sonora",
    state %in% "SINALOA" ~ "Sinaloa",
    # state %in% "JALISCO" ~ "Jalisco", ### not needed: lost Jalisco when filtering for large scale.
    state %in% "NAYARIT" ~ "Nayarit",
    TRUE ~ ""  # default case for any unmatched states
  ))

ohi_rgns_LS <- left_join(
  goc_poly,
  only_goc_apertura_2018_present_LS_prepjoin,
  by = "estado",
  relationship = "many-to-many" # anticipated, as because of rgn_id, there are multiple regions per state.  For now, lets give the same information to both Region_1 and Region_2. LATER, we will want to classify fishing sites by rgn_id, to make it more accurate. 
)

st_write(ohi_rgns_LS, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","ohi_rgns_LS.shp"))

```

### Revenue largescale

```{r}
## assume revenue is the total value for each year, for all stocks
rev_LS <- ohi_rgns_LS %>% 
  group_by(rgn_id, year_cut) %>% 
  summarise(revenue = sum(value))
```


## ECO: small scale

SS = small scale

```{r}
#############
state_conapesca_apertura_2018_present_SS <- mex_conapesca_apertura_2018_present %>%
  filter(fleet %in% "small_scale") %>% 
  filter(state %in% c("BAJA CALIFORNIA SUR","SONORA","SINALOA","BAJA CALIFORNIA","NAYARIT","JALISCO"))

## determining which of the office names in the GoC are Gulf-side
unique(state_conapesca_apertura_2018_present_SS$office_name)

```


# Restarting using mex_landings_2000_present.rds

## ECO: both (2000 - 2025)

```{r}
library(data.table)

## use either fread or feather/arrow because readRDS is taking a reallllly long time to load and there are 12,153,879 observations of 19 variables.
mex_landings_2000_present_dt <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_landings_2000_present.rds")) %>% as.data.table()

state_mex_landings_2000_present_both <- mex_landings_2000_present_dt[
    state %in% c("BAJA CALIFORNIA SUR","SONORA","SINALOA","BAJA CALIFORNIA","NAYARIT","JALISCO")
]

### check and see what landing sites are available and which are in the GoC (there are sooo many!! Come back to this)
unique(state_mex_landings_2000_present_both$landing_site)

```


## ECO: large scale (2018 - 2025)

```{r}
library(data.table)

## use either fread or feather/arrow because readRDS is taking a reallllly long time to load and there are 12,153,879 observations of 19 variables.
mex_landings_2000_present_dt <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_landings_2000_present.rds")) %>% as.data.table()

state_mex_landings_2000_present_LS <- mex_landings_2000_present_dt[
  fleet == "large_scale" & 
    state %in% c("BAJA CALIFORNIA SUR","SONORA","SINALOA","BAJA CALIFORNIA","NAYARIT","JALISCO")
]

### check and see what landing sites are available and which are in the GoC
unique(state_mex_landings_2000_present_LS$landing_site)

#  [1] "SAN FELIPE"   Y           "TOPOLOBAMPO"   Y,          
#  [3] "MAZATLAN"   Y             "PARAJE NUEVO"           
#  [5] "GUAYMAS"       Y          "PUERTO PEÑASCO"  Y       
#  [7] "YAVAROS"      Y, sonora           "SAN CARLOS"  Y           
#  [9] "CRUZ DE HUANACAXTLE"     "SAN BLAS"       Y        
# [11] "PUERTO VALLARTA"   Y      "ENSENADA"    N           
# [13] "LA PAZ"  Y                "PTO ADOLFO LOPEZ MATEOS" N
# [15] "PICHILINGUE"  Y, by la paz          "SANTA ROSALIA"  Y, by mulegé        
# [17] "BAHIA ASUNCION"   N, pacific-side       "SAN LUCAS"   Y           
# [19] "EL SAUZAL"  N, pacific-side             "MANZANILLO" N, in colima?            
# [21] "PUERTO ANGEL"    UNSURE: might be in Oaxaca         "PUNTA ABREOJOS"  N, pacific-side       
# [23] "GUERRERO NEGRO"   N, pacific side       "BAHIA DE KINO"    Y      
# [25] "LA CORTINA"   Unsure. N           "EL CASTILLO"    UNSURE        
# [27] "LA REFORMA"    Y          "BAHIA TORTUGAS"  N, pacific side      
# [29] "MATANCITAS" N, barely pacific side             "TEACAPAN, SIN." Y
# [31] "SANCHEZ MAGALLANES" N... Tabasco??     "PUERTO DE ABRIGO" N, Yucatan!      
# [33] "ISLA CEDROS" N, pacific side            "MOLINO VIEJO"   N, pacific-side        
# [35] "SALINA CRUZ"  N, coastal Oaxaca           "PUERTO MADERO"   N, near Tapachula.. very far       
# [37] "CHIAPAS"   N              "ROSALILLITA"   N, pacific side         
# [39] "PUERTO PE\xd1ASCO" Y      "GOLFO DE SANTA CLARA"   Y
# [41] "CHETUMAL" UNSURE: likely Quintana Roo, but could be in Bahia Kino Sonora...               "PUERTO ALCATRAZ" N, pacific side       
# [43] "PUERTO EXTRANJERO"  UNSURE     "PUERTO JUAREZ"  UNSURE, N
```


```{r}
# filter so that the landing sites are in the GoC
## NOTE: did not filter office_name to be wihtin the GoC, since it can all be submitted electronically and is not likely representative of where landings were caught. See JC email (<https://github.com/OHI-GOC/OHI_GOC_issues/issues/28#issuecomment-3357184877>)
goc_mex_landings_2000_present_LS <- state_mex_landings_2000_present_LS[
  !landing_site %in% c(
  "ENSENADA",            # N
  "PTO ADOLFO LOPEZ MATEOS", # N
  "BAHIA ASUNCION",     # N, pacific-side 
  "EL SAUZAL",          # N, pacific-side 
  "MANZANILLO",         # N, in colima? 
  "PUERTO ANGEL",       # UNSURE: might be in Oaxaca
  "PUNTA ABREOJOS",     # N, pacific-side 
  "GUERRERO NEGRO",     # N, pacific side 
  "LA CORTINA",         # Unsure. N 
  "EL CASTILLO",        # UNSURE
  "MATANCITAS",         # N, barely pacific side
  "SANCHEZ MAGALLANES", # N... Tabasco??
  "PUERTO DE ABRIGO",   # N, Yucatan!
  "ISLA CEDROS",        # N, pacific side
  "MOLINO VIEJO",       # N, pacific-side
  "SALINA CRUZ",        # N, coastal Oaxaca
  "PUERTO MADERO",      # N, near Tapachula.. very far
  "CHIAPAS",            # N
  "ROSALILLITA",        # N, pacific side
  "CHETUMAL",           # UNSURE: likely Quintana Roo, but could be in Bahia Kino Sonora...
  "PUERTO ALCATRAZ",    # N, pacific side
  "PUERTO EXTRANJERO",  # UNSURE
  "PUERTO JUAREZ" ,      # UNSURE, N
  "BAHIA TORTUGAS",     # N, pacific-side
  "PARAJE NUEVO"        # N, in Guerrero?
  )
]
```

```{r}
## now, join with ohi regions...
goc_poly <- st_read(here("spatial/ohi_regions","goc_ohi_rgns.shp"))
st_crs(goc_poly) # not WGS84: Mexico ITRF2008 / LCC
mapview(goc_poly)

goc_rgns_df <- goc_poly %>% 
  st_drop_geometry()

goc_mex_landings_2000_present_LS_prepjoin <- goc_mex_landings_2000_present_LS %>% 
  mutate(estado = case_when(
    state %in% "BAJA CALIFORNIA SUR" ~ "Baja_California_Sur",
    state %in% "BAJA CALIFORNIA"~ "Baja_California",
    state %in% "SONORA" ~ "Sonora",
    state %in% "SINALOA" ~ "Sinaloa",
    state %in% "JALISCO" ~ "Jalisco",
    state %in% "NAYARIT" ~ "Nayarit",
    TRUE ~ ""  # default case for any unmatched states
  ))

write_csv(goc_mex_landings_2000_present_LS_prepjoin, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","goc_mex_landings_2000_present_LS_prepjoin.csv"))


ohi_rgns_LS <- left_join(
  goc_rgns_df,
  goc_mex_landings_2000_present_LS_prepjoin,
  by = "estado",
  relationship = "many-to-many" # anticipated, as because of rgn_id, there are multiple regions per state.  For now, lets give the same information to both Region_1 and Region_2. LATER, we will want to classify fishing sites by rgn_id, to make it more accurate. 
)

unique(ohi_rgns_LS$landing_site) ## looks good, all GoC. it is fine if office name is outside of the GoC, not representative (just where record reciepts are submitted)
```

```{r}
## assume revenue is the total value for each year, for all stocks
rev_by_state_LS <- ohi_rgns_LS %>% 
  group_by(estado, year) %>% 
  summarise(revenue = sum(value))

rev_by_state_LS_sf <- full_join(goc_poly, rev_by_state_LS, by = "estado")

rev_by_state_LS_2024 <- rev_by_state_LS %>% 
  filter(year %in% "2024")

mapview(rev_by_state_LS_2024, zcol = "revenue")

## by rgn_id
rev_by_rgn_LS <- ohi_rgns_LS %>% 
  group_by(rgn_id, year) %>% 
  summarise(revenue = sum(value))

rev_by_rgn_LS_sf <- full_join(goc_poly, rev_by_rgn_LS, by = "rgn_id")
```


```{r}
st_write(rev_by_state_LS_sf, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","rev_by_state_LS_sf.shp"))
st_write(rev_by_rgn_LS_sf, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","rev_by_rgn_LS_sf.shp"))
```

```{r}
library(ggplot2)

rev_by_state_LS_2028_2024 <- rev_by_state_LS %>% 
  filter(!year %in% "2025")

ggplot(rev_by_state_LS_2028_2024, aes(x = year, y = revenue)) +
  geom_line(color = "steelblue") +
  geom_point() +
  scale_y_continuous(labels = scales::comma) +
  facet_wrap(~ estado, scales = "free_y") +
  labs(title = "Large scale fishing revenue by state, 2018 - 2024", x = "Year", y = "Revenue") +
  theme_minimal()

### actually, plotly is better to have a fixed y axis and see the differences across states.
library(plotly)

rev_by_state_LS_2028_2024_line_plot <- plotly::plot_ly(rev_by_state_LS_2028_2024, x = ~year, y = ~revenue, color = ~estado, type = "scatter", mode = "lines") %>%
  layout(title = "Large scale fishing revenue by state, 2018 - 2024", 
         xaxis = list(title = "Year"),
         yaxis = list(title = "Revenue (pesos)"))

rev_by_state_LS_2028_2024_line_plot
```


## ECO: small scale (2018 - 2025)

```{r}
library(data.table)

## use either fread or feather/arrow because readRDS is taking a reallllly long time to load and there are 12,153,879 observations of 19 variables.
mex_landings_2000_present_dt <- readRDS(here("/home/shares/ohi/OHI_GOC/_raw_data/CONAPESCA/d2025/SharedByJuanCarlos/mex_landings/data/clean", "mex_landings_2000_present.rds")) %>% as.data.table()

state_mex_landings_2000_present_SS <- mex_landings_2000_present_dt[
  fleet == "small_scale" & 
    state %in% c("BAJA CALIFORNIA SUR","SONORA","SINALOA","BAJA CALIFORNIA","NAYARIT","JALISCO")
]

### check and see what landing sites are available and which are in the GoC
unique(state_mex_landings_2000_present_SS$landing_site)
length(unique(state_mex_landings_2000_present_SS$landing_site)) # 1327 ... soooo many!! too hard to filter out right now... 


### using office name, not because it is accurate, but because it is easier to manually limit to the GoC... FOR NOW
unique(state_mex_landings_2000_present_SS$office_name)

#  [1] "ENSENADA"              "SAN FELIPE"           
#  [3] "EL ROSARIO"            "MEXICALI"             
#  [5] "BAHIA TORTUGAS"        "PUERTO PEÑASCO"       
#  [7] "MAZATLAN"              "PUNTA ABREOJOS"       
#  [9] "GUADALAJARA"           "BAHIA ASUNCION"       
# [11] "LA PAZ"                "CD. CONSTITUCION"     
# [13] "GUASAVE"               "TOPOLOBAMPO"          
# [15] "GUAYMAS"               "SAN QUINTIN"          
# [17] "LOS MOCHIS"            "CHAPALA"              
# [19] "LA REFORMA"            "PUERTO LIBERTAD"      
# [21] "CRUZ DE HUANACAXTLE"   "CABO SAN LUCAS"       
# [23] "SAN CARLOS"            "GUERRERO NEGRO"       
# [25] "BAHIA KINO"            "SANTA ROSALIA"        
# [27] "LORETO"                "NAVOLATO"             
# [29] "ESCUINAPA"             "PEÑITA DE JALTEMBA"   
# [31] "CULIACAN"              "BAHIA DE LOS ANGELES" 
# [33] "CD. OBREGON"           "SAN BLAS"             
# [35] "TECUALA"               "PUERTO VALLARTA"      
# [37] "SANTIAGO IXCUINTLA"    "TEPIC"                
# [39] "VILLA DE JESUS MARIA"  "TIJUANA"              
# [41] "ISLA CEDROS"           "GOLFO DE SANTA CLARA" 
# [43] "BARRA DE NAVIDAD"      "HUATABAMPO"           
# [45] "TUXPAN"                "OCOTLAN"              
# [47] "EL FUERTE"             "HERMOSILLO"           
# [49] "PUERTO PE\xd1ASCO"     "PE\xd1ITA DE JALTEMBA"

```


```{r}
# filter so that the landing sites are in the GoC
## NOTE: did not filter office_name to be wihtin the GoC, since it can all be submitted electronically and is not likely representative of where landings were caught. See JC email (<https://github.com/OHI-GOC/OHI_GOC_issues/issues/28#issuecomment-3357184877>)
goc_mex_landings_2000_present_SS <- state_mex_landings_2000_present_SS[
  !office_name %in% c(
    "ENSENADA",          # Pacific side, N
    "EL ROSARIO",        # Pacific side, Baja CA
    "MEXICALI",          # Inland, not coastal
    "BAHIA TORTUGAS",    # Pacific side
    "PUNTA ABREOJOS",    # Pacific side
    "GUADALAJARA",       # Inland
    "BAHIA ASUNCION",    # Pacific side
    "CD. CONSTITUCION",  # Inland, Baja CA Sur
    "SAN QUINTIN",       # Pacific side, Baja CA
    "CHAPALA",           # Inland, lake
    "GUERRERO NEGRO",    # Pacific side
    "TIJUANA",           # Pacific side, Baja CA
    "ISLA CEDROS",       # Pacific side, Baja CA
    "BARRA DE NAVIDAD",  # Outside the GoC, Jalisco
    "TUXPAN",            # Could be nayarit, but might be Jalisco or veracruz... so do not include for now.
    "OCOTLAN"            # Inland, Jalisco
  )
]
```

```{r}
## now, join with ohi regions...
goc_poly <- st_read(here("spatial/ohi_regions","goc_ohi_rgns.shp"))
st_crs(goc_poly) # not WGS84: Mexico ITRF2008 / LCC
mapview(goc_poly)

goc_rgns_df <- goc_poly %>% 
  st_drop_geometry()

goc_mex_landings_2000_present_SS_prepjoin <- goc_mex_landings_2000_present_SS %>% 
  mutate(estado = case_when(
    state %in% "BAJA CALIFORNIA SUR" ~ "Baja_California_Sur",
    state %in% "BAJA CALIFORNIA"~ "Baja_California",
    state %in% "SONORA" ~ "Sonora",
    state %in% "SINALOA" ~ "Sinaloa",
    state %in% "JALISCO" ~ "Jalisco",
    state %in% "NAYARIT" ~ "Nayarit",
    TRUE ~ ""  # default case for any unmatched states
  ))

write_csv(goc_mex_landings_2000_present_SS_prepjoin, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","goc_mex_landings_2000_present_SS_prepjoin.csv"))


ohi_rgns_SS <- left_join(
  goc_rgns_df,
  goc_mex_landings_2000_present_SS_prepjoin,
  by = "estado",
  relationship = "many-to-many" # anticipated, as because of rgn_id, there are multiple regions per state.  For now, lets give the same information to both Region_1 and Region_2. LATER, we will want to classify landing sites by rgn_id, to make it more accurate. 
)

unique(ohi_rgns_SS$landing_site) # hard to tell if they are in GoC.  914 obs
```

```{r}
## assume revenue is the total value for each year, for all stocks
rev_by_state_SS <- ohi_rgns_SS %>% 
  group_by(estado, year) %>% 
  summarise(revenue = sum(value))

# rev_by_state_SS_sf <- full_join(goc_poly, rev_by_state_SS, by = "estado")
# 
# rev_by_state_SS_2024 <- rev_by_state_SS %>%
#   filter(year %in% "2024")

# mapview(rev_by_state_LS_2024, zcol = "revenue")

## by rgn_id
rev_by_rgn_SS <- ohi_rgns_SS %>% 
  group_by(rgn_id, year) %>% 
  summarise(revenue = sum(value))

# rev_by_rgn_SS_sf <- full_join(goc_poly, rev_by_rgn_SS, by = "rgn_id")
```


```{r}
# st_write(rev_by_state_SS_sf, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","rev_by_state_SS_sf.shp"))
# st_write(rev_by_rgn_SS_sf, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","rev_by_rgn_SS_sf.shp"))
```

```{r}
library(ggplot2)

rev_by_state_SS_2028_2024 <- rev_by_state_SS %>% 
  filter(!year %in% "2025")

ggplot(rev_by_state_SS_2028_2024, aes(x = year, y = revenue)) +
  geom_line(color = "steelblue") +
  geom_point() +
  scale_y_continuous(labels = scales::comma) +
  facet_wrap(~ estado, scales = "free_y") +
  labs(title = "Small scale fishing revenue by state, 2018 - 2024", x = "Year", y = "Revenue") +
  theme_minimal()

### actually, plotly is better to have a fixed y axis and see the differences across states.
library(plotly)

rev_by_state_SS_2028_2024_line_plot <- plotly::plot_ly(rev_by_state_SS_2028_2024, x = ~year, y = ~revenue, color = ~estado, type = "scatter", mode = "lines") %>%
  layout(title = "Small scale fishing revenue by state, 2018 - 2024", 
         xaxis = list(title = "Year"),
         yaxis = list(title = "Revenue (pesos)"))

rev_by_state_SS_2028_2024_line_plot
```



# Was losing Jalisco by joining with ohi rgns!! going to just do by state for now.......

```{r}
rev_by_state_raw_LS <- goc_mex_landings_2000_present_LS %>% 
  group_by(state, year) %>% 
  summarise(revenue = sum(value))

# write_csv(rev_by_state_raw_LS, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","rev_by_state_raw_LS.csv"))

library(plotly)

rev_by_state_raw_LS_2028_2025_line_plot <- plotly::plot_ly(rev_by_state_raw_LS, x = ~year, y = ~revenue, color = ~state, type = "scatter", mode = "lines") %>%
  layout(title = "Large scale fishing revenue by state, 2018 - 2025", 
         xaxis = list(title = "Year"),
         yaxis = list(title = "Revenue (pesos)"))

rev_by_state_raw_LS_2028_2025_line_plot
```


```{r}
rev_by_state_raw_SS <- goc_mex_landings_2000_present_SS %>% 
  group_by(state, year) %>% 
  summarise(revenue = sum(value))

write_csv(rev_by_state_raw_SS, here::here("/home/shares/ohi/OHI_GOC/goal_prep/le/eco/v2025","rev_by_state_raw_SS.csv"))

library(plotly)

rev_by_state_raw_SS_2028_2025_line_plot <- plotly::plot_ly(rev_by_state_raw_SS, x = ~year, y = ~revenue, color = ~state, type = "scatter", mode = "lines") %>%
  layout(title = "Small scale fishing revenue by state, 2018 - 2025", 
         xaxis = list(title = "Year"),
         yaxis = list(title = "Revenue (pesos)"))

rev_by_state_raw_SS_2028_2025_line_plot
```

