################################################################################

Erica Ferrer
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
# Visualization
library(ggplot2)
library(plotly)
library(htmlwidgets)

setwd("/home/ferrer/ohi_goc_prep/BD/")
```

```{r Hem's species occurrance data}
## Data provided by: Hem
## Citation: 2018 publication

# Load in the transect data:
LTER_data<- read_excel("/home/shares/ohi/OHI_GOC/_raw_data/dataMares/GCMP_LTERdata_Nov2025.xlsx")

# Load in the species key:
LTER_SpKey<- read_csv("/home/shares/ohi/OHI_GOC/_raw_data/dataMares/GCMP_LTERdata_SpKey_Nov2025.csv")
```

```{r CONAPESCA master key}
CONAPESCA_Master_SpKey<- read_csv("/home/ferrer/ohi_goc_prep/general/Species_Keys/CleanedMaster_SpKey_Dec012025.csv")

CONAPESCA_SpKey_filtered<- 
```

```{r Hem's species occurrance data}
## Data provided by: Hem
## Citation: 2018 publication

# Load in presence absence data:
Sp_PresenceAbsence_data<- read_csv("/home/shares/ohi/OHI_GOC/_raw_data/Hem_data/GoC_species_ocurrence_clean.csv")

Sp_PresenceAbsence_filtered<- Sp_PresenceAbsence_data %>%
  select(old_name) %>% 
  mutate(old_name = tolower(old_name)) %>%
  distinct()
```

```{r Merge}
LTER_SpKey_filtered<- LTER_SpKey %>% 
  select(Species, Family, Functional_groups) %>% 
  distinct() %>%
  mutate(Species = tolower(Species))

CONAPESCA_SpKey_filtered<- CONAPESCA_Master_SpKey %>% 
  select(estimated_species_name, estimated_family_name, IHH_functional_major_groups_sm) %>%
  distinct() %>%
  mutate(estimated_species_name = tolower(estimated_species_name))

Biodiversity_SpKey <- left_join(
  LTER_SpKey_filtered,
  CONAPESCA_SpKey_filtered,
  by = c("Species" = "estimated_species_name")
)

Biodiversity_SpKey_merge <- left_join(
  Biodiversity_SpKey,
  Sp_PresenceAbsence_data,
  by = c("Species" = "old_name")
)
```

