---
title: "Tourist data (continued)"
output: html_document
date: "2025-8-6"
editor_options: 
  chunk_output_type: console
---

https://github.com/OHI-GOC/OHI_GOC_issues/issues/13

```{r setup, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

library(mapview)
library(sf)
library(tidyverse)
library(here)
library(terra)

```

# INEGI API usage

```{r}
library(httr)
library(jsonlite)
library(rjson)

#Llamado al API
url <-"https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/1002000001/es/00000/false/BISE/2.0/8baba5fd-1dbe-310b-3fda-1cee5cdbd7a1?type=json"
respuesta<-GET(url)
datosGenerales<-content(respuesta,"text")
flujoDatos<-paste(datosGenerales,collapse = " ")

#Obtención de la lista de observaciones 
flujoDatos<-fromJSON(flujoDatos)
flujoDatos<-flujoDatos $Series
flujoDatos<-flujoDatos[[1]] $OBSERVATIONS

#Generación del promedio de la lista de observaciones 
datos<-0;
for (i in 1:length(flujoDatos)){

 datos[i]<-flujoDatos[[i]] $OBS_VALUE
}

datos<-as.numeric(datos)
print(mean(datos))
```

