---
title: 'OHI GoC 2024: Lasting Special Places (LSP): Cultural Centers'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: inline
editor_options: 
  chunk_output_type: inline
---

# INEGI: Servicios de alojamiento temporal y de preparación de alimentos y bebidas (1 de 2) y Servicios de alojamiento temporal y de preparación de alimentos y bebidas (2 de 2)

<https://en.www.inegi.org.mx/app/descarga/?ti=6>

```{r}
library(tidyverse)
library(magrittr)
library(here)
library(janitor)
library(tmaptools)
library(sf)
library(mapview)

sp_1 <- st_read(here("/home/shares/ohi/OHI_GOC/_raw_data/inegi_denue_establishments/denue_00_72_1_shp/conjunto_de_datos","denue_inegi_72_1.shp"))

sp_1_goc <- sp_1 %>% 
  filter(entidad %in% c("Baja California","Baja California Sur","Jalisco","Nayarit","Sinaloa","Sonora"))

sp_1_goc[] <- lapply(sp_1_goc, function(x) {
  if (is.character(x)) iconv(x, from = "", to = "UTF-8", sub = "byte") else x
})

# sp_2_valid <- sp_2 %>% 
#   select(id, geometry)

mapview(sp_1_goc)
```


```{r}
sp_2 <- st_read(here("/home/shares/ohi/OHI_GOC/_raw_data/inegi_denue_establishments/denue_00_72_2_shp/conjunto_de_datos","denue_inegi_72_2.shp"), options = "ENCODING=UTF-8")

# sp_2_dropgeo <- sp_2 %>%
#   st_drop_geometry()
# 
# sp_2_sf <- sp_2_dropgeo %>%
#   st_as_sf(coords = c("longitud", "latitud"),
#            crs = 4326, # WGS84
#            remove = FALSE)
# 
# sapply(sp_2, function(col) {
#   if (is.character(col)) {
#     any(is.na(iconv(col, from = "UTF-8", to = "UTF-8")))
#   } else {
#     FALSE
#   }
# })

unique(sp_2$entidad)

sp_2_goc <- sp_2 %>% 
  filter(entidad %in% c("Baja California","Baja California Sur","Jalisco","Nayarit","Sinaloa","Sonora"))

sp_2_goc[] <- lapply(sp_2_goc, function(x) {
  if (is.character(x)) iconv(x, from = "", to = "UTF-8", sub = "byte") else x
})

# sp_2_valid <- sp_2 %>% 
#   select(id, geometry)

mapview(sp_2_goc)
```


```{r}
denue_71 <- read_csv(here("/home/shares/ohi/OHI_GOC/_raw_data/inegi_denue_establishments/denue_00_71_csv/conjunto_de_datos","denue_inegi_71_.csv")) %>% 
  mutate()

unique(denue_71$localidad) # \x needs to be replaced
unique(denue_71$entidad)
# [1] "Aguascalientes"                  "Baja California"                 "Baja California Sur"             "Campeche"                       
#  [5] "Coahuila de Zaragoza"            "Colima"                          "Chiapas"                         "Chihuahua"                      
#  [9] "Ciudad de M\xe9xico"             "Durango"                         "Guanajuato"                      "Guerrero"                       
# [13] "Hidalgo"                         "Jalisco"                         "M\xe9xico"                       "Michoac\xe1n de Ocampo"         
# [17] "Morelos"                         "Nayarit"                         "Nuevo Le\xf3n"                   "Oaxaca"                         
# [21] "Puebla"                          "Quer\xe9taro"                    "Quintana Roo"                    "San Luis Potos\xed"             
# [25] "Sinaloa"                         "Sonora"                          "Tabasco"                         "Tamaulipas"                     
# [29] "Tlaxcala"                        "Veracruz de Ignacio de la Llave" "Yucat\xe1n"                      "Zacatecas" 

denue_71_goc <- denue_71 %>% 
  filter(entidad %in% c("Baja California","Baja California Sur","Jalisco","Nayarit","Sinaloa","Sonora"))

denue_71_sf <- denue_71_goc %>%
  st_as_sf(coords = c("longitud", "latitud"),
           crs = 4326, # WGS84
           remove = FALSE)
mapview(denue_71_sf)


denue_71_sf[] <- lapply(denue_71_sf, function(x) {
  if (is.character(x)) iconv(x, from = "", to = "UTF-8", sub = "byte") else x
})

mapview(denue_71_sf)
```

