---
title: 'OHI GoC 2025: Tourism & Recreation'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: inline
editor_options: 
  chunk_output_type: console
---

# Merging all indicators into the TR current status score

This script brings in all current status scores for the components of TR, and puts them together. 

```{r}
library(tidyverse)
library(sf)
library(mapview)
library(here)
```


## Quantity

```{r}
cs_quantity <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/tr/v2025/output_quantity","tr_quantity_current_status_121025.csv"))
```

## Quality

### Crime

```{r}
cs_quality_crime <- read_csv(here::here("TR/tr_quality_int/tr_qual_crime_score_120925.csv"))
```

### Activities

```{r}

```



## Sustainability

```{r}

```
