################################################################################

Erica Ferrer
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
# Visualization
library(ggplot2)
library(colorspace)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/BD/")
```

```{r Load clean_names_lowercase function}
clean_names_lowercase <- function(x) {

  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")

  x %>%
    tolower() %>%
    trimws()
}
```

# STEP 1: Load input data ------------------------------

```{r Load HAB scores}
HAB_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/BD_Scores/BD_HAB_Scores/BD_HAB_Scores_df_Jul202026.csv")
# 405 obs., 11 vars.

# Clean HAB dataframe:
HAB_Scores<- HAB_Scores0 %>%
  rename(biome_score= HAB_score)
# 405 obs., 11 vars.
```

```{r Load OCE scores}
OCE_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/BD_Scores/OCE_Scores/OCE_Scores_df_Jul222026.csv")
# 63 obs., 5 vars.

# Clean OCE dataframe:
OCE_Scores<- OCE_Scores0 %>%
  rename(biome_score= OCE_Score)

OCE_Scores$biome_type<- c("open_ocean")
# 63 obs., 6 vars.
```

```{r Load ROK scores}
ROK_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/BD_Scores/ROK_Scores/ROK_Scores_1.0_df_Aug102026.csv")
# 55 obs., 6 vars.

# Clean ROK dataframe:
ROK_Scores<- ROK_Scores0 %>%
  select(-mean_NRSI, -n_reefs) %>%
  rename(biome_score= ROK_score)

ROK_Scores$biome_type<- c("rocky_reef")
# 55 obs., 5 vars.
```

```{r Load SOF scores}
SOF_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/soft_bottom/SOF_outputs/sof_region_scores_per_year.csv")

# Clean SOF dataframe:
colnames(SOF_Scores0)

SOF_Scores <- SOF_Scores0 %>%
  mutate(OHI_region = tolower(gsub(" ", "_", region_clean))) %>%
  select(year, OHI_region, SOF_score) %>%
  rename(biome_score= SOF_score)

SOF_Scores$biome_type<- c("soft_bottom")

# 171 obs., 4 vars.
```

```{r Load SOF scores}
RHO_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/soft_bottom/RHO_outputs/rho_region_scores_per_year.csv")

# Clean RHO dataframe:
colnames(RHO_Scores0)

RHO_Scores<- RHO_Scores0 %>%
  mutate(OHI_region = tolower(gsub(" ", "_", region_clean)),
         RHO_score = RHO_score * 100) %>%
  select(year, OHI_region, RHO_score) %>%
  rename(biome_score= RHO_score)

RHO_Scores$biome_type<- c("rhodolith_bed")

# 152 obs., 4 vars.
```

# STEP 2: Compute regional BD scores ------------------------------

```{r Combine OCE_Scores0 scores}
Biomes_Combined0 <- bind_rows(HAB_Scores, OCE_Scores, ROK_Scores, SOF_Scores, RHO_Scores)
# 846 obs., 12 vars. (as of August 11 2026)

table(Biomes_Combined0$biome_type)
# coastal_dune     mangrove   open_ocean    saltmarsh     seagrass 
#          108          117           63          108           72 
# Great!

# After Aug 5:
# coastal_dune     mangrove   open_ocean   rocky_reef    saltmarsh     seagrass 
#          108          117           63           51          108           72 

# After Aug 11:
# coastal_dune      mangrove    open_ocean rhodolith_bed    rocky_reef     saltmarsh      seagrass 
#          108           117            63           152            55           108            72 
#  soft_bottom 
#          171 

# Great!
```

```{r Compute BD_score}
colnames(Biomes_Combined0)

BD_Scores0 <- Biomes_Combined0 %>%
  select(year, OHI_region, biome_type, biome_score) %>%
  group_by(year, OHI_region) %>%
  summarize(
    BD_score = mean(biome_score, na.rm = TRUE),
    biome_types = paste(unique(biome_type), collapse = ", "),
    .groups = "drop"
  )

# 195 obs., 4 vars.
```

```{r Filter out the years for which we have all habitat types}
BD_Scores<- BD_Scores0 %>%
  filter(year >= 2019, year <= 2024)
# 54 obs., 4 vars.
```

# SAVE BD_Scores ------------------------------

```{r Save BD_Scores}
write.csv(BD_Scores, 
          "/home/ferrer/ohi_goc_prep/BD/BD_Scores/BD_Scores_1.0_df_Aug112026.csv", 
          row.names = FALSE)
# 54 obs., 4 vars.
```

```{r Sanity check final BD_Scores}
colnames(BD_Scores)

summary(BD_Scores$BD_score)

# BEFORE rocky reefs (Aug 5):
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 61.37   67.68   72.35   73.79   80.50   86.50 

# AFTER rocky reefs (Aug 5):
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 61.37   65.30   70.18   72.00   78.31   86.50 

# AFTER RHO and SOF (Aug 11):
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 64.80   73.44   77.20   77.12   82.29   87.63 

# Year 2024 mean for BD scores:
mean(BD_Scores$BD_score[BD_Scores$year == 2024], na.rm = TRUE)
# 71 (BEFORE ROK was added, Aug 5)
# 70 (ROK pulled the score down slightly...)
# 76 (RHO and SOF pulled the scores up quite a bit...)
```

# PLOT BD_Scores  ------------------------------
```{r Load in BD_Scores as needed}
BD_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/BD/BD_Scores/BD_Scores_1.0_df_Aug052026.csv")
# 56 obs., 4 vars.

BD_Scores<- BD_Scores0
```

```{r Region key}
Region_Key0<- read.csv("/home/ferrer/ohi_goc_prep/FP/CONAPESCA_Keys/Spatial_Keys/RegionKey_FINAL_May262026.csv")

colnames(Region_Key0)

Region_Key<- Region_Key0 %>%
  select(OHI_region= OHI_region_est, OHI_region_name) %>%
  distinct()
```

```{r Merge Region_Key to BD_Scores}
BD_Scores<- BD_Scores %>%
  left_join(Region_Key, 
            by = "OHI_region")

# Make sure to order the regions:
Region_order <- c(
  "Western Upper Gulf",
  "Western Midriff Islands",
  "Western Central Gulf",
  "Western Southern Gulf",
  "Eastern Upper Gulf",
  "Eastern Midriff Islands",
  "Southern Sonora Coast",
  "Sinaloa Coast",
  "Southeastern Gulf"
)

BD_Scores <- BD_Scores %>%
  mutate(
    OHI_region_name = factor(
      OHI_region_name,
      levels = Region_order
    )
  )
```

```{r Plot BD_Scores}
unique(BD_Scores$OHI_region_name)

Region_colors<- c(
  "Western Upper Gulf" = "#C03729",
  "Western Midriff Islands" = "#E68C7C",
  "Western Central Gulf" = "#FC8F24",
  "Western Southern Gulf" = "#dcaa38",
  "Eastern Upper Gulf" = "#cbd2a0",
  "Eastern Midriff Islands" = "#98a25a",
  "Southern Sonora Coast" = "#747428",
  "Sinaloa Coast" = "#627391",
  "Southeastern Gulf" = "#8d61a9")

BD_Scores_OverTime<- BD_Scores %>%
  filter(!is.na(OHI_region_name)) %>%
  
  ggplot(aes(
    x = year,
    y = BD_score,
    color = OHI_region_name
  )) +
  
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  
  facet_wrap(~ OHI_region_name, scales = "fixed") +
  
  labs(
    title = "BD Scores by Region [DRAFT]",
    subtitle= "updated: Aug 11 2026",
    y = "BD Score (from 0 to 100)",
    x = "Year"
  ) +
  
  geom_hline(yintercept = 100, linetype = "dashed", color = "grey50") +
  
  ylim(0, 101) +
  
  scale_color_manual(values = Region_colors) +
  
  theme_bw(base_size = 14) +
  theme(
    legend.position = "none",
    strip.text = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

BD_Scores_OverTime
```

```{r Save as PNG}
ggsave(
  filename = sprintf("/home/ferrer/ohi_goc_prep/BD/BD_Scores/BD_Scores_1.0_plot_Aug112026.png"),
  plot = BD_Scores_OverTime,
  width = 12,
  height = 12,
  dpi = 300
)
```