---
title: 'OHI GoC 2025: CCE'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: console
editor_options: 
  chunk_output_type: console
---

# Sense of Pertenencia: Coastal Community Engagement (CCE)

## Adoption of beaches & Maintained cultural hertiage site employees (non-natural cultural sites)

```{r}
ama_tu_playa_progress <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/cce/v2026/output","current_status_ama_tu_playa_progress_040126.csv")) %>% 
  mutate(year = 2025)
colnames(ama_tu_playa_progress)
```

```{r}
cultural_places_scaled_to_population_cs <- read_csv(here::here("/home/shares/ohi/OHI_GOC/goal_prep/sp/cce/v2026/output","cultural_places_scaled_to_population_current_status_quantile_041026.csv")) 
colnames(cultural_places_scaled_to_population_cs)
```

