################################################################################

Erica Ferrer, Ph.D.
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
# Visualization
library(ggplot2)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/FP/")
```

# STEP 1: Load in Raw CONAPESCA data ------------------------------




# PART 4: Merge the cleaned master sp key with landings data ------------------------------
```{r Load data frames if needed}
Master_SpKey_Cleaned <- read_csv("/home/ferrer/ohi_goc_prep/FP/CONAPESCA_Data&Keys/CONAPESCA_Keys/Species_Keys/CleanedMaster_SpKey_Dec012025.csv")
# 802 obs of 41 variables
# Was previously found here: "/home/ferrer/ohi_goc_prep/general/Species_Keys/CleanedMaster_SpKey_Dec012025.csv"

Landings_GoC_Cleaned<- readRDS(here("/home/shares/ohi/OHI_GOC/goal_prep/fis/v2025/int/juan_carlos/GoC_Landings_wKeyWords_2000.present_Dec012025.rds"))
# n = 3716415 obs.
```

```{r Shave down the size of Master_SpKey_filtered}
Master_SpKey_filtered<- Master_SpKey_Cleaned %>% 
  select(recorded_taxa_group, recorded_taxa_name_clean, common_name_clean,
         estimated_species_name, species_est_certainty, estimated_genus_name, estimated_family_name,
         IHH_order, IHH_class, IHH_functional_major_groups_sm, IHH_fishery)
# 802 obs., 11 vars.
```

```{r Merge landings with filtered sp key}
Landings_GoC_Cleaned_wSp <- Landings_GoC_Cleaned %>%
  left_join(
    Master_SpKey_filtered,
    by = c(
      "recorded_taxa_group",
      "recorded_taxa_name_clean",
      "common_name_clean"
    )
  )
# 3716415 obs. as expected, 41 vars.
```

## Save Landings_GoC_Cleaned_wSp rds file
```{r Save this dataframe - landings keywords & species for top groupings: Nov 10 2025}
saveRDS(Landings_GoC_Cleaned_wSp, file="/home/shares/ohi/OHI_GOC/goal_prep/fis/v2025/int/juan_carlos/GoC_Landings_wSp_2000.present_Dec012025.rds")
```