################################################################################

Erica Ferrer
emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################

# PRE-WORK ------------------------------
```{r Clear environment}
rm(list=ls(all=T))
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(zoo) # used for gapfilling RAM data.
# Visualization
library(ggplot2)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)


setwd("/home/ferrer/ohi_goc_prep/FP/")
```

## clean_names_lowercase function
```{r Load clean_names_lowercase function}
# Takes text and standardizes it, which we will need for merging later on:

clean_names_lowercase <- function(x) {

  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")

  x %>%
    tolower() %>%
    trimws()
}
```

## lowercase_function function
```{r lowercase_function}
# Turns all entries lower-case
lowercase_function<- function(x){
  if(is.character(x)){
    tolower(x)
  } else if (is.factor(x)){
    tolower(as.character(x))
  } else {
    x
  }
}
```


# Calculate final FIS scores (merge component scores):

# **DECISION POINT: CPUE versus StockStatus weights!**
```{r Merge ALL dataframes to calculate final FIS Score}
# Check dimensions:
dim(CPUE_Scores_GeoMean) # 70
colnames(CPUE_Scores_GeoMean)

dim(StockStatus_GeoMean) # 255
colnames(StockStatus_GeoMean)

# Merge:
FIS_Scores <- CPUE_Scores_GeoMean %>%
  full_join(
    StockStatus_GeoMean %>% filter(year >= StudyPeriod_low & year <= StudyPeriod_high),
    by = c("year", "OHI_region_est")
  ) %>%
  relocate(StockStatus_SubScore, .before= CPUE_SubScore) %>%
  relocate(GeoMean_StockStatus, .before= GeoMean_CPUE)
# 70 obs. Good! 

# FIS score is 1/3 CPUE versus 2/3 StockStatus:

FIS_Scores<- FIS_Scores %>%
  mutate(
    FIS_Score = (2/3)*StockStatus_SubScore + (1/3)*CPUE_SubScore 
  )
```

```{r Sanity check final FIS_Scores}
colnames(FIS_Scores)

summary(FIS_Scores$FIS_Score)
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 63.44   84.96   90.56   87.99   93.40   99.95

# Year 2024 mean for FP scores:
mean(FIS_Scores$FIS_Score[FIS_Scores$year == 2024], na.rm = TRUE)
```

# SAVE FIS_Scores ------------------------------

```{r Save FIS_Scores}
write.csv(FIS_Scores, 
          "/home/ferrer/ohi_goc_prep/FP/FP_Scores/FIS_Scores/FIS_Scores_df_Jun052026.csv", 
          row.names = FALSE)
# 70 obs., 7 vars.
```


# PLOT FIS_Scores  ------------------------------
```{r Load in FIS_Scores as needed}
FIS_Scores0 <- read.csv("/home/ferrer/ohi_goc_prep/FP/FP_Scores/FIS_Scores/FIS_Scores_df_Jun052026.csv")
# 70 obs., 7 vars.

FIS_Scores<- FIS_Scores0
```

```{r Region key}
Region_Key0<- read.csv("/home/ferrer/ohi_goc_prep/FP/CONAPESCA_Keys/Spatial_Keys/RegionKey_FINAL_May262026.csv")

colnames(Region_Key0)

Region_Key<- Region_Key0 %>%
  select(OHI_region_est, OHI_region_name) %>%
  distinct()
```

```{r Merge Region_Key to FP_Scores}
FIS_Scores<- FIS_Scores %>%
  left_join(Region_Key, 
            by = "OHI_region_est")

# Make sure to order the regions:
region_order <- c(
  "Western Upper Gulf",
  "Western Midriff Islands",
  "Western Central Gulf",
  "Western Southern Gulf",
  "Eastern Upper Gulf",
  "Eastern Midriff Islands",
  "Southern Sonora Coast",
  "Sinaloa Coast",
  "Southeastern Gulf"
)

FIS_Scores <- FIS_Scores %>%
  mutate(
    OHI_region_name = factor(
      OHI_region_name,
      levels = region_order
    )
  )
```

```{r Plot FIS_Scores}
Region_colors<- c(
  "Western Upper Gulf" = "#C03729",
  "Western Midriff Islands" = "#E68C7C",
  "Western Central Gulf" = "#FC8F24",
  "Western Southern Gulf" = "#dcaa38",
  "Eastern Upper Gulf" = "#cbd2a0",
  "Eastern Midriff Islands" = "#98a25a",
  "Southern Sonora Coast" = "#747428",
  "Sinaloa Coast" = "#627391",
  "Southeastern Gulf" = "#8d61a9")

FIS_Scores_overTime<- FIS_Scores %>%
  
  filter(!is.na(OHI_region_name)) %>%
  
  ggplot(aes(x = year, y = FIS_Score, color = OHI_region_name)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  
  facet_wrap(~ OHI_region_name, scales = "fixed") +
  
  geom_hline(yintercept = 100, linetype = "dashed", color = "grey50") +
  
  labs(
    title = "FIS Scores by Region",
    subtitle= "updated: Jul 15 2026",
    y = "FIS Score (from 0 to 100)",
    x = "Year"
  ) +
  
  ylim(0, 101) +
  
  scale_color_manual(values = Region_colors) +
  
  theme_bw(base_size = 14) +
  theme(
    legend.position = "none",
    strip.text = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

FIS_Scores_overTime
```

```{r Save as PNG}
  ggsave(
    filename = sprintf("/home/ferrer/ohi_goc_prep/FP/FP_Scores/FIS_Scores/FIS_Scores_plot_Jul152026.png"),
    plot = FIS_Scores_overTime,
    width = 12,
    height = 12,
    dpi = 300
  )
```