---
title: 'OHI GoC 2025: Mangroves'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
format:
  html:
    code-fold: show
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    theme: cerulean
    highlight-style: haddock
  pdf:
    toc: true
editor: 
  markdown:
    wrap: sentence
  chunk_output_type: inline
editor_options: 
  chunk_output_type: console
---

# Summary

# Setup

```{r}
library(raster)
library(terra)
library(readr)
library(magrittr)
library(mregions2)
library(mapview)
library(sf)
library(tidyverse)
library(lwgeom)
library(here)
library(leaflet.extras2)
library(fasterize)
library(tictoc)
library(kableExtra)
library(plotly)
library(viridis)
library(readr)
library(purrr)
library(doParallel)
library(httr2) # to handle timeouts (error HTTP 524 NA)
library(data.table)
library(leaflet)
library(leaflet.extras)
library(RColorBrewer)

# ---- sources! ----
# source(here("workflow", "R", "common.R")) # file creates objects to process data
## set the mazu and neptune data_edit share based on operating system
dir_M             <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
                       'Darwin'  = '/Volumes/ohi',    ### connect (cmd-K) to smb://mazu/ohi
                       'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

# ---- set year and file path info ----
current_year <- 2025 # Update this in the future!!
version_year <- paste0("v",current_year)
data_dir_version_year <- paste0("d", current_year)

# ---- data directories ----

# raw data directory (on Mazu)
raw_data_dir <- here::here(dir_M, "OHI_GOC", "_raw_data")

# for SIMAR CONABIO mangrove polygons
sc_mangrove_raw_dir <- here::here(dir_M, "OHI_GOC", "_raw_data", "SIMAR_CONABIO", data_dir_version_year, "hab_mangrove","cobertura-manglar")

# for coastline characteristics intermediates
int_dir <- here::here("hab", "hab_mangroves", version_year, "int")

# final output dir
output_dir <- here("hab", "hab_mangroves", version_year, "output")

# spatial data for GoC
goc_spatial <- here("spatial")

# this CRS might be better for visualization, explore.
gulf_crs <- st_crs("+proj=aea +lat_1=23 +lat_2=30 +lat_0=25 +lon_0=-110 +datum=WGS84 +units=m +no_defs")
```


# Exploration


## SIMAR CONABIO 

```{r}
# read in the mangrove polygons from SIMAR CONABIO
sc_mangroves_raw <- st_read(here::here(sc_mangrove_raw_dir, "cobertura-manglar.shp")) # WGS 84, polygon data
head(sc_mangroves_raw)
st_crs(sc_mangroves_raw) # WGS84, can be used to crop global data
```
### Limit to GoC Ecoregion

```{r}
# read in ecoregion shapefiles in 
eco_hr_latlon <- st_read(here(goc_spatial, "GoC_polygon_ecoregion_latlon.shp"))
# mapview(eco_hr_latlon)
head(eco_hr_latlon)

eco_hr_eqarea <- st_read(here(goc_spatial, "GoC_polygon_ecoregion_eqarea.shp"))
# mapview(eco_hr_eqarea)

# check CRS of ecoregion boundary
st_crs(eco_hr_latlon) # WGS84, can be used to crop global data

# transform to gulf_CRS
# eco_hr_albers <- st_transform(eco_hr_eqarea, crs = "+proj=aea +lat_1=23 +lat_2=30 +lat_0=25 +lon_0=-110 +datum=WGS84 +units=m +no_defs")
# st_crs(eco_hr_albers) # double check it worked well
# mapview(eco_hr_albers) # looks good!
```

```{r}
# crop the global data to the gulf ecoregion boundary
sc_mangroves_cropped <- st_intersection(sc_mangroves_raw, eco_hr_latlon)
head(sc_mangroves_cropped) # attributes are conserved
unique(sc_mangroves_cropped$FECHA) # all data is from 2020
unique(sc_mangroves_cropped$CLASE) # all clase 5, mangroves
length(unique(sc_mangroves_cropped$COV_ID)) # v2025: 1712 separate mangrove polygons documented

mapview(sc_mangroves_cropped)

# write_sf(pc_mb_cropped, here::here("hab", "hab_muddy_coasts", "v2025"," ","www", "pc_mb_cropped_wgs84.shp"))
write_sf(sc_mangroves_cropped, here::here(int_dir, "sc_mangroves_cropped_wgs84.shp"))
sc_mangroves_cropped <- read_sf(here::here(int_dir, "sc_mangroves_cropped_wgs84.shp"))
write_sf(sc_mangroves_cropped, here::here(dir_M, "OHI_GOC/_raw_data/SIMAR_CONABIO/d2025/hab_mangrove/int/sc_mangroves_cropped_wgs84.shp"))
```






