################################################################################ 

For questions contact: Erica Ferrer, Ph.D. at emferrer@ucsd.edu - OR - ferrer@nceas.ucsb.edu

################################################################################ 

# PRE-WORK ------------------------------

```{r Clear environment}
rm(list=ls(all=T))
```

```{r Set working directory}
setwd("/home/ferrer/ohi_goc_prep/NP/v2026/")
```

```{r Load Libraries & Set WD}
# Read In
library(here)
library(readxl)
library(readr)
# Data Processing
library(tidyverse)
library(dplyr)
library(purrr)
library(tidytext)  # for reorder_within and scale_x_reordered
library(lubridate)
library(janitor)
library(stringi)
library(stringr)
library(data.table)
library(broom)
# Visualization
library(ggplot2)
library(ggforce)
library(plotly)
library(htmlwidgets)
library(htmltools)
```

```{r Load clean_names_lowercase function}
clean_names_lowercase <- function(x) {
  x <- iconv(x, from = "", to = "UTF-8", sub = "")
  x <- stringi::stri_trans_general(x, "Latin-ASCII")
  x %>%
    tolower() %>%
    trimws()
}
```

# NP Final Scores ------------------------------

```{r Load in Sub-Scores}
# Fish oil fish meal (FOFM)
FOFM_SubScores0<- read.csv("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/FOFM_SubScores/FOFM_SubScores_df_Sep052026.csv")
FOFM_SubScores<- FOFM_SubScores0

# Aquarium trade (AQRM)
AQRM_SubScores0<- read.csv("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/AQRM_SubScores/AQRM_SubScores_df_Sep052026.csv")
AQRM_SubScores<- AQRM_SubScores0

# Sea shells (SHEL)
SHEL_SubScores0<- read.csv("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/SHEL_SubScores/SHEL_SubScores_df_Sep052026.csv")
SHEL_SubScores<- SHEL_SubScores0

# Fisheries residues (RESD)
RESD_SubScores0<- read.csv("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/RESD_SubScores/RESD_SubScores_df_Sep062026.csv")
RESD_SubScores<- RESD_SubScores0

# Shark fins (FINS)
FINS_SubScores0<- read.csv("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/FINS_SubScores/FINS_SubScores_df_Sep062026.csv")
FINS_SubScores<- FINS_SubScores0

# Salt production (SALT)
SALT_SubScores0<- read.csv("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/SALT_SubScores/SALT_SubScores_df_Sep062026.csv")
SALT_SubScores<- SALT_SubScores0
```

# Merge ---

```{r Prep dataframes for merging}
# Fish oil fish meal (FOFM)
colnames(FOFM_SubScores)

FOFM_SubScores_simple<- FOFM_SubScores %>%
  select(year, OHI_region= OHI_region_est, FOFM_score)


# Aquarium trade (AQRM)
colnames(AQRM_SubScores)

AQRM_SubScores_simple<- AQRM_SubScores %>%
  select(year, OHI_region= OHI_region_est, AQRM_score)


# Sea shells (SHEL)
colnames(SHEL_SubScores)

SHEL_SubScores_simple<- SHEL_SubScores %>%
  select(year, OHI_region= OHI_region_est, SHEL_score)


# Other residues (RESD)
colnames(RESD_SubScores)

RESD_SubScores_simple<- RESD_SubScores %>%
  select(year, OHI_region= OHI_region_est, RESD_score)


# Shark fins (FINS)
colnames(FINS_SubScores)

FINS_SubScores_simple<- FINS_SubScores %>%
  select(year, OHI_region= OHI_region_est, FINS_score)


# Salt production (SALT)
colnames(SALT_SubScores)

SALT_SubScores_simple<- SALT_SubScores %>%
  select(year, OHI_region, SALT_score)

SALT_SubScores_simple<- SALT_SubScores_simple %>%
  mutate(
    OHI_region = clean_names_lowercase(OHI_region)
  )
```

```{r Merge Component Scores}
NP_Scores0 <- list(
  FOFM_SubScores_simple,
  AQRM_SubScores_simple,
  SHEL_SubScores_simple,
  RESD_SubScores_simple,
  FINS_SubScores_simple,
  SALT_SubScores_simple
) %>%
  reduce(full_join, by = c("year", "OHI_region"))

NP_Scores<- NP_Scores0 %>%
  filter(!is.na(OHI_region)) %>%
  filter(year <= 2024)
```

```{r Calculate NP_Scores}
colnames(NP_Scores)

NP_Scores <- NP_Scores %>%
  mutate(
    NP_Score = rowMeans(
      select(., FOFM_score, AQRM_score, SHEL_score,
                    RESD_score, FINS_score, SALT_score),
      na.rm = TRUE
    ),
    NP_Score_n_components = rowSums(
      !is.na(select(., FOFM_score, AQRM_score, SHEL_score,
                    RESD_score, FINS_score, SALT_score))
    )
  )
```

```{r SAVE NP regional scores}
write.csv(
  NP_Scores,
  file= "/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/NP_Scores_1.0_df_Sep062026.csv",
  row.names = FALSE
)
```

# Plot final NP_Scores:

```{r Load in NP_Scores as needed}
NP_Scores0<- read.csv("/home/ferrer/ohi_goc_prep/NP/v2026/NP_Scores/NP_Scores_1.0_df_Sep062026.csv")

NP_Scores<- NP_Scores0
```

```{r Merge Region_Key to NP_Scores}
NP_Scores<- NP_Scores %>%
  left_join(Region_Key, 
            by = c("OHI_region"= "OHI_region_est"))
# 63 obs., 11 vars.

# Make sure to order the regions:
region_order <- c(
  "Western Upper Gulf",
  "Western Midriff Islands",
  "Western Central Gulf",
  "Western Southern Gulf",
  "Eastern Upper Gulf",
  "Eastern Midriff Islands",
  "Southern Sonora Coast",
  "Sinaloa Coast",
  "Southeastern Gulf"
)

NP_Scores <- NP_Scores %>%
  mutate(
    OHI_region_name = factor(
      OHI_region_name,
      levels = region_order
    )
  )
```

```{r Plot NP_Scores over time by region}
Region_colors<- c(
  "Western Upper Gulf" = "#C03729",
  "Western Midriff Islands" = "#E68C7C",
  "Western Central Gulf" = "#FC8F24",
  "Western Southern Gulf" = "#dcaa38",
  "Eastern Upper Gulf" = "#cbd2a0",
  "Eastern Midriff Islands" = "#98a25a",
  "Southern Sonora Coast" = "#747428",
  "Sinaloa Coast" = "#627391",
  "Southeastern Gulf" = "#8d61a9")

# Plot over time:
NP_Scores_OverTime <- NP_Scores %>%
  filter(!is.na(OHI_region)) %>%
  
  ggplot(aes(x = year, 
             y = NP_Score, 
             color = OHI_region_name)) +
  
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  
  facet_wrap(~ OHI_region_name, scales = "fixed") +
  
  labs(
    title = "NP Scores by Region",
    subtitle= "summed FOFM, AQRM, SHEL, RESD, FINS, SALT scores", 
    caption = "updated: Sep 6 2026",
    y = "NP Current Status (0 to 100)",
    x = "Year"
  ) +
  
  ylim(c(0, 101)) +
  
  geom_hline(yintercept = 100, linetype = "dashed", color = "grey50") +
  
  scale_color_manual(values = Region_colors) +
  
  theme_bw(base_size = 14) +
  theme(
    legend.position = "none",
    strip.text = element_text(size = 14, face = "bold"),
    plot.title = element_text(size = 16, face = "bold")
  )

NP_Scores_OverTime
```


# FINAL STEP: SAVE NP SCORES ------------------------------
```{r SAVE NP score plot}
ggsave(
  plot = NP_Scores_OverTime,
  filename = "/home/ferrer/ohi_goc_prep/NP/v2025/NP_Scores/NP_Scores_1.0_plot_Sep062026.png",
  width = 12,
  height = 8,
  dpi = 300
)
```